// 내장 단어팩 (file:// 에서도 동작하도록 JS로 내장) — build_packs.py 가 생성
window.VOCA_BUILD = '0911.1754';
window.VOCA_PACKS = [
  {
    "pack_id": "neungyul-voca-middle-2025-day03",
    "title": "능률VOCA 중등 필수 [2025] DAY 03",
    "source": "프렙업 영어학원 프린트 (PAGE 3/50)",
    "words": [
      {
        "n": 1,
        "en": "pack",
        "ko": "[동] 1. (짐을) 싸다 2. 포장하다 / [명] (한) 갑[통/상자]",
        "ipa": "/pæk/",
        "stress": "PACK",
        "emoji": "🎒📦",
        "ex": "I need to pack my bag tonight.",
        "ex_ko": "나 오늘 밤에 가방 싸야 해.",
        "mnemonic": "'팩'하고 상자에 눌러 담는 소리. 짐을 팩팩 눌러 싸는 장면을 떠올리세요."
      },
      {
        "n": 2,
        "en": "male",
        "ko": "[형] 남성[수컷]의 / [명] 남성, 수컷",
        "ipa": "/meɪl/",
        "stress": "MALE",
        "emoji": "♂️👦",
        "ex": "The male lion has a big mane.",
        "ex_ko": "수컷 사자는 큰 갈기가 있어.",
        "mnemonic": "발음이 '메일(mail)'과 똑같아요. 남자한테 온 메일이라고 묶어서 기억하세요."
      },
      {
        "n": 3,
        "en": "finally",
        "ko": "[부] 1. 마침내, 결국 2. 마지막으로",
        "ipa": "/ˈfaɪnəli/",
        "stress": "FI-nal-ly",
        "emoji": "🏁😮‍💨",
        "ex": "I finally finished my science homework.",
        "ex_ko": "나 드디어 과학 숙제 끝냈어.",
        "mnemonic": "final(마지막) + ly. 마지막에 가서야, 즉 '마침내'예요."
      },
      {
        "n": 4,
        "en": "sometime",
        "ko": "[부] (과거, 미래의) 언제, 언젠가",
        "ipa": "/ˈsʌmtaɪm/",
        "stress": "SOME-time",
        "emoji": "📅❓",
        "ex": "Let's watch a movie sometime next week.",
        "ex_ko": "다음 주 언젠가 영화 보자.",
        "mnemonic": "some(어떤) + time(때) = 어떤 때, 즉 '언젠가'. 정확한 날짜는 몰라요."
      },
      {
        "n": 5,
        "en": "valley",
        "ko": "[명] 계곡, 골짜기",
        "ipa": "/ˈvæli/",
        "stress": "VAL-ley",
        "emoji": "🏞️⛰️",
        "ex": "We hiked down into the green valley.",
        "ex_ko": "우리는 초록 계곡으로 걸어 내려갔어.",
        "mnemonic": "'밸리'는 배구 '발리'처럼 푹 꺼진 곳. 산과 산 사이 푹 팬 골짜기예요."
      },
      {
        "n": 6,
        "en": "bark",
        "ko": "[동] (개가) 짖다",
        "ipa": "/bɑːrk/",
        "stress": "BARK",
        "emoji": "🐕🗯️",
        "ex": "My dog barks at every stranger.",
        "ex_ko": "우리 개는 낯선 사람만 보면 짖어.",
        "mnemonic": "'박!' 하고 개가 짖는 소리예요. 발음 그대로 개 짖는 소리로 외우세요."
      },
      {
        "n": 7,
        "en": "crash",
        "ko": "[동] 충돌[추락]하다 / [명] (자동차의) 충돌, (비행기의) 추락",
        "ipa": "/kræʃ/",
        "stress": "CRASH",
        "emoji": "💥🚗",
        "ex": "Two cars crashed near my school today.",
        "ex_ko": "오늘 학교 근처에서 차 두 대가 충돌했어.",
        "mnemonic": "'크래쉬!' 자체가 쾅 부딪히는 소리. 컴퓨터가 '크래시' 나는 것도 같은 말이에요."
      },
      {
        "n": 8,
        "en": "nature",
        "ko": "[명] 1. 자연 2. 천성, 본성",
        "ipa": "/ˈneɪtʃər/",
        "stress": "NA-ture",
        "emoji": "🌳🦋",
        "ex": "I love walking in nature after school.",
        "ex_ko": "나는 방과 후에 자연 속을 걷는 걸 좋아해.",
        "mnemonic": "'네이처'는 태어난(nat-) 그대로의 모습. 그래서 '자연'이자 타고난 '본성'이에요."
      },
      {
        "n": 9,
        "en": "harmony",
        "ko": "[명] 1. 조화, 화합 2. 화음",
        "ipa": "/ˈhɑːrməni/",
        "stress": "HAR-mo-ny",
        "emoji": "🎶🤝",
        "ex": "The two singers sang in perfect harmony.",
        "ex_ko": "두 가수는 완벽한 화음으로 노래했다.",
        "mnemonic": "\"하모니카\"의 하모니! 여러 소리가 섞여 어울리는 게 조화, 화음이야."
      },
      {
        "n": 10,
        "en": "wonder",
        "ko": "[동] 궁금하다 / [명] 감탄, 놀라움",
        "ipa": "/ˈwʌndər/",
        "stress": "WON-der",
        "emoji": "🤔❓",
        "ex": "I wonder why she didn't come today.",
        "ex_ko": "걔가 오늘 왜 안 왔는지 궁금해.",
        "mnemonic": "\"원더\"풀! 놀라운 걸 보면 \"왜지?\" 하고 궁금해지지."
      },
      {
        "n": 11,
        "en": "able",
        "ko": "[형] 1. …할 수 있는 2. 능력 있는, 유능한",
        "ipa": "/ˈeɪbl/",
        "stress": "A-ble",
        "emoji": "💪✅",
        "ex": "I'm able to finish this homework tonight.",
        "ex_ko": "나 오늘 밤에 이 숙제 끝낼 수 있어.",
        "mnemonic": "\"에이, 불~\" 껐어! 불도 끌 수 있는 능력자. …할 수 있다."
      },
      {
        "n": 12,
        "en": "pain",
        "ko": "[명] (육체적, 정신적) 통증, 고통",
        "ipa": "/peɪn/",
        "stress": "PAIN",
        "emoji": "🤕😣",
        "ex": "I felt a sharp pain in my leg.",
        "ex_ko": "다리에 날카로운 통증이 느껴졌어.",
        "mnemonic": "\"페인\"트 통이 발등에 쿵! 아픈 통증이 확 오지."
      },
      {
        "n": 13,
        "en": "uniform",
        "ko": "[명] 제복, 유니폼 / [형] 균일한, 일정한",
        "ipa": "/ˈjuːnɪfɔːrm/",
        "stress": "U-ni-form",
        "emoji": "👔🎽",
        "ex": "We have to wear a school uniform every day.",
        "ex_ko": "우리는 매일 교복을 입어야 해.",
        "mnemonic": "uni(하나)+form(모양). 다 같은 하나의 모양으로 입는 옷이 제복."
      },
      {
        "n": 14,
        "en": "beauty",
        "ko": "[명] 1. 아름다움, 미 2. 미인",
        "ipa": "/ˈbjuːti/",
        "stress": "BEAU-ty",
        "emoji": "🌸✨",
        "ex": "We stopped to enjoy the beauty of the sunset.",
        "ex_ko": "우리는 노을의 아름다움을 즐기려고 멈췄어.",
        "mnemonic": "\"뷰티\"숍은 아름다움을 만드는 곳! 그대로 아름다움, 미."
      },
      {
        "n": 15,
        "en": "taste",
        "ko": "[명] 맛 / [동] 1. 맛이 나다 2. 맛보다",
        "ipa": "/teɪst/",
        "stress": "TASTE",
        "emoji": "👅🍜",
        "ex": "This soup tastes a little too salty.",
        "ex_ko": "이 국은 좀 너무 짠 맛이 나.",
        "mnemonic": "\"테이스트\"—떼서 입에 스윽! 맛보다, 맛이 나다."
      },
      {
        "n": 16,
        "en": "without",
        "ko": "[전] 1. … 없이 2. …하지 않고",
        "ipa": "/wɪˈðaʊt/",
        "stress": "with-OUT",
        "emoji": "🚫🥤",
        "ex": "I can't study without my phone nearby.",
        "ex_ko": "나는 폰이 옆에 없으면 공부를 못 해.",
        "mnemonic": "with(함께)에서 out(밖으로) 나가버림. 그래서 \"… 없이\"."
      },
      {
        "n": 17,
        "en": "sunlight",
        "ko": "[명] 햇빛, 햇살",
        "ipa": "/ˈsʌnˌlaɪt/",
        "stress": "SUN-light",
        "emoji": "☀️🌤️",
        "ex": "Open the curtains and let the sunlight in.",
        "ex_ko": "커튼 열고 햇빛 좀 들어오게 해.",
        "mnemonic": "sun(태양) + light(빛) = 햇빛. 두 쉬운 단어를 그냥 붙인 말이에요."
      },
      {
        "n": 18,
        "en": "exact",
        "ko": "[형] 정확한",
        "ipa": "/ɪɡˈzækt/",
        "stress": "ex-ACT",
        "emoji": "🎯📏",
        "ex": "Tell me the exact time of the movie.",
        "ex_ko": "영화 시작하는 정확한 시간을 말해 줘.",
        "mnemonic": "\"이그잭!\" 자를 딱 대고 잰 듯 정확한. 뒤에 액트(ACT)에 힘줘서 읽어요."
      },
      {
        "n": 19,
        "en": "popular",
        "ko": "[형] 1. 인기 있는 2. 대중의, 대중적인",
        "ipa": "/ˈpɑːpjələr/",
        "stress": "PO-pu-lar",
        "emoji": "⭐🙌",
        "ex": "That song is really popular at our school.",
        "ex_ko": "그 노래 우리 학교에서 진짜 인기 많아.",
        "mnemonic": "people(사람들)과 뿌리가 같아요. 사람들이 다 좋아하니까 인기 있는."
      },
      {
        "n": 20,
        "en": "noisy",
        "ko": "[형] 떠들썩한, 시끄러운",
        "ipa": "/ˈnɔɪzi/",
        "stress": "NOI-sy",
        "emoji": "📢🔊",
        "ex": "The classroom is too noisy to study.",
        "ex_ko": "교실이 공부하기엔 너무 시끄러워.",
        "mnemonic": "noise(소음)에 -y 붙이면 시끄러운. \"노이지\"하면 귀 아픈 소리 떠올려요."
      },
      {
        "n": 21,
        "en": "pill",
        "ko": "[명] 알약, 정제",
        "ipa": "/pɪl/",
        "stress": "PILL",
        "emoji": "💊",
        "ex": "Take this pill after you eat lunch.",
        "ex_ko": "점심 먹고 나서 이 알약 먹어.",
        "mnemonic": "\"필\"수로 먹어야 하는 알약! 삼킬 때 \"삐~ㄹ\" 넘어가는 느낌."
      },
      {
        "n": 22,
        "en": "be in trouble",
        "ko": "어려움[곤경]에 처하다",
        "ipa": "/bi ɪn ˈtrʌbəl/",
        "stress": "be in TROU-ble",
        "emoji": "😰⚠️",
        "ex": "I'll be in trouble if I'm late again.",
        "ex_ko": "또 늦으면 나 곤란해질 거야.",
        "mnemonic": "trouble(문제) 안에(in) 들어가 있다 = 곤경에 처하다."
      },
      {
        "n": 23,
        "en": "think up",
        "ko": "…을 생각해내다",
        "ipa": "/ˌθɪŋk ˈʌp/",
        "stress": "think UP",
        "emoji": "💡🤔",
        "ex": "Let's think up a good name for our team.",
        "ex_ko": "우리 팀 이름 좋은 걸로 하나 생각해 내자.",
        "mnemonic": "생각(think)을 머리 위로(up) 쑥 끌어올리다 = 생각해내다."
      },
      {
        "n": 24,
        "en": "be famous for",
        "ko": "…로 유명하다",
        "ipa": "/bi ˈfeɪməs fɔːr/",
        "stress": "be FA-mous for",
        "emoji": "🏅🍜",
        "ex": "This town is famous for its fried chicken.",
        "ex_ko": "이 동네는 치킨으로 유명해.",
        "mnemonic": "famous(유명한) 뒤에 for는 \"~때문에\". 무엇 때문에 유명한지 알려줘요."
      }
    ]
  },
  {
    "pack_id": "neungyul-voca-middle-2025-day04",
    "title": "능률VOCA 중등 필수 [2025] DAY 04",
    "source": "프렙업 영어학원 프린트 (PAGE 4/50)",
    "words": [
      {
        "n": 1,
        "en": "female",
        "ko": "[형] 여성[암컷]의 / [명] 여성, 암컷",
        "ipa": "/ˈfiːmeɪl/",
        "stress": "FE-male",
        "emoji": "👩♀️",
        "ex": "The female lion hunts for the whole group.",
        "ex_ko": "암사자가 무리 전체를 위해 사냥해요.",
        "mnemonic": "fe(피메일)는 male(남성) 앞에 fe가 붙은 것. male이 아닌 쪽, 즉 여성이에요."
      },
      {
        "n": 2,
        "en": "regular",
        "ko": "[형] 1. 정기적인, 규칙적인 2. (크기가) 보통의, 표준적인",
        "ipa": "/ˈreɡjələr/",
        "stress": "RE-gu-lar",
        "emoji": "📅⏰",
        "ex": "I have a regular meeting every Monday morning.",
        "ex_ko": "저는 매주 월요일 아침에 정기 회의가 있어요.",
        "mnemonic": "\"레귤러 사이즈\" 하면 보통 크기죠. 늘 똑같은 게 regular예요."
      },
      {
        "n": 3,
        "en": "coin",
        "ko": "[명] 동전",
        "ipa": "/kɔɪn/",
        "stress": "COIN",
        "emoji": "🪙",
        "ex": "I found an old coin under my bed.",
        "ex_ko": "침대 밑에서 오래된 동전을 하나 찾았어요.",
        "mnemonic": "\"코인 노래방\"의 그 코인! 동전 넣고 노래 부르죠."
      },
      {
        "n": 4,
        "en": "prepare",
        "ko": "[동] 1. 준비하다 2. (음식을) 준비[마련]하다",
        "ipa": "/prɪˈper/",
        "stress": "pre-PARE",
        "emoji": "🍳📝",
        "ex": "I need to prepare for tomorrow's math test.",
        "ex_ko": "내일 수학 시험을 준비해야 해요.",
        "mnemonic": "pre(미리) + pare(다듬다). 미리 다듬어 두는 게 준비예요."
      },
      {
        "n": 5,
        "en": "quite",
        "ko": "[부] 꽤, 상당히",
        "ipa": "/kwaɪt/",
        "stress": "QUITE",
        "emoji": "👍📈",
        "ex": "This soup is quite spicy for me.",
        "ex_ko": "이 국은 저한테 꽤 매워요.",
        "mnemonic": "\"콰이트!\" 하고 감탄할 만큼 꽤 대단하다고 외워요."
      },
      {
        "n": 6,
        "en": "alike",
        "ko": "[형] 비슷한 / [부] 비슷하게, 마찬가지로",
        "ipa": "/əˈlaɪk/",
        "stress": "a-LIKE",
        "emoji": "👯👀",
        "ex": "My sister and I look very much alike.",
        "ex_ko": "언니랑 저는 정말 많이 닮았어요.",
        "mnemonic": "a + like(~같은). 서로 '같은' 모습이니까 비슷한 거예요."
      },
      {
        "n": 7,
        "en": "alarm",
        "ko": "[명] 1. 경보(기) 2. 자명종, 알람",
        "ipa": "/əˈlɑːrm/",
        "stress": "a-LARM",
        "emoji": "⏰🚨",
        "ex": "My alarm didn't ring, so I was late.",
        "ex_ko": "알람이 안 울려서 지각했어요.",
        "mnemonic": "\"알람\" 그대로예요. 시끄럽게 울려서 위험도 알리는 경보."
      },
      {
        "n": 8,
        "en": "bored",
        "ko": "[형] 지루해하는",
        "ipa": "/bɔːrd/",
        "stress": "BORED",
        "emoji": "😑🥱",
        "ex": "I'm so bored on rainy weekends at home.",
        "ex_ko": "비 오는 주말에 집에 있으면 너무 지루해요.",
        "mnemonic": "\"보드\"게임도 없이 혼자 있으면 지루하죠. 보얼드=지루한."
      },
      {
        "n": 9,
        "en": "freeze",
        "ko": "[동] 얼다, 얼리다, 냉동하다",
        "ipa": "/friːz/",
        "stress": "FREEZE",
        "emoji": "🧊❄️",
        "ex": "The water in the bottle will freeze tonight.",
        "ex_ko": "병 속의 물이 오늘 밤 얼 거야.",
        "mnemonic": "'프리즈!'하고 외치면 그 자리에서 얼어붙죠. 얼음처럼 굳는 게 freeze예요."
      },
      {
        "n": 10,
        "en": "language",
        "ko": "[명] 언어, 말",
        "ipa": "/ˈlæŋɡwɪdʒ/",
        "stress": "LAN-guage",
        "emoji": "🗣️💬🌍",
        "ex": "How many languages can you speak?",
        "ex_ko": "너는 몇 개 언어를 말할 수 있어?",
        "mnemonic": "'랭귀지'는 혀(라틴어 lingua=혀)에서 왔어요. 혀로 하는 것이 언어죠."
      },
      {
        "n": 11,
        "en": "nobody",
        "ko": "[대] 아무도 … 않다, 아무도 없다",
        "ipa": "/ˈnoʊbɑːdi/",
        "stress": "NO-bod-y",
        "emoji": "🚫👤",
        "ex": "Nobody was home when I got back.",
        "ex_ko": "내가 돌아왔을 때 아무도 집에 없었어.",
        "mnemonic": "no(없다) + body(몸). 몸이 하나도 없으니 '아무도 없다'예요."
      },
      {
        "n": 12,
        "en": "teenager",
        "ko": "[명] 십 대",
        "ipa": "/ˈtiːneɪdʒər/",
        "stress": "TEEN-ag-er",
        "emoji": "🧑‍🎓📱",
        "ex": "Most teenagers love listening to music.",
        "ex_ko": "대부분의 십 대는 음악 듣는 걸 좋아해.",
        "mnemonic": "thirTEEN~nineTEEN, 끝이 teen인 나이(13~19살)가 바로 teenager예요."
      },
      {
        "n": 13,
        "en": "chance",
        "ko": "[명] 1. 가능성 2. 기회 3. 우연",
        "ipa": "/tʃæns/",
        "stress": "CHANCE",
        "emoji": "🎲🍀",
        "ex": "Give me one more chance, please.",
        "ex_ko": "나에게 한 번만 더 기회를 줘.",
        "mnemonic": "'찬스!'라고 외칠 때를 떠올려요. 딱 찾아온 기회, 가능성이 chance."
      },
      {
        "n": 14,
        "en": "curl",
        "ko": "[동] 곱슬곱슬하다, 곱슬곱슬하게 하다 / [명] 곱슬머리",
        "ipa": "/kɜːrl/",
        "stress": "CURL",
        "emoji": "🌀💇",
        "ex": "She curls her hair before every party.",
        "ex_ko": "그녀는 파티마다 머리를 곱슬곱슬하게 말아.",
        "mnemonic": "'컬 파마'할 때 그 컬! 머리카락이 동그랗게 말리는 게 curl이에요."
      },
      {
        "n": 15,
        "en": "planet",
        "ko": "[명] 행성",
        "ipa": "/ˈplænɪt/",
        "stress": "PLAN-et",
        "emoji": "🪐🌍",
        "ex": "Mars is the fourth planet from the sun.",
        "ex_ko": "화성은 태양에서 네 번째 행성이야.",
        "mnemonic": "'플라넷'—우주에 넷(net)처럼 퍼진 별들. 태양 둘레를 도는 행성이에요."
      },
      {
        "n": 16,
        "en": "deaf",
        "ko": "[형] 귀가 먹은, 청각 장애가 있는",
        "ipa": "/def/",
        "stress": "DEAF",
        "emoji": "🦻🚫👂",
        "ex": "My grandfather is deaf in one ear.",
        "ex_ko": "우리 할아버지는 한쪽 귀가 안 들리셔.",
        "mnemonic": "'데프'—소리가 덮여서 안 들려요. 귀가 막힌 상태가 deaf예요."
      },
      {
        "n": 17,
        "en": "invent",
        "ko": "[동] 발명하다",
        "ipa": "/ɪnˈvent/",
        "stress": "in-VENT",
        "emoji": "💡🔧",
        "ex": "He wants to invent a robot that cleans rooms.",
        "ex_ko": "그는 방을 청소하는 로봇을 발명하고 싶어 해.",
        "mnemonic": "'인(in) 벤트(vent, 통풍구)'를 처음 뚫은 사람이 발명가! 안쪽에 새 길을 내는 게 발명이야."
      },
      {
        "n": 18,
        "en": "soil",
        "ko": "[명] 흙, 토양",
        "ipa": "/sɔɪl/",
        "stress": "SOIL",
        "emoji": "🌱🟤",
        "ex": "This soil is good for growing tomatoes.",
        "ex_ko": "이 흙은 토마토 키우기에 좋아.",
        "mnemonic": "'쏘일까?' 하고 흙에 씨앗을 쏘아 심는 장면. 씨를 쏘는 곳이 흙이야."
      },
      {
        "n": 19,
        "en": "noodle",
        "ko": "[명] 국수",
        "ipa": "/ˈnuːdl/",
        "stress": "NOO-dle",
        "emoji": "🍜🥢",
        "ex": "I ate a big bowl of noodles for lunch.",
        "ex_ko": "나 점심으로 국수 한 그릇 크게 먹었어.",
        "mnemonic": "'누들누들' 늘어지는 면발. 소리가 그대로 국수의 흐물흐물한 모습이야."
      },
      {
        "n": 20,
        "en": "stair",
        "ko": "[명] 계단",
        "ipa": "/ster/",
        "stress": "STAIR",
        "emoji": "🪜🚶",
        "ex": "She ran up the stairs to her room.",
        "ex_ko": "그 애는 자기 방으로 계단을 뛰어 올라갔어.",
        "mnemonic": "'스테어'는 '스타(star)처럼 위로' 올라가는 계단. 한 칸씩 별을 향해 올라가."
      },
      {
        "n": 21,
        "en": "comedy",
        "ko": "[명] 코미디, 희극",
        "ipa": "/ˈkɑːmədi/",
        "stress": "CO-me-dy",
        "emoji": "😂🎭",
        "ex": "We watched a funny comedy movie last night.",
        "ex_ko": "우리 어젯밤에 웃긴 코미디 영화 봤어.",
        "mnemonic": "'코미디'는 그대로 코미디! 코가 미친 듯이 웃겨 벌렁거리는 장면을 떠올려."
      },
      {
        "n": 22,
        "en": "calm down",
        "ko": "진정하다, …을 진정시키다",
        "ipa": "/kɑːm daʊn/",
        "stress": "CALM down",
        "emoji": "😮‍💨🧘",
        "ex": "Calm down and tell me what happened.",
        "ex_ko": "진정하고 무슨 일이 있었는지 말해 봐.",
        "mnemonic": "'캄(calm) 다운' — 화가 위로 솟았다가 아래(down)로 내려앉는 그림. 열이 내려가면 진정."
      },
      {
        "n": 23,
        "en": "take care",
        "ko": "조심하다",
        "ipa": "/teɪk ker/",
        "stress": "take CARE",
        "emoji": "🤗⚠️",
        "ex": "Take care when you cross the street.",
        "ex_ko": "길 건널 때 조심해.",
        "mnemonic": "'케어(care, 돌봄)를 챙겨(take) 간다' — 자기를 돌볼 마음을 챙기니 조심하게 돼."
      },
      {
        "n": 24,
        "en": "because of",
        "ko": "… 때문에",
        "ipa": "/bɪˈkɔːz əv/",
        "stress": "be CAUSE of",
        "emoji": "➡️🌧️",
        "ex": "We stayed home because of the rain.",
        "ex_ko": "우리는 비 때문에 집에 있었어.",
        "mnemonic": "because 안에 'cause(원인)'가 들어 있어. '원인이 되는 것' 때문에! 뒤엔 명사가 와."
      }
    ]
  },
  {
    "pack_id": "neungyul-voca-middle-2025-day05",
    "title": "능률VOCA 중등 필수 [2025] DAY 05",
    "source": "프렙업 영어학원 프린트 (PAGE 5/50)",
    "words": [
      {
        "n": 1,
        "en": "repair",
        "ko": "[동] 고치다, 수리하다 / [명] 수리, 보수",
        "ipa": "/rɪˈper/",
        "stress": "re-PAIR",
        "emoji": "🔧🛠️",
        "ex": "My dad will repair my broken bike today.",
        "ex_ko": "아빠가 오늘 내 고장 난 자전거를 고쳐 주실 거야.",
        "mnemonic": "'리페어' — 페어(pair, 짝)를 다시(re) 맞춘다. 망가진 걸 원래 짝처럼 되돌리는 게 수리."
      },
      {
        "n": 2,
        "en": "instant",
        "ko": "[형] 1. 즉각적인, 당장의 2. 즉석의, 인스턴트의 / [명] 순간",
        "ipa": "/ˈɪnstənt/",
        "stress": "IN-stant",
        "emoji": "⚡🍜",
        "ex": "I made instant noodles for a quick snack.",
        "ex_ko": "간단히 먹으려고 인스턴트 라면을 끓였어.",
        "mnemonic": "인스턴트 라면! 3분이면 바로 나오는 즉석. 그래서 '즉각적인, 순간'."
      },
      {
        "n": 3,
        "en": "advise",
        "ko": "[동] 충고하다, 조언하다",
        "ipa": "/ədˈvaɪz/",
        "stress": "ad-VISE",
        "emoji": "💬🧑‍🏫",
        "ex": "My teacher advised me to study every day.",
        "ex_ko": "선생님이 나에게 매일 공부하라고 조언하셨어.",
        "mnemonic": "ad(~에게) + vise(wise, 지혜). 지혜를 건네주는 게 충고·조언이에요."
      },
      {
        "n": 4,
        "en": "totally",
        "ko": "[부] 완전히, 전적으로",
        "ipa": "/ˈtoʊtəli/",
        "stress": "TO-tal-ly",
        "emoji": "💯🙌",
        "ex": "I totally forgot about the math test.",
        "ex_ko": "나 수학 시험을 완전히 까먹었어.",
        "mnemonic": "토탈(total, 전체)에 -ly가 붙어 '전체적으로 = 완전히'. 토탈 합계니까 하나도 안 빼고."
      },
      {
        "n": 5,
        "en": "freezing",
        "ko": "[형] 몹시 추운[차가운]",
        "ipa": "/ˈfriːzɪŋ/",
        "stress": "FREE-zing",
        "emoji": "🥶❄️",
        "ex": "It's freezing outside, so wear your coat.",
        "ex_ko": "밖이 엄청 추우니까 코트 입어.",
        "mnemonic": "'프리징' — 프리저(냉동실) 안처럼 꽁꽁 어는 추위. freeze(얼다)+ing."
      },
      {
        "n": 6,
        "en": "blank",
        "ko": "[형] 공백의, 빈 / [명] 빈칸, 공란",
        "ipa": "/blæŋk/",
        "stress": "BLANK",
        "emoji": "📄⬜",
        "ex": "Please fill in the blank with a word.",
        "ex_ko": "빈칸에 단어를 채워 넣으세요.",
        "mnemonic": "'블랭크' — 시험지 빈칸 보면 머리가 '블랭!' 하고 하얘진다. 그게 공백."
      },
      {
        "n": 7,
        "en": "important",
        "ko": "[형] 중요한",
        "ipa": "/ɪmˈpɔːrtnt/",
        "stress": "im-POR-tant",
        "emoji": "⭐❗",
        "ex": "This test is very important for my grade.",
        "ex_ko": "이 시험은 내 성적에 아주 중요해.",
        "mnemonic": "항구(port)로 안으로(im) 들여오는 물건은 귀한 것. 수입할 만큼 값진 = 중요한."
      },
      {
        "n": 8,
        "en": "teen",
        "ko": "[명] 십 대 / [형] 십 대의",
        "ipa": "/tiːn/",
        "stress": "TEEN",
        "emoji": "🧑‍🎤🎒",
        "ex": "Many teens love listening to K-pop music.",
        "ex_ko": "많은 십 대들이 케이팝 음악 듣는 걸 좋아해.",
        "mnemonic": "thirTEEN(13)부터 nineTEEN(19)까지 뒤에 붙는 -teen. 그 나이대가 바로 십 대."
      },
      {
        "n": 9,
        "en": "weigh",
        "ko": "[동] 1. 무게가 …이다 2. 무게를 재다[달다]",
        "ipa": "/weɪ/",
        "stress": "WEIGH",
        "emoji": "⚖️",
        "ex": "How much does your backpack weigh?",
        "ex_ko": "네 가방 무게가 얼마나 나가?",
        "mnemonic": "\"웨이\" 하고 저울 위에 올리면 무게가 나온다. 헬스장 웨이트(weight)도 같은 뿌리."
      },
      {
        "n": 10,
        "en": "regularly",
        "ko": "[부] 정기적으로, 규칙적으로",
        "ipa": "/ˈreɡjələrli/",
        "stress": "RE-gu-lar-ly",
        "emoji": "📅⏰",
        "ex": "I exercise regularly after school.",
        "ex_ko": "나는 방과 후에 규칙적으로 운동해.",
        "mnemonic": "규칙(rule)을 뜻하는 regular에 -ly가 붙어 '규칙적으로'. 달력에 동그라미 치듯 정기적으로."
      },
      {
        "n": 11,
        "en": "law",
        "ko": "[명] 법, 법률",
        "ipa": "/lɔː/",
        "stress": "LAW",
        "emoji": "⚖️📜",
        "ex": "Everyone must follow the law.",
        "ex_ko": "모두가 법을 지켜야 해.",
        "mnemonic": "\"로\"—법대를 '로스쿨(law school)'이라고 하지. 로스쿨 = 법 배우는 학교."
      },
      {
        "n": 12,
        "en": "rub",
        "ko": "[동] 비비다, 문지르다",
        "ipa": "/rʌb/",
        "stress": "RUB",
        "emoji": "🤲✨",
        "ex": "She rubbed her eyes and yawned.",
        "ex_ko": "그녀는 눈을 비비며 하품했어.",
        "mnemonic": "\"럽\" 하고 손을 문지르면 러브(love) 하트가 나올 것 같다. 램프를 rub하면 지니 등장."
      },
      {
        "n": 13,
        "en": "pour",
        "ko": "[동] 1. 붓다, 따르다 2. (비가) 쏟아지다, 퍼붓다",
        "ipa": "/pɔːr/",
        "stress": "POUR",
        "emoji": "🫗🌧️",
        "ex": "Can you pour me some water?",
        "ex_ko": "물 좀 따라 줄래?",
        "mnemonic": "\"포~\" 하고 물줄기가 쏟아진다. 비가 퍼부을 때도 pour."
      },
      {
        "n": 14,
        "en": "yet",
        "ko": "[부] 1. [부정문] 아직 2. [의문문] 벌써",
        "ipa": "/jet/",
        "stress": "YET",
        "emoji": "⏳❓",
        "ex": "I haven't finished my homework yet.",
        "ex_ko": "나 아직 숙제 다 못 끝냈어.",
        "mnemonic": "\"옛?\"—아직 안 했냐고 물을 때 쓰는 말. 부정문엔 '아직', 의문문엔 '벌써'."
      },
      {
        "n": 15,
        "en": "skill",
        "ko": "[명] 1. 기량, 솜씨 2. 기술",
        "ipa": "/skɪl/",
        "stress": "SKILL",
        "emoji": "🎯🛠️",
        "ex": "Cooking is a useful skill to have.",
        "ex_ko": "요리는 갖고 있으면 유용한 기술이야.",
        "mnemonic": "게임에서 '스킬 쓴다'고 하지. 스킬 = 갈고닦은 솜씨·기술."
      },
      {
        "n": 16,
        "en": "neat",
        "ko": "[형] 정돈된, 단정한",
        "ipa": "/niːt/",
        "stress": "NEAT",
        "emoji": "🧹📚",
        "ex": "Your room looks really neat today.",
        "ex_ko": "네 방 오늘 정말 깔끔해 보인다.",
        "mnemonic": "\"니트\" 스웨터를 곱게 개어 놓은 모습. 반듯하고 단정한 상태가 neat."
      },
      {
        "n": 17,
        "en": "ache",
        "ko": "[동] 아프다, 쑤시다 / [명] 아픔, 통증",
        "ipa": "/eɪk/",
        "stress": "ACHE",
        "emoji": "🤕😣",
        "ex": "My legs ache after playing soccer all day.",
        "ex_ko": "하루 종일 축구하고 나니 다리가 쑤셔요.",
        "mnemonic": "'에이크(에이 크다!)' 하고 아파서 소리치는 모습. 몸이 쑤실 때 나는 신음이에요."
      },
      {
        "n": 18,
        "en": "patient",
        "ko": "[명] 환자 / [형] 인내심[참을성] 있는",
        "ipa": "/ˈpeɪʃənt/",
        "stress": "PA-tient",
        "emoji": "🏥🧑‍⚕️😌",
        "ex": "The doctor is very patient with young patients.",
        "ex_ko": "그 의사 선생님은 어린 환자들에게 아주 인내심이 많아요.",
        "mnemonic": "'페이션트'는 아파도 참는 사람. 참는 사람이 곧 '환자'이자 '참을성 있는' 이에요."
      },
      {
        "n": 19,
        "en": "elderly",
        "ko": "[형] 나이가 지긋한, 연세가 드신",
        "ipa": "/ˈeldərli/",
        "stress": "EL-der-ly",
        "emoji": "👴👵",
        "ex": "An elderly man sat next to me on the bus.",
        "ex_ko": "버스에서 나이 지긋한 할아버지가 제 옆에 앉으셨어요.",
        "mnemonic": "elder(연장자) + ly. '엘더'는 나보다 오래 산 어른, 그래서 연세 드신."
      },
      {
        "n": 20,
        "en": "wipe",
        "ko": "[동] 닦다, 훔치다",
        "ipa": "/waɪp/",
        "stress": "WIPE",
        "emoji": "🧽🧻",
        "ex": "Please wipe the table before we eat.",
        "ex_ko": "밥 먹기 전에 식탁 좀 닦아 줘.",
        "mnemonic": "'와입~' 하고 물티슈로 쓱 닦는 소리. 와이퍼가 유리창 닦는 거 생각하면 돼요."
      },
      {
        "n": 21,
        "en": "punch",
        "ko": "[동] 1. 주먹으로 치다[때리다] 2. 구멍을 뚫다",
        "ipa": "/pʌntʃ/",
        "stress": "PUNCH",
        "emoji": "👊🥊",
        "ex": "He tried to punch the wall in anger.",
        "ex_ko": "그는 화가 나서 벽을 주먹으로 치려고 했어요.",
        "mnemonic": "'펀치!' 주먹으로 퍽 때리기. 펀치로 종이에 구멍 뚫는 것도 같은 단어예요."
      },
      {
        "n": 22,
        "en": "take out",
        "ko": "1. …을 꺼내다 2. …을 데리고 나가다",
        "ipa": "/teɪk aʊt/",
        "stress": "TAKE out",
        "emoji": "🎒📤🐕",
        "ex": "Take out your notebook and write your name.",
        "ex_ko": "공책을 꺼내서 이름을 쓰세요.",
        "mnemonic": "take(가지다) + out(밖으로) = 밖으로 가지고 나오다, 즉 꺼내다."
      },
      {
        "n": 23,
        "en": "get out of",
        "ko": "1. (장소)에서 나가다 2. (차)에서 내리다",
        "ipa": "/ɡet aʊt əv/",
        "stress": "GET out of",
        "emoji": "🚗🚪🚶",
        "ex": "Get out of the car and close the door.",
        "ex_ko": "차에서 내려서 문을 닫아.",
        "mnemonic": "get(움직이다) + out of(~밖으로) = ~에서 빠져나오다, 차에서 내리다."
      },
      {
        "n": 24,
        "en": "plenty of",
        "ko": "많은, 충분한",
        "ipa": "/ˈplenti əv/",
        "stress": "PLEN-ty of",
        "emoji": "🍎🍎🍎",
        "ex": "We have plenty of time before the movie starts.",
        "ex_ko": "영화 시작 전까지 시간이 충분히 많아요.",
        "mnemonic": "'플렌티'는 full(가득)과 뿌리가 같아요. 넘칠 만큼 많고 충분한 것."
      }
    ]
  },
  {
    "pack_id": "neungyul-voca-middle-2025-day06",
    "title": "능률VOCA 중등 필수 [2025] DAY 06",
    "source": "프렙업 영어학원 프린트 (PAGE 6/50)",
    "words": [
      {
        "n": 1,
        "en": "mistake",
        "ko": "[명] 실수, 잘못",
        "ipa": "/mɪˈsteɪk/",
        "stress": "mis-TAKE",
        "emoji": "❌📝",
        "ex": "Sorry, I made a mistake on question five.",
        "ex_ko": "미안해, 나 5번 문제에서 실수했어.",
        "mnemonic": "mis(잘못)+take(잡다) — 잘못 집어 들면 실수! '미스테이크'는 미스(miss)한 것."
      },
      {
        "n": 2,
        "en": "flour",
        "ko": "[명] 밀가루",
        "ipa": "/ˈflaʊər/",
        "stress": "FLOUR",
        "emoji": "🌾🥣",
        "ex": "We need more flour to make the cookies.",
        "ex_ko": "쿠키를 만들려면 밀가루가 더 필요해.",
        "mnemonic": "발음이 flower(꽃)와 똑같아요. '밀가루를 뿌리니 하얀 꽃가루 같다'로 기억!"
      },
      {
        "n": 3,
        "en": "lawyer",
        "ko": "[명] 변호사",
        "ipa": "/ˈlɔɪər/",
        "stress": "LAW-yer",
        "emoji": "⚖️👨‍💼",
        "ex": "My uncle is a lawyer at a big company.",
        "ex_ko": "우리 삼촌은 큰 회사의 변호사야.",
        "mnemonic": "law(법)+er(사람) — 법을 다루는 사람이 변호사예요."
      },
      {
        "n": 4,
        "en": "tire",
        "ko": "[동] 지치다, 지치게 하다 / [명] (자동차 등의) 타이어",
        "ipa": "/ˈtaɪər/",
        "stress": "TIRE",
        "emoji": "🛞😩",
        "ex": "Long walks always tire my little brother.",
        "ex_ko": "오래 걸으면 항상 내 남동생은 지쳐.",
        "mnemonic": "'타이어'가 닳아서 힘 빠지듯, 사람도 tire하면 지쳐요."
      },
      {
        "n": 5,
        "en": "channel",
        "ko": "[명] (TV 등의) 채널",
        "ipa": "/ˈtʃænəl/",
        "stress": "CHAN-nel",
        "emoji": "📺🔢",
        "ex": "Can you change the channel to the news?",
        "ex_ko": "채널을 뉴스로 바꿔 줄래?",
        "mnemonic": "'채널'이라고 그대로 읽어요. TV 채널은 물길처럼 방송이 흘러오는 통로!"
      },
      {
        "n": 6,
        "en": "soldier",
        "ko": "[명] 군인, 병사",
        "ipa": "/ˈsoʊldʒər/",
        "stress": "SOL-dier",
        "emoji": "🪖🎖️",
        "ex": "My grandfather was a soldier for ten years.",
        "ex_ko": "우리 할아버지는 10년 동안 군인이셨어.",
        "mnemonic": "'솔저' — 솔(sol) 하고 총 쏘는 사람. 군인은 나라를 지켜요."
      },
      {
        "n": 7,
        "en": "recipe",
        "ko": "[명] 요리법, 레시피",
        "ipa": "/ˈresəpi/",
        "stress": "RE-ci-pe",
        "emoji": "📖🍳",
        "ex": "This recipe for pancakes is really easy.",
        "ex_ko": "이 팬케이크 요리법은 정말 쉬워.",
        "mnemonic": "'레시피'라고 읽어요. '레서피 → 레시피' 끝을 '파이'로 읽지 않게 조심!"
      },
      {
        "n": 8,
        "en": "wallet",
        "ko": "[명] 지갑",
        "ipa": "/ˈwɑlət/",
        "stress": "WAL-let",
        "emoji": "👛💳",
        "ex": "I left my wallet at home this morning.",
        "ex_ko": "나 오늘 아침에 지갑을 집에 두고 왔어.",
        "mnemonic": "'왈렛' — '왈! 돈이 다 나갔네' 하고 놀라는 지갑으로 기억!"
      },
      {
        "n": 9,
        "en": "silent",
        "ko": "[형] 1. 말이 없는, 침묵하는 2. 조용한, 고요한",
        "ipa": "/ˈsaɪlənt/",
        "stress": "SI-lent",
        "emoji": "🤫🔇",
        "ex": "Everyone was silent during the test.",
        "ex_ko": "시험 보는 동안 모두가 조용했어.",
        "mnemonic": "\"사일런트 모드\" 하면 폰이 소리 안 나죠. 말없이 조용한 상태예요."
      },
      {
        "n": 10,
        "en": "rail",
        "ko": "[명] 1. (철도의) 레일 2. 철도, 기차",
        "ipa": "/reɪl/",
        "stress": "RAIL",
        "emoji": "🛤️🚆",
        "ex": "Don't stand too close to the rail.",
        "ex_ko": "레일에 너무 가까이 서 있지 마.",
        "mnemonic": "\"레일\"은 우리도 그대로 써요. 기차가 달리는 두 줄 철길!"
      },
      {
        "n": 11,
        "en": "adult",
        "ko": "[명] 성인, 어른 / [형] 성인의, 다 자란",
        "ipa": "/əˈdʌlt/",
        "stress": "a-DULT",
        "emoji": "🧑👔",
        "ex": "You can drive when you become an adult.",
        "ex_ko": "어른이 되면 운전할 수 있어.",
        "mnemonic": "\"어덜트\" → \"어른\"! 소리가 비슷해서 바로 외워져요."
      },
      {
        "n": 12,
        "en": "tasty",
        "ko": "[형] 맛있는",
        "ipa": "/ˈteɪsti/",
        "stress": "TAS-ty",
        "emoji": "😋🍕",
        "ex": "This pizza is really tasty!",
        "ex_ko": "이 피자 진짜 맛있다!",
        "mnemonic": "taste(맛) + y = 맛이 있는, 맛있는."
      },
      {
        "n": 13,
        "en": "couple",
        "ko": "[명] 1. 한 쌍, 두 개 2. 부부, 커플",
        "ipa": "/ˈkʌpəl/",
        "stress": "COU-ple",
        "emoji": "👫2️⃣",
        "ex": "I need a couple of minutes to finish.",
        "ex_ko": "끝내려면 몇 분만 더 필요해.",
        "mnemonic": "\"커플\"은 둘이 한 쌍! 그래서 \"두 개, 한 쌍\"이란 뜻이에요."
      },
      {
        "n": 14,
        "en": "especially",
        "ko": "[부] 1. 특히 2. 특별히, 각별히",
        "ipa": "/ɪˈspeʃəli/",
        "stress": "es-PE-cial-ly",
        "emoji": "⭐👉",
        "ex": "I love fruit, especially strawberries.",
        "ex_ko": "난 과일 좋아해, 특히 딸기.",
        "mnemonic": "special(특별한) + ly = 특별하게, 특히."
      },
      {
        "n": 15,
        "en": "soap",
        "ko": "[명] 비누",
        "ipa": "/soʊp/",
        "stress": "SOAP",
        "emoji": "🧼🫧",
        "ex": "Wash your hands with soap and water.",
        "ex_ko": "비누랑 물로 손 씻어.",
        "mnemonic": "\"솝\" 하고 손을 문지르면 거품이 뽀글! 비누예요."
      },
      {
        "n": 16,
        "en": "lonely",
        "ko": "[형] 외로운, 쓸쓸한",
        "ipa": "/ˈloʊnli/",
        "stress": "LONE-ly",
        "emoji": "😢🧍",
        "ex": "I feel lonely when my friends are busy.",
        "ex_ko": "친구들이 바쁘면 난 외로워.",
        "mnemonic": "alone(혼자)에서 온 말. 혼자라서 외로운 거예요."
      },
      {
        "n": 17,
        "en": "mind",
        "ko": "[명] 마음, 정신 / [동] 꺼리다, 싫어하다",
        "ipa": "/maɪnd/",
        "stress": "MIND",
        "emoji": "🧠",
        "ex": "Do you mind if I open the window?",
        "ex_ko": "제가 창문 좀 열어도 될까요?",
        "mnemonic": "'마인드'는 마음·정신. 'Do you mind?'는 '마음에 걸려?' 즉 꺼리냐는 뜻이에요."
      },
      {
        "n": 18,
        "en": "curly",
        "ko": "[형] 곱슬곱슬한",
        "ipa": "/ˈkɜːrli/",
        "stress": "CUR-ly",
        "emoji": "🌀💇",
        "ex": "My sister has long curly brown hair.",
        "ex_ko": "우리 언니는 길고 곱슬곱슬한 갈색 머리야.",
        "mnemonic": "'컬리'—머리 '컬(curl)' 넣는다는 말 그대로! 컬이 들어간 머리가 curly."
      },
      {
        "n": 19,
        "en": "opinion",
        "ko": "[명] 의견, 견해",
        "ipa": "/əˈpɪnjən/",
        "stress": "o-PIN-ion",
        "emoji": "💭🗣️",
        "ex": "In my opinion, the movie was too long.",
        "ex_ko": "내 생각엔 그 영화 너무 길었어.",
        "mnemonic": "'어핀연'—핀(pin)을 콕 꽂듯 자기 생각을 딱 찍어 말하는 게 opinion, 의견."
      },
      {
        "n": 20,
        "en": "blend",
        "ko": "[동] 섞이다, 섞다, 혼합하다",
        "ipa": "/blend/",
        "stress": "BLEND",
        "emoji": "🥤🌀",
        "ex": "Blend the milk and bananas for two minutes.",
        "ex_ko": "우유랑 바나나를 2분 동안 섞어.",
        "mnemonic": "'블렌더(blender)'가 뭐 하는 기계? 섞는 기계! blend가 바로 '섞다'."
      },
      {
        "n": 21,
        "en": "mixture",
        "ko": "[명] 혼합(물)",
        "ipa": "/ˈmɪkstʃər/",
        "stress": "MIX-ture",
        "emoji": "🥣🎨",
        "ex": "This drink is a mixture of juice and soda.",
        "ex_ko": "이 음료는 주스와 탄산음료를 섞은 거야.",
        "mnemonic": "mix(섞다) + -ture(명사 꼬리) = 섞은 것, 혼합물. '믹스처'라고 읽어."
      },
      {
        "n": 22,
        "en": "fill in",
        "ko": "1. (빈칸 등)에 기입하다, 써넣다 2. (구멍 등)을 메우다",
        "ipa": "/ˌfɪl ˈɪn/",
        "stress": "fill IN",
        "emoji": "📝✍️",
        "ex": "Please fill in your name and phone number.",
        "ex_ko": "이름이랑 전화번호를 적어 주세요.",
        "mnemonic": "fill(채우다) + in(안에) = 빈칸 '안을 채우다', 즉 써넣다."
      },
      {
        "n": 23,
        "en": "be different from",
        "ko": "…와 다르다",
        "ipa": "/bi ˈdɪfrənt frəm/",
        "stress": "be DIF-fer-ent from",
        "emoji": "🍎🍊↔️",
        "ex": "My school is different from yours.",
        "ex_ko": "우리 학교는 너희 학교랑 달라.",
        "mnemonic": "different(다른) 뒤엔 무조건 from! '~로부터 떨어져 다르다'로 외우면 to랑 안 헷갈려."
      },
      {
        "n": 24,
        "en": "go away",
        "ko": "1. (사람, 장소를) (떠나)가다 2. 집을 떠나다, 어디를 가다 3. 없어지다",
        "ipa": "/ˌɡoʊ əˈweɪ/",
        "stress": "go a-WAY",
        "emoji": "🚶‍♂️💨",
        "ex": "My headache finally went away last night.",
        "ex_ko": "어젯밤에 두통이 드디어 사라졌어.",
        "mnemonic": "go(가다) + away(멀리) = 멀리 가버리다. 사람이면 '떠나다', 아픔이면 '없어지다'."
      }
    ]
  },
  {
    "pack_id": "neungyul-voca-middle-2025-day07",
    "title": "능률VOCA 중등 필수 [2025] DAY 07",
    "source": "프렙업 영어학원 프린트 (PAGE 7/50)",
    "words": [
      {
        "n": 1,
        "en": "share",
        "ko": "[동] 1. 함께 쓰다, 공유하다 2. 나누다",
        "ipa": "/ʃer/",
        "stress": "SHARE",
        "emoji": "🤝🍕",
        "ex": "Can I share your umbrella on the way home?",
        "ex_ko": "집에 가는 길에 네 우산 같이 써도 될까?",
        "mnemonic": "'셰어하우스'는 여러 명이 집을 함께 쓰는 곳. share = 함께 쓰다."
      },
      {
        "n": 2,
        "en": "form",
        "ko": "[명] 1. 종류, 유형, 형태 2. (문서) 서식 / [동] 형성하다, 이루다",
        "ipa": "/fɔrm/",
        "stress": "FORM",
        "emoji": "📝🧱",
        "ex": "Please fill out this form before the class starts.",
        "ex_ko": "수업 시작 전에 이 서식을 작성해 주세요.",
        "mnemonic": "'폼이 좋다'의 폼! 겉모양·형태를 뜻하고, 종이 서식도 정해진 형태라서 form."
      },
      {
        "n": 3,
        "en": "invention",
        "ko": "[명] 발명(품)",
        "ipa": "/ɪnˈvenʃən/",
        "stress": "in-VEN-tion",
        "emoji": "💡🔧",
        "ex": "The phone is one of the greatest inventions ever.",
        "ex_ko": "전화기는 역사상 가장 위대한 발명품 중 하나야.",
        "mnemonic": "invent(발명하다) + -tion(명사) = 발명품. '인벤토리'에 새로 만든 물건이 쌓인다고 생각해요."
      },
      {
        "n": 4,
        "en": "blind",
        "ko": "[형] 1. 눈 먼, 맹인의 2. 깨닫지[알아차리지] 못하는",
        "ipa": "/blaɪnd/",
        "stress": "BLIND",
        "emoji": "🙈🕶️",
        "ex": "My grandfather went blind in his left eye.",
        "ex_ko": "우리 할아버지는 왼쪽 눈이 안 보이게 되셨어.",
        "mnemonic": "창문 '블라인드'를 내리면 아무것도 안 보이죠. blind = 눈 먼."
      },
      {
        "n": 5,
        "en": "actual",
        "ko": "[형] 실제의, 사실의",
        "ipa": "/ˈæktʃuəl/",
        "stress": "AC-tu-al",
        "emoji": "✅🔍",
        "ex": "The actual price was higher than I expected.",
        "ex_ko": "실제 가격은 내가 생각한 것보다 비쌌어.",
        "mnemonic": "'액션(act)'은 진짜로 일어난 행동. 그래서 actual은 '실제의'."
      },
      {
        "n": 6,
        "en": "culture",
        "ko": "[명] 문화",
        "ipa": "/ˈkʌltʃər/",
        "stress": "CUL-ture",
        "emoji": "🌏🎎",
        "ex": "Korean culture is popular around the world now.",
        "ex_ko": "요즘 한국 문화는 전 세계에서 인기가 많아.",
        "mnemonic": "'컬처 쇼크'라는 말 그대로 문화. 밭을 갈아 키우듯 사람들이 가꿔온 것이 문화예요."
      },
      {
        "n": 7,
        "en": "lost",
        "ko": "[형] 1. 길을 잃은 2. 잃어버린, 분실된",
        "ipa": "/lɔst/",
        "stress": "LOST",
        "emoji": "🧭😵",
        "ex": "We got lost on the way to the museum.",
        "ex_ko": "우리는 박물관 가는 길에 길을 잃었어.",
        "mnemonic": "lose(잃다)의 과거분사가 lost. 게임에서 지면 뜨는 'LOST' 화면을 떠올려요."
      },
      {
        "n": 8,
        "en": "natural",
        "ko": "[형] 1. 자연의 2. 당연한, 자연스러운 3. 타고난, 선천적인",
        "ipa": "/ˈnætʃərəl/",
        "stress": "NA-tu-ral",
        "emoji": "🌿☀️",
        "ex": "This juice has no sugar, only natural flavor.",
        "ex_ko": "이 주스는 설탕 없이 자연 그대로의 맛만 나.",
        "mnemonic": "nature(자연) + -al(형용사) = 자연의. '내추럴한 화장'은 꾸미지 않은 자연스러운 것."
      },
      {
        "n": 9,
        "en": "breath",
        "ko": "[명] 숨, 호흡",
        "ipa": "/brɛθ/",
        "stress": "BREATH",
        "emoji": "😮‍💨🫁",
        "ex": "Take a deep breath before you start.",
        "ex_ko": "시작하기 전에 숨을 깊게 들이쉬어.",
        "mnemonic": "'브레스'—숨을 '후' 불면 브레스가 나와요. breathe(숨쉬다)의 명사형이 breath(숨)."
      },
      {
        "n": 10,
        "en": "excite",
        "ko": "[동] 흥분시키다, 들뜨게 하다",
        "ipa": "/ɪkˈsaɪt/",
        "stress": "ex-CITE",
        "emoji": "🤩🎉",
        "ex": "The new game really excites my little brother.",
        "ex_ko": "그 새 게임은 내 남동생을 정말 들뜨게 해.",
        "mnemonic": "'익사이트'—너무 신나서 '익! 사이다!' 하고 소리치는 장면을 떠올려요."
      },
      {
        "n": 11,
        "en": "garbage",
        "ko": "[명] 쓰레기",
        "ipa": "/ˈɡɑːrbɪdʒ/",
        "stress": "GAR-bage",
        "emoji": "🗑️🍌",
        "ex": "Please take the garbage out tonight.",
        "ex_ko": "오늘 밤에 쓰레기 좀 내다 버려 줘.",
        "mnemonic": "'가비지'—쓰레기 봉투를 '가방'에 담아 버린다고 기억해요."
      },
      {
        "n": 12,
        "en": "suck",
        "ko": "[동] 1. 빨아 마시다[먹다] 2. 빨다",
        "ipa": "/sʌk/",
        "stress": "SUCK",
        "emoji": "🥤😮",
        "ex": "The baby sucks milk from the bottle.",
        "ex_ko": "아기가 젖병에서 우유를 빨아 마셔.",
        "mnemonic": "'석'—빨대로 '쓱' 빨아 마시는 소리. 쓱쓱 빨아들이면 suck."
      },
      {
        "n": 13,
        "en": "prison",
        "ko": "[명] 교도소, 감옥",
        "ipa": "/ˈprɪzən/",
        "stress": "PRI-son",
        "emoji": "🏢⛓️",
        "ex": "The thief spent five years in prison.",
        "ex_ko": "그 도둑은 감옥에서 5년을 보냈어.",
        "mnemonic": "'프리즌'—free(자유)가 없는 zone(구역)! 자유 없는 곳이 감옥이에요."
      },
      {
        "n": 14,
        "en": "flow",
        "ko": "[동] 흐르다 / [명] 흐름",
        "ipa": "/floʊ/",
        "stress": "FLOW",
        "emoji": "🌊➡️",
        "ex": "The river flows into the sea.",
        "ex_ko": "그 강은 바다로 흘러 들어가.",
        "mnemonic": "'플로우'—물이 '플~' 하고 부드럽게 흘러가는 소리로 기억해요."
      },
      {
        "n": 15,
        "en": "solar",
        "ko": "[형] 1. 태양의, 태양에 관한 2. 태양열의",
        "ipa": "/ˈsoʊlər/",
        "stress": "SO-lar",
        "emoji": "☀️🔋",
        "ex": "Our school uses solar power for electricity.",
        "ex_ko": "우리 학교는 전기를 태양열로 만들어 써.",
        "mnemonic": "'솔라'—라틴어 sol이 '태양'. 솔라시도의 '솔'을 태양이라고 외워요."
      },
      {
        "n": 16,
        "en": "captain",
        "ko": "[명] 1. 선장, 기장 2. (팀의) 주장",
        "ipa": "/ˈkæptən/",
        "stress": "CAP-tain",
        "emoji": "🧢⚓",
        "ex": "Our team captain gave us a short speech.",
        "ex_ko": "우리 팀 주장이 우리에게 짧게 연설했어.",
        "mnemonic": "'캡틴'—모자(cap) 쓴 사람이 배의 선장이자 팀 주장이에요."
      },
      {
        "n": 17,
        "en": "dialogue",
        "ko": "[명] (소설, 영화 등의) 대화, 회화",
        "ipa": "/ˈdaɪəlɔːɡ/",
        "stress": "DI-a-logue",
        "emoji": "💬🗣️",
        "ex": "The movie had funny dialogue between two friends.",
        "ex_ko": "그 영화는 두 친구 사이의 웃긴 대화가 있었어.",
        "mnemonic": "'다이얼로그' — 전화 다이얼(dial) 돌려서 주고받는 말이 대화예요."
      },
      {
        "n": 18,
        "en": "fail",
        "ko": "[동] 1. 실패하다 2. (시험에) 떨어지다",
        "ipa": "/feɪl/",
        "stress": "FAIL",
        "emoji": "❌📉",
        "ex": "I studied hard so I didn't fail the test.",
        "ex_ko": "열심히 공부해서 시험에 떨어지지 않았어.",
        "mnemonic": "'페일' — 페인트가 벽에서 다 벗겨지듯 실패했다고 외워요."
      },
      {
        "n": 19,
        "en": "purse",
        "ko": "[명] (여성용) 지갑, 핸드백",
        "ipa": "/pɜːrs/",
        "stress": "PURSE",
        "emoji": "👛💰",
        "ex": "My mom keeps her cards in her purse.",
        "ex_ko": "엄마는 카드를 지갑에 넣어 두셔.",
        "mnemonic": "'퍼스' — 지갑을 확 퍼서 돈을 꺼낸다고 기억해요."
      },
      {
        "n": 20,
        "en": "mate",
        "ko": "[명] 1. 친구, 동료 2. (한 쌍을 이루는 동물의) 짝",
        "ipa": "/meɪt/",
        "stress": "MATE",
        "emoji": "🤝👬",
        "ex": "He is my best mate at school.",
        "ex_ko": "걔는 학교에서 내 제일 친한 친구야.",
        "mnemonic": "'메이트' — 룸메이트, 팀메이트처럼 짝이 되는 친구예요."
      },
      {
        "n": 21,
        "en": "villa",
        "ko": "[명] (휴가용) 주택, 별장, 저택",
        "ipa": "/ˈvɪlə/",
        "stress": "VIL-la",
        "emoji": "🏡🌴",
        "ex": "We stayed in a villa near the beach.",
        "ex_ko": "우리는 해변 근처 별장에서 머물렀어.",
        "mnemonic": "'빌라' — 우리가 아는 빌라보다 훨씬 좋은 휴가용 별장이에요."
      },
      {
        "n": 22,
        "en": "pick up",
        "ko": "1. …을 집어 들다 2. …을 (차에) 태우러 가다[오다]",
        "ipa": "/ˈpɪk ʌp/",
        "stress": "PICK up",
        "emoji": "🤏🚗",
        "ex": "My dad will pick me up after school.",
        "ex_ko": "아빠가 학교 끝나고 나를 데리러 오실 거야.",
        "mnemonic": "pick(집다) + up(위로) — 위로 집어 올리다, 사람도 차에 태워 올려요."
      },
      {
        "n": 23,
        "en": "help out",
        "ko": "도와주다",
        "ipa": "/ˈhelp aʊt/",
        "stress": "HELP out",
        "emoji": "🙌🤲",
        "ex": "I help out my mom in the kitchen.",
        "ex_ko": "나는 부엌에서 엄마를 도와드려.",
        "mnemonic": "help(돕다) + out(밖으로) — 힘든 상황 밖으로 꺼내 주는 게 도와주는 거예요."
      },
      {
        "n": 24,
        "en": "thanks to",
        "ko": "…의 덕분에, … 때문에",
        "ipa": "/ˈθæŋks tuː/",
        "stress": "THANKS to",
        "emoji": "🙏✨",
        "ex": "Thanks to my friend, I passed the exam.",
        "ex_ko": "친구 덕분에 나는 시험에 합격했어.",
        "mnemonic": "'~에게 감사(thanks)를 준다' — 그 사람 덕분이라는 뜻이에요."
      }
    ]
  },
  {
    "pack_id": "neungyul-voca-middle-2025-day08",
    "title": "능률VOCA 중등 필수 [2025] DAY 08",
    "source": "프렙업 영어학원 프린트 (PAGE 8/50)",
    "words": [
      {
        "n": 1,
        "en": "tear",
        "ko": "[명] 눈물 / [동] 찢다, 찢어지다",
        "ipa": "/tɪr/",
        "stress": "TEAR",
        "emoji": "😢💧",
        "ex": "A tear rolled down her cheek slowly.",
        "ex_ko": "눈물 한 방울이 그녀의 뺨을 타고 천천히 흘렀다.",
        "mnemonic": "티어 나게 울면 눈물! 찢을 때는 '테어' 하고 종이가 찢어지는 소리."
      },
      {
        "n": 2,
        "en": "gallery",
        "ko": "[명] 미술관",
        "ipa": "/ˈɡæləri/",
        "stress": "GAL-ler-y",
        "emoji": "🖼️🏛️",
        "ex": "We visited an art gallery on Sunday.",
        "ex_ko": "우리는 일요일에 미술관에 갔다.",
        "mnemonic": "'갤러리'는 우리도 그대로 쓰죠. 그림 걸어놓고 구경하는 곳!"
      },
      {
        "n": 3,
        "en": "result",
        "ko": "[명] 결과 / [동] (…의 결과로) 발생하다, 생기다",
        "ipa": "/rɪˈzʌlt/",
        "stress": "re-SULT",
        "emoji": "📊✅",
        "ex": "I'm nervous about my test results today.",
        "ex_ko": "오늘 시험 결과 때문에 긴장돼.",
        "mnemonic": "'리설트' — 게임 끝나면 뜨는 RESULT 화면. 다 끝난 뒤 나오는 게 결과."
      },
      {
        "n": 4,
        "en": "upstairs",
        "ko": "[부] 위층에[으로] / [명] 위층",
        "ipa": "/ˌʌpˈsterz/",
        "stress": "up-STAIRS",
        "emoji": "🪜⬆️🏠",
        "ex": "My room is upstairs next to the bathroom.",
        "ex_ko": "내 방은 위층 화장실 옆에 있어.",
        "mnemonic": "up(위로) + stairs(계단) = 계단 위로, 즉 위층!"
      },
      {
        "n": 5,
        "en": "living",
        "ko": "[형] 살아 있는 / [명] 생활비, 생계 수단",
        "ipa": "/ˈlɪvɪŋ/",
        "stress": "LIV-ing",
        "emoji": "🌱💰",
        "ex": "My uncle makes a living by fixing cars.",
        "ex_ko": "우리 삼촌은 자동차를 고쳐서 생계를 유지하신다.",
        "mnemonic": "live(살다)+ing → 살아 있는. 살려면 돈이 필요하니 '생계'도 됨."
      },
      {
        "n": 6,
        "en": "report",
        "ko": "[명] 보고(서) / [동] 1. 보고하다, 발표하다 2. 보도하다",
        "ipa": "/rɪˈpɔrt/",
        "stress": "re-PORT",
        "emoji": "📝📢",
        "ex": "I have to write a book report tonight.",
        "ex_ko": "나 오늘 밤에 독후감 써야 해.",
        "mnemonic": "'리포트' 그대로 쓰죠! 조사한 걸 다시(re) 날라다(port) 알리는 것."
      },
      {
        "n": 7,
        "en": "produce",
        "ko": "[동] 1. (곡물 등을) 생산하다 2. (상품 등을) 제조[생산]하다",
        "ipa": "/prəˈdus/",
        "stress": "pro-DUCE",
        "emoji": "🏭🌾",
        "ex": "This factory produces about a thousand phones daily.",
        "ex_ko": "이 공장은 하루에 약 천 대의 휴대폰을 생산한다.",
        "mnemonic": "'프로듀서'가 뭘 하죠? 노래·방송을 만들어내는 사람. produce는 만들어내다!"
      },
      {
        "n": 8,
        "en": "excited",
        "ko": "[형] 신이 난, 흥분한",
        "ipa": "/ɪkˈsaɪtɪd/",
        "stress": "ex-CI-ted",
        "emoji": "🤩🎉",
        "ex": "I'm so excited about the school trip tomorrow.",
        "ex_ko": "나 내일 수학여행 때문에 너무 신나.",
        "mnemonic": "'익사이팅'한 순간! 심장이 '싸이(cite)~' 하고 뛰며 신나는 상태."
      },
      {
        "n": 9,
        "en": "gather",
        "ko": "[동] 1. (사람들이) 모이다, (물건 등을) 모으다 2. (정보 등을) 수집하다",
        "ipa": "/ˈɡæðər/",
        "stress": "GA-ther",
        "emoji": "👥🧺",
        "ex": "Let's gather in the gym after lunch.",
        "ex_ko": "점심 먹고 체육관에 모이자.",
        "mnemonic": "\"개더\" 개들이 더 모인다! 사람도 물건도 한곳에 모으는 거예요."
      },
      {
        "n": 10,
        "en": "cause",
        "ko": "[명] 원인 / [동] 일으키다, …의 원인이 되다",
        "ipa": "/kɔːz/",
        "stress": "CAUSE",
        "emoji": "🔥➡️💨",
        "ex": "The heavy rain caused a big accident.",
        "ex_ko": "폭우가 큰 사고를 일으켰어.",
        "mnemonic": "'코즈'는 because 안에 들어 있는 cause! 결과를 일으키는 원인이에요."
      },
      {
        "n": 11,
        "en": "interested",
        "ko": "[형] 흥미 있는, 관심 있는",
        "ipa": "/ˈɪntrəstɪd/",
        "stress": "IN-ter-est-ed",
        "emoji": "🤩👀",
        "ex": "I'm really interested in K-pop dance.",
        "ex_ko": "난 케이팝 댄스에 정말 관심이 많아.",
        "mnemonic": "interest(관심)에 -ed가 붙어 \"관심이 생긴 상태\". 사람이 흥미를 느낄 땐 -ed예요."
      },
      {
        "n": 12,
        "en": "actually",
        "ko": "[부] 실제로, 정말로",
        "ipa": "/ˈæktʃuəli/",
        "stress": "AC-tu-al-ly",
        "emoji": "💡✅",
        "ex": "Actually, I already finished my homework.",
        "ex_ko": "사실 나 숙제 벌써 다 했어.",
        "mnemonic": "act(행동)+ually — 말이 아니라 실제 행동으로 그렇다는 뜻, \"사실은\"."
      },
      {
        "n": 13,
        "en": "talent",
        "ko": "[명] (타고난) 재능, 재주",
        "ipa": "/ˈtælənt/",
        "stress": "TA-lent",
        "emoji": "🎤🌟",
        "ex": "She has a real talent for singing.",
        "ex_ko": "걔는 노래에 진짜 재능이 있어.",
        "mnemonic": "\"탤런트\"는 연기 재능을 타고난 사람이죠. 타고난 재능이 talent예요."
      },
      {
        "n": 14,
        "en": "greet",
        "ko": "[동] 맞이하다, 환영하다",
        "ipa": "/ɡriːt/",
        "stress": "GREET",
        "emoji": "🙋👋",
        "ex": "My dog greets me at the door.",
        "ex_ko": "우리 개가 문 앞에서 날 반겨줘.",
        "mnemonic": "\"그리트\" 그리웠던 사람을 만나 반갑게 맞이한다!"
      },
      {
        "n": 15,
        "en": "lane",
        "ko": "[명] 1. 좁은 길, 도로 2. 차선 3. (육상, 수영 대회 등의) 레인",
        "ipa": "/leɪn/",
        "stress": "LANE",
        "emoji": "🛣️🏊",
        "ex": "The car moved into the fast lane.",
        "ex_ko": "그 차가 추월 차선으로 옮겨 갔어.",
        "mnemonic": "\"레인\" 수영장 레인처럼 길게 나뉜 좁은 길·차선이에요."
      },
      {
        "n": 16,
        "en": "stress",
        "ko": "[명] 1. 스트레스, 압박 2. 강조 / [동] 강조하다",
        "ipa": "/stres/",
        "stress": "STRESS",
        "emoji": "😩📌",
        "ex": "Exams give me a lot of stress.",
        "ex_ko": "시험은 나에게 스트레스를 많이 줘.",
        "mnemonic": "\"스트레스\" 그대로! 꾹 누르는 압박, 말할 때 꾹 눌러 강조하기도 해요."
      },
      {
        "n": 17,
        "en": "later",
        "ko": "[부] 후에, 나중에 / [형] 더 늦은, 더 나중의",
        "ipa": "/ˈleɪtər/",
        "stress": "LA-ter",
        "emoji": "⏰➡️",
        "ex": "I'll call you later tonight, okay?",
        "ex_ko": "오늘 밤 이따가 전화할게, 알았지?",
        "mnemonic": "late(늦은)에 -er이 붙어 '더 늦게', 즉 '나중에'가 돼요."
      },
      {
        "n": 18,
        "en": "create",
        "ko": "[동] 창조하다, 만들다",
        "ipa": "/kriˈeɪt/",
        "stress": "cre-ATE",
        "emoji": "🎨✨",
        "ex": "Let's create a new game together this weekend.",
        "ex_ko": "이번 주말에 같이 새 게임을 만들어 보자.",
        "mnemonic": "'크리에이터'는 영상을 만드는 사람이죠. create = 만들다, 창조하다."
      },
      {
        "n": 19,
        "en": "flat",
        "ko": "[형] 1. 평평한 2. (타이어 등이) 바람이 빠진, 펑크가 난",
        "ipa": "/flæt/",
        "stress": "FLAT",
        "emoji": "🛣️🛞",
        "ex": "My bike tire is flat again today.",
        "ex_ko": "내 자전거 타이어가 오늘 또 펑크 났어.",
        "mnemonic": "'플랫 슈즈'는 굽 없이 평평한 신발! 바람 빠져 납작해진 타이어도 flat."
      },
      {
        "n": 20,
        "en": "beat",
        "ko": "[동] 1. 때리다, 두드리다 2. 이기다",
        "ipa": "/biːt/",
        "stress": "BEAT",
        "emoji": "🥁🏆",
        "ex": "We beat their team by three points.",
        "ex_ko": "우리가 그 팀을 3점 차로 이겼어.",
        "mnemonic": "노래 '비트'는 북을 두드리는 소리! 두드리다 → 상대를 눌러 이기다."
      },
      {
        "n": 21,
        "en": "plus",
        "ko": "[전] 1. 더하기 2. 게다가, … 뿐만 아니라",
        "ipa": "/plʌs/",
        "stress": "PLUS",
        "emoji": "➕😀",
        "ex": "Two plus three is five, plus it's easy.",
        "ex_ko": "2 더하기 3은 5고, 게다가 쉬워.",
        "mnemonic": "'플러스' 기호 그대로 더하기. 문장 앞에 쓰면 '게다가'라는 뜻이에요."
      },
      {
        "n": 22,
        "en": "make noise",
        "ko": "소란을 피우다, 떠들다",
        "ipa": "/meɪk nɔɪz/",
        "stress": "make NOISE",
        "emoji": "📢🙉",
        "ex": "Please don't make noise during the movie.",
        "ex_ko": "영화 보는 동안 떠들지 말아 줘.",
        "mnemonic": "noise(소음)를 make(만들다) → 소음을 만들다 = 떠들다."
      },
      {
        "n": 23,
        "en": "hand in hand",
        "ko": "서로 손을 잡고",
        "ipa": "/hænd ɪn hænd/",
        "stress": "HAND in hand",
        "emoji": "🤝👫",
        "ex": "They walked hand in hand along the beach.",
        "ex_ko": "그들은 해변을 따라 손을 잡고 걸었다.",
        "mnemonic": "손(hand) 안에(in) 손(hand) — 서로 손을 맞잡은 그림 그대로예요."
      },
      {
        "n": 24,
        "en": "take care of",
        "ko": "…을 돌보다",
        "ipa": "/teɪk kɛr ʌv/",
        "stress": "take CARE of",
        "emoji": "🧸👶",
        "ex": "Can you take care of my dog tomorrow?",
        "ex_ko": "내일 우리 강아지 좀 돌봐 줄 수 있어?",
        "mnemonic": "care(돌봄)를 take(맡다) → 누군가를 맡아 돌보다."
      }
    ]
  },
  {
    "pack_id": "neungyul-voca-middle-2025-day09",
    "title": "능률VOCA 중등 필수 [2025] DAY 09",
    "source": "프렙업 영어학원 프린트 (PAGE 9/50)",
    "words": [
      {
        "n": 1,
        "en": "member",
        "ko": "[명] 회원, 일원",
        "ipa": "/ˈmembər/",
        "stress": "MEM-ber",
        "emoji": "👥🎫",
        "ex": "She is a member of our school band.",
        "ex_ko": "그녀는 우리 학교 밴드의 회원이야.",
        "mnemonic": "'멤버'는 이미 우리말로 쓰죠. 동아리 멤버 = 그 모임의 회원, 일원."
      },
      {
        "n": 2,
        "en": "serious",
        "ko": "[형] 1. (상태, 정도가) 심각한 2. 진지한",
        "ipa": "/ˈsɪriəs/",
        "stress": "SE-ri-ous",
        "emoji": "😐🚨",
        "ex": "Don't laugh, this is a serious problem.",
        "ex_ko": "웃지 마, 이건 심각한 문제야.",
        "mnemonic": "'시리어스'한 얼굴 = 웃음기 없이 굳은 표정. 심각하고 진지한 상태예요."
      },
      {
        "n": 3,
        "en": "afraid",
        "ko": "[형] 1. 두려워하는 2. 걱정하는",
        "ipa": "/əˈfreɪd/",
        "stress": "a-FRAID",
        "emoji": "😨🕷️",
        "ex": "I'm afraid of spiders in the bathroom.",
        "ex_ko": "난 욕실에 있는 거미가 무서워.",
        "mnemonic": "a + fraid(fright, 공포). 공포에 빠진 상태라서 두려워하는 거예요."
      },
      {
        "n": 4,
        "en": "dessert",
        "ko": "[명] 디저트, 후식",
        "ipa": "/dɪˈzɜːrt/",
        "stress": "de-SSERT",
        "emoji": "🍰🍨",
        "ex": "What's for dessert after dinner tonight?",
        "ex_ko": "오늘 저녁 먹고 디저트는 뭐야?",
        "mnemonic": "s가 두 개인 건 디저트는 한 번 더(second) 먹고 싶으니까! 사막(desert)은 s 하나."
      },
      {
        "n": 5,
        "en": "toothache",
        "ko": "[명] 치통",
        "ipa": "/ˈtuːθeɪk/",
        "stress": "TOOTH-ache",
        "emoji": "🦷😖",
        "ex": "I have a toothache, so I can't eat.",
        "ex_ko": "나 이가 아파서 못 먹겠어.",
        "mnemonic": "tooth(이) + ache(아픔) = 치통. ache는 '에이크', 아파서 '에잇!' 소리."
      },
      {
        "n": 6,
        "en": "effect",
        "ko": "[명] 1. 영향 2. 결과",
        "ipa": "/ɪˈfekt/",
        "stress": "e-FFECT",
        "emoji": "🎬✨",
        "ex": "The movie's special effects were really cool.",
        "ex_ko": "그 영화의 특수 효과 정말 멋있었어.",
        "mnemonic": "게임·영화의 '이펙트(효과)' 그대로예요. 원인 뒤에 따라오는 결과·영향."
      },
      {
        "n": 7,
        "en": "skillful",
        "ko": "[형] 숙련된, 능숙한",
        "ipa": "/ˈskɪlfl/",
        "stress": "SKILL-ful",
        "emoji": "🎯🛠️",
        "ex": "He is a skillful player on our team.",
        "ex_ko": "그는 우리 팀에서 능숙한 선수야.",
        "mnemonic": "skill(기술) + full(가득) = 기술이 가득한, 즉 능숙한."
      },
      {
        "n": 8,
        "en": "silence",
        "ko": "[명] 1. 고요, 정적 2. 침묵",
        "ipa": "/ˈsaɪləns/",
        "stress": "SI-lence",
        "emoji": "🤫🔇",
        "ex": "There was a long silence in the classroom.",
        "ex_ko": "교실에 긴 침묵이 흘렀어.",
        "mnemonic": "'사일런스'—폰의 사일런트 모드처럼 소리가 꺼진 상태, 고요·침묵."
      },
      {
        "n": 9,
        "en": "stomach",
        "ko": "[명] [소화기관] 위, 배",
        "ipa": "/ˈstʌmək/",
        "stress": "STOM-ach",
        "emoji": "🫃🍽️",
        "ex": "My stomach hurts after eating too much pizza.",
        "ex_ko": "피자를 너무 많이 먹었더니 배가 아파.",
        "mnemonic": "\"스터먹\" — 스트레스 받으면 먹고, 그게 다 위로 간다고 기억하세요."
      },
      {
        "n": 10,
        "en": "print",
        "ko": "[동] 1. 인쇄[출력]하다 2. 출판[발행]하다",
        "ipa": "/prɪnt/",
        "stress": "PRINT",
        "emoji": "🖨️📄",
        "ex": "Can you print this page for me, please?",
        "ex_ko": "이 페이지 좀 출력해 줄래?",
        "mnemonic": "프린터가 종이를 뽑아내는 그 동작이 바로 print입니다."
      },
      {
        "n": 11,
        "en": "safely",
        "ko": "[부] 안전하게, 무사히",
        "ipa": "/ˈseɪfli/",
        "stress": "SAFE-ly",
        "emoji": "🦺✅",
        "ex": "We arrived home safely before the storm started.",
        "ex_ko": "우리는 폭풍이 오기 전에 무사히 집에 도착했어.",
        "mnemonic": "safe(안전한) + ly(하게) = 안전하게. 금고(safe)처럼 무사히요."
      },
      {
        "n": 12,
        "en": "importance",
        "ko": "[명] 중요성",
        "ipa": "/ɪmˈpɔːrtəns/",
        "stress": "im-POR-tance",
        "emoji": "⭐❗",
        "ex": "My teacher talked about the importance of sleep.",
        "ex_ko": "선생님이 잠의 중요성에 대해 말씀하셨어.",
        "mnemonic": "important(중요한)에 -ance 붙여 명사로. \"임포턴스\" = 중요함."
      },
      {
        "n": 13,
        "en": "review",
        "ko": "[동] 1. 검토하다 2. 평론[비평]하다 3. 복습하다 / [명] 1. 검토 2. 평론[비평] 3. 복습",
        "ipa": "/rɪˈvjuː/",
        "stress": "re-VIEW",
        "emoji": "🔁👀📝",
        "ex": "I need to review my notes before the test.",
        "ex_ko": "시험 전에 필기를 복습해야 해.",
        "mnemonic": "re(다시) + view(보다) = 다시 보다 → 복습, 검토."
      },
      {
        "n": 14,
        "en": "strange",
        "ko": "[형] 1. 이상한 2. 낯선",
        "ipa": "/streɪndʒ/",
        "stress": "STRANGE",
        "emoji": "🤨👽",
        "ex": "That's a strange noise coming from upstairs.",
        "ex_ko": "위층에서 이상한 소리가 나는데.",
        "mnemonic": "\"스트레인지\" — 스트레스 받게 낯설고 이상한 느낌으로 외우세요."
      },
      {
        "n": 15,
        "en": "burn",
        "ko": "[동] (불에) 타다, 태우다",
        "ipa": "/bɜːrn/",
        "stress": "BURN",
        "emoji": "🔥",
        "ex": "Be careful, don't burn your hand on the pan!",
        "ex_ko": "조심해, 팬에 손 데지 마!",
        "mnemonic": "\"번!\" 하고 불이 번지는 소리 — 타다, 태우다."
      },
      {
        "n": 16,
        "en": "talented",
        "ko": "[형] 재능 있는, 유능한",
        "ipa": "/ˈtæləntɪd/",
        "stress": "TAL-ent-ed",
        "emoji": "🎤🌟",
        "ex": "She is a talented singer in our school band.",
        "ex_ko": "그 애는 우리 학교 밴드의 재능 있는 가수야.",
        "mnemonic": "탤런트(talent)는 재능 있는 사람. 거기에 -ed 붙여 \"재능 있는\"."
      },
      {
        "n": 17,
        "en": "bare",
        "ko": "[형] 벌거벗은, 살을 드러낸",
        "ipa": "/ber/",
        "stress": "BARE",
        "emoji": "🦶🌳",
        "ex": "Don't walk on the hot sand with bare feet.",
        "ex_ko": "뜨거운 모래 위를 맨발로 걷지 마.",
        "mnemonic": "곰(bear)이 털 없이 '베어'진 모습 — 벌거벗은 상태. 소리는 곰과 똑같아요."
      },
      {
        "n": 18,
        "en": "housework",
        "ko": "[명] 집안일, 가사",
        "ipa": "/ˈhaʊsˌwɜːrk/",
        "stress": "HOUSE-work",
        "emoji": "🧹🧺🏠",
        "ex": "I have to do the housework before dinner.",
        "ex_ko": "나 저녁 먹기 전에 집안일 해야 해.",
        "mnemonic": "house(집) + work(일) = 집안일. 숙제는 homework, 집안일은 housework!"
      },
      {
        "n": 19,
        "en": "however",
        "ko": "[부] 그러나, 그렇지만",
        "ipa": "/haʊˈevər/",
        "stress": "how-EV-er",
        "emoji": "🔄🤔",
        "ex": "I studied hard. However, I failed the test.",
        "ex_ko": "나 열심히 공부했어. 그러나 시험을 망쳤어.",
        "mnemonic": "how(어떻게) + ever(도대체) — '아무리 그래도'가 '그러나'로. 앞말을 뒤집는 신호."
      },
      {
        "n": 20,
        "en": "accept",
        "ko": "[동] 받아들이다, 수락하다",
        "ipa": "/əkˈsept/",
        "stress": "ac-CEPT",
        "emoji": "🤝🎁✅",
        "ex": "She decided to accept his apology.",
        "ex_ko": "그녀는 그의 사과를 받아들이기로 했어.",
        "mnemonic": "ac(~에게) + cept(잡다). 내미는 걸 손으로 잡아 받아들이는 장면이에요."
      },
      {
        "n": 21,
        "en": "mark",
        "ko": "[명] 1. 자국, 얼룩 2. 표시 / [동] 표시하다",
        "ipa": "/mɑːrk/",
        "stress": "MARK",
        "emoji": "🖊️🔵",
        "ex": "There's a dirty mark on your white shirt.",
        "ex_ko": "네 흰 셔츠에 더러운 얼룩이 있어.",
        "mnemonic": "매직으로 '마크' 찍기 — 찍으면 표시, 남으면 자국. 마크 표시가 곧 얼룩."
      },
      {
        "n": 22,
        "en": "not ... anymore",
        "ko": "더 이상 … 않다",
        "ipa": "/nɑːt ˌeniˈmɔːr/",
        "stress": "NOT ... an-y-MORE",
        "emoji": "🚫⏹️",
        "ex": "I don't play that game anymore.",
        "ex_ko": "나 그 게임 더 이상 안 해.",
        "mnemonic": "not(안) + any more(더) = '더는 안'. 문장 맨 끝에 붙여서 '이제 끝!'을 표시해요."
      },
      {
        "n": 23,
        "en": "pass through",
        "ko": "지나가다, 통과하다",
        "ipa": "/pæs θruː/",
        "stress": "PASS through",
        "emoji": "🚶🚪➡️",
        "ex": "The train passes through our town every hour.",
        "ex_ko": "그 기차는 한 시간마다 우리 마을을 지나가.",
        "mnemonic": "pass(지나가다) + through(관통) = 뚫고 지나가다. 터널을 통과하는 기차를 떠올려요."
      },
      {
        "n": 24,
        "en": "in fact",
        "ko": "사실은",
        "ipa": "/ɪn fækt/",
        "stress": "in FACT",
        "emoji": "💡🗣️",
        "ex": "He looks young. In fact, he's forty.",
        "ex_ko": "그는 어려 보여. 사실은 마흔이야.",
        "mnemonic": "fact(사실) 안으로 들어가면 '사실은'. 겉모습 말한 뒤 진짜를 밝힐 때 써요."
      }
    ]
  },
  {
    "pack_id": "neungyul-voca-middle-2025-day10",
    "title": "능률VOCA 중등 필수 [2025] DAY 10",
    "source": "프렙업 영어학원 프린트 (PAGE 10/50)",
    "words": [
      {
        "n": 1,
        "en": "return",
        "ko": "[동] 1. 돌아가다[오다] 2. 돌려주다, 반납하다 / [명] 돌아감, 귀환",
        "ipa": "/rɪˈtɜːrn/",
        "stress": "re-TURN",
        "emoji": "🔙📚",
        "ex": "I have to return this book today.",
        "ex_ko": "나 오늘 이 책 반납해야 해.",
        "mnemonic": "re(다시) + turn(돌다) = 다시 돌아가다, 돌려주다."
      },
      {
        "n": 2,
        "en": "press",
        "ko": "[동] 누르다 / [명] 언론, 신문",
        "ipa": "/pres/",
        "stress": "PRESS",
        "emoji": "👆🔘",
        "ex": "Press this button to start the game.",
        "ex_ko": "게임을 시작하려면 이 버튼을 눌러.",
        "mnemonic": "'프레스'로 꾹 누르는 기계 생각! 신문도 종이를 눌러 찍어서 press."
      },
      {
        "n": 3,
        "en": "focus",
        "ko": "[동] 집중하다, 집중시키다 / [명] 초점, 중점",
        "ipa": "/ˈfoʊkəs/",
        "stress": "FO-cus",
        "emoji": "🎯🔍",
        "ex": "I can't focus with all this noise.",
        "ex_ko": "이렇게 시끄러우면 집중이 안 돼.",
        "mnemonic": "'포커스'는 카메라 초점! 한 곳에 초점을 맞추는 게 집중하다."
      },
      {
        "n": 4,
        "en": "dictionary",
        "ko": "[명] 사전",
        "ipa": "/ˈdɪkʃəneri/",
        "stress": "DIC-tion-ar-y",
        "emoji": "📖🔤",
        "ex": "Look up the word in your dictionary.",
        "ex_ko": "그 단어를 사전에서 찾아봐.",
        "mnemonic": "'딕션(diction, 말)'을 모아둔 책 = 사전. 말이 다 들어있는 책이야."
      },
      {
        "n": 5,
        "en": "allow",
        "ko": "[동] 허락하다, 허용하다",
        "ipa": "/əˈlaʊ/",
        "stress": "al-LOW",
        "emoji": "✅🙆",
        "ex": "My mom doesn't allow me to stay out late.",
        "ex_ko": "엄마는 내가 늦게까지 밖에 있는 걸 허락 안 하셔.",
        "mnemonic": "'얼라우' → '얼른 하우(해)!' 하고 허락해 주는 느낌."
      },
      {
        "n": 6,
        "en": "breathe",
        "ko": "[동] 숨 쉬다, 호흡하다",
        "ipa": "/briːð/",
        "stress": "BREATHE",
        "emoji": "😮‍💨🫁",
        "ex": "Just breathe slowly and calm down.",
        "ex_ko": "천천히 숨 쉬면서 진정해.",
        "mnemonic": "'브리~드' 하고 길게 소리 내보면 그게 바로 숨 쉬는 거야."
      },
      {
        "n": 7,
        "en": "trash",
        "ko": "[명] 쓰레기",
        "ipa": "/træʃ/",
        "stress": "TRASH",
        "emoji": "🗑️🍌",
        "ex": "Please take out the trash tonight.",
        "ex_ko": "오늘 밤에 쓰레기 좀 내다 버려.",
        "mnemonic": "'트래쉬' → '트럭에 쓸어(래쉬) 담는 쓰레기'로 기억!"
      },
      {
        "n": 8,
        "en": "success",
        "ko": "[명] 성공, 성과",
        "ipa": "/səkˈses/",
        "stress": "suc-CESS",
        "emoji": "🏆🎉",
        "ex": "Hard work is the key to success.",
        "ex_ko": "노력이 성공의 열쇠야.",
        "mnemonic": "'석세스' → '(어깨) 석! 세워' 성공하면 어깨가 으쓱 올라가지."
      },
      {
        "n": 9,
        "en": "rise",
        "ko": "[동] 1. 오르다, 상승하다 2. 일어나다 3. (해, 달이) 뜨다",
        "ipa": "/raɪz/",
        "stress": "RISE",
        "emoji": "📈🌅",
        "ex": "The sun will rise at six tomorrow.",
        "ex_ko": "내일 해는 6시에 뜰 거야.",
        "mnemonic": "라이즈! 하고 몸을 일으키며 해가 떠오르는 장면을 떠올려요."
      },
      {
        "n": 10,
        "en": "topic",
        "ko": "[명] 주제, 화제",
        "ipa": "/ˈtɑːpɪk/",
        "stress": "TO-pic",
        "emoji": "💬📋",
        "ex": "Let's change the topic to something fun.",
        "ex_ko": "더 재미있는 주제로 바꾸자.",
        "mnemonic": "'톱(top)'에 적힌 제목이 곧 주제예요. 맨 위에 오는 게 화제죠."
      },
      {
        "n": 11,
        "en": "scare",
        "ko": "[동] 겁주다, 겁나게 하다",
        "ipa": "/sker/",
        "stress": "SCARE",
        "emoji": "😱👻",
        "ex": "Don't scare me like that again!",
        "ex_ko": "다시는 그렇게 나 겁주지 마!",
        "mnemonic": "'스케어'가 '스산해'처럼 들려요. 스산하면 겁이 나죠."
      },
      {
        "n": 12,
        "en": "step",
        "ko": "[명] 1. (발)걸음 2. 조치 3. 단계",
        "ipa": "/step/",
        "stress": "STEP",
        "emoji": "👣🪜",
        "ex": "Take one more step and stop.",
        "ex_ko": "한 걸음 더 가고 멈춰.",
        "mnemonic": "스텝 밟는다는 말 그대로 발걸음, 계단 한 칸씩 오르는 단계예요."
      },
      {
        "n": 13,
        "en": "cooking",
        "ko": "[명] 요리(하기) / [형] 요리(용)의",
        "ipa": "/ˈkʊkɪŋ/",
        "stress": "COOK-ing",
        "emoji": "🍳👨‍🍳",
        "ex": "My mom is cooking dinner right now.",
        "ex_ko": "우리 엄마는 지금 저녁을 요리하고 계셔.",
        "mnemonic": "cook(요리하다) + ing = 요리하기. '쿡쿡' 찔러가며 음식을 익히는 모습이에요."
      },
      {
        "n": 14,
        "en": "anger",
        "ko": "[명] 화, 분노",
        "ipa": "/ˈæŋɡər/",
        "stress": "AN-ger",
        "emoji": "😡🔥",
        "ex": "He couldn't hide his anger at school.",
        "ex_ko": "그는 학교에서 화를 감출 수 없었어.",
        "mnemonic": "'앵거'가 '앵!' 하고 성내는 소리 같아요. 앵! 하면 화가 난 거죠."
      },
      {
        "n": 15,
        "en": "own",
        "ko": "[형] 자기 자신의 / [동] 소유하다",
        "ipa": "/oʊn/",
        "stress": "OWN",
        "emoji": "🙋🔑",
        "ex": "I want my own room someday.",
        "ex_ko": "언젠가 내 방을 갖고 싶어.",
        "mnemonic": "'오운'을 '오! 내 것'으로 기억해요. 내 자신의 것, 소유하다."
      },
      {
        "n": 16,
        "en": "praise",
        "ko": "[동] 칭찬하다 / [명] 칭찬, 찬양",
        "ipa": "/preɪz/",
        "stress": "PRAISE",
        "emoji": "👏🌟",
        "ex": "My teacher gave me praise for my work.",
        "ex_ko": "선생님이 내 과제를 칭찬해 주셨어.",
        "mnemonic": "'프레이즈' — 잘했다고 박수 치며 칭찬하는 소리로 기억해요."
      },
      {
        "n": 17,
        "en": "continue",
        "ko": "[동] 계속되다, 계속하다",
        "ipa": "/kənˈtɪnjuː/",
        "stress": "con-TIN-ue",
        "emoji": "▶️➡️",
        "ex": "The rain will continue until tomorrow morning.",
        "ex_ko": "비는 내일 아침까지 계속 올 거야.",
        "mnemonic": "con(함께) + tinue(잡다). 손을 놓지 않고 계속 이어가는 거예요."
      },
      {
        "n": 18,
        "en": "wooden",
        "ko": "[형] 나무로 된, 목재의",
        "ipa": "/ˈwʊdən/",
        "stress": "WOOD-en",
        "emoji": "🪵🪑",
        "ex": "We sat on an old wooden bench.",
        "ex_ko": "우리는 오래된 나무 벤치에 앉았어.",
        "mnemonic": "wood(나무) + -en(~로 된) = 나무로 된."
      },
      {
        "n": 19,
        "en": "certain",
        "ko": "[형] 1. 확실한, 확신하는 2. 어떤, 특정한",
        "ipa": "/ˈsɜːrtən/",
        "stress": "CER-tain",
        "emoji": "✅🤔",
        "ex": "I'm certain I locked the front door.",
        "ex_ko": "나 현관문 잠근 거 확실해.",
        "mnemonic": "'써튼(서든)' 확신에 차서 서 있는 모습. 확실한!"
      },
      {
        "n": 20,
        "en": "less",
        "ko": "[형] 더 적은, 덜한 / [부] 더 적게, 덜하게",
        "ipa": "/les/",
        "stress": "LESS",
        "emoji": "📉🤏",
        "ex": "I want less sugar in my coffee.",
        "ex_ko": "커피에 설탕 좀 덜 넣어줘.",
        "mnemonic": "little(적은)의 비교급이 less. 더 적은, 덜한."
      },
      {
        "n": 21,
        "en": "entire",
        "ko": "[형] 전체의",
        "ipa": "/ɪnˈtaɪər/",
        "stress": "en-TIRE",
        "emoji": "🌐🍰",
        "ex": "He ate the entire pizza by himself.",
        "ex_ko": "걔는 피자 한 판을 통째로 혼자 먹었어.",
        "mnemonic": "'인타이어' — 타이어 전체가 하나로 이어진 원. 전체의."
      },
      {
        "n": 22,
        "en": "at least",
        "ko": "적어도, 최소한",
        "ipa": "/æt ˈliːst/",
        "stress": "at LEAST",
        "emoji": "☝️📏",
        "ex": "You should sleep at least seven hours.",
        "ex_ko": "적어도 일곱 시간은 자야 해.",
        "mnemonic": "least(가장 적은)에 at을 붙이면 '가장 적어도' = 최소한."
      },
      {
        "n": 23,
        "en": "no longer",
        "ko": "더 이상 … 않다",
        "ipa": "/noʊ ˈlɔːŋɡər/",
        "stress": "no LON-ger",
        "emoji": "🚫⏳",
        "ex": "She no longer lives in this town.",
        "ex_ko": "그 애는 더 이상 이 동네에 안 살아.",
        "mnemonic": "no(아니) + longer(더 오래) = 더 이상 오래 안 함."
      },
      {
        "n": 24,
        "en": "look up",
        "ko": "1. (정보 등을) 찾아보다 2. 올려다보다",
        "ipa": "/lʊk ʌp/",
        "stress": "LOOK up",
        "emoji": "🔎📖⬆️",
        "ex": "Let's look up the answer online.",
        "ex_ko": "온라인으로 답을 찾아보자.",
        "mnemonic": "사전 위쪽(up)을 훑어보며(look) 찾는다. 올려다보기도 그대로."
      }
    ]
  },
  {
    "pack_id": "reading-tutor-junior1-section09-1",
    "title": "리딩튜터 주니어 1 섹션 9-1",
    "source": "리딩튜터 주니어 1 · 섹션 9 어휘리스트 프린트 (1~42번)",
    "words": [
      {
        "n": 1,
        "en": "exciting",
        "ko": "흥미진진한",
        "ipa": "/ɪkˈsaɪtɪŋ/",
        "stress": "ex-CI-ting",
        "emoji": "🎢🤩",
        "ex": "The last soccer game was really exciting.",
        "ex_ko": "지난 축구 경기는 정말 흥미진진했어.",
        "mnemonic": "익사이팅! 익사할 뻔할 만큼 심장 뛰는 상황이 흥미진진한 거예요."
      },
      {
        "n": 2,
        "en": "excitement",
        "ko": "흥분, 신남",
        "ipa": "/ɪkˈsaɪtmənt/",
        "stress": "ex-CITE-ment",
        "emoji": "🎉😆",
        "ex": "I couldn't sleep from excitement last night.",
        "ex_ko": "어젯밤엔 신나서 잠을 못 잤어.",
        "mnemonic": "exciting(흥미진진한)에 -ment 붙으면 그 느낌 자체, 즉 흥분·신남이 돼요."
      },
      {
        "n": 3,
        "en": "experience",
        "ko": "경험하다",
        "ipa": "/ɪkˈspɪriəns/",
        "stress": "ex-PE-ri-ence",
        "emoji": "🧗🌏",
        "ex": "I want to experience life in another country.",
        "ex_ko": "나는 다른 나라에서의 삶을 경험해 보고 싶어.",
        "mnemonic": "'익스피리언스' → 익숙해지려면 피(땀) 흘리며 겪어봐야죠. 직접 겪는 게 경험."
      },
      {
        "n": 4,
        "en": "stay",
        "ko": "머물다, 묵다; 머무름, 방문",
        "ipa": "/steɪ/",
        "stress": "STAY",
        "emoji": "🏨🛏️",
        "ex": "We stayed at my grandma's house last weekend.",
        "ex_ko": "우리는 지난 주말에 할머니 댁에서 묵었어.",
        "mnemonic": "'스테이'는 '서 있다(stand)'와 친척 — 안 가고 그 자리에 머무르는 거예요."
      },
      {
        "n": 5,
        "en": "locate",
        "ko": "~에 위치시키다",
        "ipa": "/ˈloʊkeɪt/",
        "stress": "LO-cate",
        "emoji": "📍🗺️",
        "ex": "They located the new school near the park.",
        "ex_ko": "그들은 새 학교를 공원 근처에 위치시켰어.",
        "mnemonic": "로케이션(location, 장소)의 동사형. '로케 잡는다' = 자리를 잡아 위치시키다."
      },
      {
        "n": 6,
        "en": "halfway",
        "ko": "중간에",
        "ipa": "/ˌhæfˈweɪ/",
        "stress": "half-WAY",
        "emoji": "🚶‍♂️➖🏁",
        "ex": "We stopped halfway up the mountain to rest.",
        "ex_ko": "우리는 산 중턱에서 쉬려고 멈췄어.",
        "mnemonic": "half(반) + way(길) = 길의 절반 지점, 즉 중간에."
      },
      {
        "n": 7,
        "en": "cliff",
        "ko": "절벽",
        "ipa": "/klɪf/",
        "stress": "CLIFF",
        "emoji": "🧗‍♀️🪨",
        "ex": "Don't stand so close to the cliff.",
        "ex_ko": "절벽에 그렇게 가까이 서 있지 마.",
        "mnemonic": "'클리프' → 낭떠러지에서 미끄러지면 '끌립!' 하고 떨어져요. 절벽."
      },
      {
        "n": 8,
        "en": "climb",
        "ko": "오르다",
        "ipa": "/klaɪm/",
        "stress": "CLIMB",
        "emoji": "🧗🌲",
        "ex": "My little brother loves to climb trees.",
        "ex_ko": "내 남동생은 나무 오르는 걸 정말 좋아해.",
        "mnemonic": "'클라임' → 클라이밍(암벽등반) 할 때 그 climb. b는 소리 안 나요."
      },
      {
        "n": 9,
        "en": "foot",
        "ko": "발; 피트(길이의 단위로 약 30센티미터에 해당)",
        "ipa": "/fʊt/",
        "stress": "FOOT",
        "emoji": "🦶📏",
        "ex": "My right foot hurts after the soccer game.",
        "ex_ko": "축구 경기 후에 오른쪽 발이 아파.",
        "mnemonic": "'풋' 하고 발을 내딛는 소리. 발 하나 길이가 딱 1피트(30cm)예요."
      },
      {
        "n": 10,
        "en": "roof",
        "ko": "지붕",
        "ipa": "/ruːf/",
        "stress": "ROOF",
        "emoji": "🏠🔺",
        "ex": "A cat is sleeping on the roof.",
        "ex_ko": "고양이가 지붕 위에서 자고 있어.",
        "mnemonic": "'루프(loop)'처럼 집 위를 빙 둘러 덮는 지붕. foot과 짝: 발은 아래, 지붕은 위."
      },
      {
        "n": 11,
        "en": "amazing",
        "ko": "놀라운",
        "ipa": "/əˈmeɪzɪŋ/",
        "stress": "a-MAZ-ing",
        "emoji": "😲✨",
        "ex": "Your new phone case looks amazing!",
        "ex_ko": "네 새 폰 케이스 정말 멋지다!",
        "mnemonic": "미로(maze)에 갇힌 듯 정신이 아득할 만큼 놀라운. '어메이징!' 감탄사 그대로예요."
      },
      {
        "n": 12,
        "en": "view",
        "ko": "경관, 전망",
        "ipa": "/vjuː/",
        "stress": "VIEW",
        "emoji": "🏞️👀",
        "ex": "The view from my window is really nice.",
        "ex_ko": "내 창문에서 보이는 경관이 정말 좋아.",
        "mnemonic": "유튜브 조회수 '뷰(view)'는 눈으로 본 횟수. 눈에 보이는 풍경이 경관이에요."
      },
      {
        "n": 13,
        "en": "valley",
        "ko": "계곡",
        "ipa": "/ˈvæli/",
        "stress": "VAL-ley",
        "emoji": "⛰️🏞️",
        "ex": "We walked through a quiet green valley.",
        "ex_ko": "우리는 조용한 초록빛 계곡을 걸어서 지나갔어.",
        "mnemonic": "산이 V자로 파인 곳이 계곡. 'V'앨리 = V 모양 골짜기로 외우세요."
      },
      {
        "n": 14,
        "en": "below",
        "ko": "아래에",
        "ipa": "/bɪˈloʊ/",
        "stress": "be-LOW",
        "emoji": "⬇️📉",
        "ex": "My name is written below yours.",
        "ex_ko": "내 이름은 네 이름 아래에 적혀 있어.",
        "mnemonic": "be + low(낮은) = 낮은 곳에 있다, 즉 아래에. low만 기억하면 끝이에요."
      },
      {
        "n": 15,
        "en": "bottom",
        "ko": "맨 아래",
        "ipa": "/ˈbɑːtəm/",
        "stress": "BOT-tom",
        "emoji": "🪣⬇️",
        "ex": "My keys were at the bottom of my bag.",
        "ex_ko": "내 열쇠는 가방 맨 아래에 있었어.",
        "mnemonic": "'바텀'은 페트병 바닥(bottle 바텀). 병 제일 밑바닥이 bottom이에요."
      },
      {
        "n": 16,
        "en": "nature",
        "ko": "자연",
        "ipa": "/ˈneɪtʃər/",
        "stress": "NA-ture",
        "emoji": "🌳🌊",
        "ex": "I love walking in nature on weekends.",
        "ex_ko": "나는 주말에 자연 속을 걷는 걸 좋아해.",
        "mnemonic": "'네이처' 하면 떠오르는 다큐 화면 — 태어난(nat=태어나다) 그대로의 세상, 자연."
      },
      {
        "n": 17,
        "en": "part",
        "ko": "부분; 지역",
        "ipa": "/pɑːrt/",
        "stress": "PART",
        "emoji": "🧩",
        "ex": "This part of the city is really quiet.",
        "ex_ko": "도시의 이 지역은 정말 조용해.",
        "mnemonic": "퍼즐을 '팟' 하고 떼어낸 한 조각이 part(부분)."
      },
      {
        "n": 18,
        "en": "unusual",
        "ko": "독특한; 신기한",
        "ipa": "/ʌnˈjuːʒuəl/",
        "stress": "un-U-su-al",
        "emoji": "🦄",
        "ex": "That's an unusual name for a dog.",
        "ex_ko": "개 이름치고는 독특하네.",
        "mnemonic": "un(아니다) + usual(보통의) = 보통이 아닌, 독특한."
      },
      {
        "n": 19,
        "en": "danger",
        "ko": "위험 (요소)",
        "ipa": "/ˈdeɪndʒər/",
        "stress": "DAN-ger",
        "emoji": "⚠️",
        "ex": "Swimming here can be a real danger.",
        "ex_ko": "여기서 수영하는 건 정말 위험할 수 있어.",
        "mnemonic": "'댄져!' 하고 외치는 경고음 — 위험 표지판 소리."
      },
      {
        "n": 20,
        "en": "typical",
        "ko": "전형적인",
        "ipa": "/ˈtɪpɪkl/",
        "stress": "TY-pi-cal",
        "emoji": "📋",
        "ex": "It was a typical Monday at school.",
        "ex_ko": "학교에서 전형적인 월요일이었어.",
        "mnemonic": "타입(type)이 딱 정해진 것 = 전형적인."
      },
      {
        "n": 21,
        "en": "bright",
        "ko": "밝은; 선명한",
        "ipa": "/braɪt/",
        "stress": "BRIGHT",
        "emoji": "☀️",
        "ex": "The sun is too bright this morning.",
        "ex_ko": "오늘 아침엔 햇빛이 너무 밝아.",
        "mnemonic": "'브라이트'하게 불이 확 켜지는 느낌 — 밝다."
      },
      {
        "n": 22,
        "en": "wetland",
        "ko": "습지",
        "ipa": "/ˈwetlænd/",
        "stress": "WET-land",
        "emoji": "🌾💧",
        "ex": "Many birds live in this wetland area.",
        "ex_ko": "많은 새들이 이 습지 지역에 살아.",
        "mnemonic": "wet(젖은) + land(땅) = 젖은 땅, 즉 습지."
      },
      {
        "n": 23,
        "en": "northeast",
        "ko": "북동의",
        "ipa": "/ˌnɔːrθˈiːst/",
        "stress": "north-EAST",
        "emoji": "🧭↗️",
        "ex": "My grandma lives in the northeast part.",
        "ex_ko": "우리 할머니는 북동쪽 지역에 사셔.",
        "mnemonic": "north(북) + east(동) = 북동의. 나침반 오른쪽 위."
      },
      {
        "n": 24,
        "en": "impressive",
        "ko": "인상적인",
        "ipa": "/ɪmˈpresɪv/",
        "stress": "im-PRES-sive",
        "emoji": "😮👏",
        "ex": "Your drawing skills are really impressive.",
        "ex_ko": "네 그림 실력 정말 인상적이야.",
        "mnemonic": "마음속에 press(꾹 눌러) 찍힌 것 = 인상적인."
      },
      {
        "n": 25,
        "en": "be covered in",
        "ko": "~로 덮여 있다",
        "ipa": "/bi ˈkʌvərd ɪn/",
        "stress": "be CO-vered in",
        "emoji": "🏔️❄️",
        "ex": "The mountain is covered in white snow.",
        "ex_ko": "그 산은 하얀 눈으로 덮여 있어.",
        "mnemonic": "cover(커버)는 덮개! be covered in은 '~로 덮인 상태'예요."
      },
      {
        "n": 26,
        "en": "autumn",
        "ko": "가을",
        "ipa": "/ˈɔːtəm/",
        "stress": "AU-tumn",
        "emoji": "🍂🍁",
        "ex": "I love the cool weather in autumn.",
        "ex_ko": "나는 가을의 시원한 날씨를 좋아해.",
        "mnemonic": "'어텀'—어! 텀벙 낙엽이 떨어지는 계절, 가을이에요."
      },
      {
        "n": 27,
        "en": "scenery",
        "ko": "풍경",
        "ipa": "/ˈsiːnəri/",
        "stress": "SCE-ner-y",
        "emoji": "🏞️📷",
        "ex": "The scenery from the window is beautiful.",
        "ex_ko": "창밖 풍경이 정말 아름다워.",
        "mnemonic": "scene(장면)+ry → 눈앞에 펼쳐진 장면, 곧 풍경이에요."
      },
      {
        "n": 28,
        "en": "wooden",
        "ko": "나무로 된, 목재의",
        "ipa": "/ˈwʊdn/",
        "stress": "WOO-den",
        "emoji": "🪵🪑",
        "ex": "We sat on an old wooden bench.",
        "ex_ko": "우리는 낡은 나무 벤치에 앉았어.",
        "mnemonic": "wood(나무)에 -en 붙으면 '나무로 된'이 돼요."
      },
      {
        "n": 29,
        "en": "deck",
        "ko": "갑판",
        "ipa": "/dek/",
        "stress": "DECK",
        "emoji": "🚢🛳️",
        "ex": "We watched the sea from the deck.",
        "ex_ko": "우리는 갑판에서 바다를 바라봤어.",
        "mnemonic": "'덱!'—배 위 넓은 마룻바닥을 덱덱 밟고 다녀요."
      },
      {
        "n": 30,
        "en": "effort",
        "ko": "노력",
        "ipa": "/ˈefərt/",
        "stress": "EF-fort",
        "emoji": "💪😤",
        "ex": "She made a big effort to win.",
        "ex_ko": "그녀는 이기려고 큰 노력을 했어.",
        "mnemonic": "'에퍼트'—에구, 퍼뜩 힘내자! 하는 게 노력이에요."
      },
      {
        "n": 31,
        "en": "protect",
        "ko": "보호하다",
        "ipa": "/prəˈtekt/",
        "stress": "pro-TECT",
        "emoji": "🛡️🙅",
        "ex": "A helmet will protect your head.",
        "ex_ko": "헬멧이 네 머리를 보호해 줄 거야.",
        "mnemonic": "앞에(pro) 방패를 대고(tect) 막아주니 '보호하다'예요."
      },
      {
        "n": 32,
        "en": "suffer",
        "ko": "고통받다",
        "ipa": "/ˈsʌfər/",
        "stress": "SUF-fer",
        "emoji": "😣🤕",
        "ex": "Many people suffer from back pain.",
        "ex_ko": "많은 사람들이 허리 통증으로 고통받아.",
        "mnemonic": "'써퍼'—써! 퍼억! 아파서 고통받는 소리로 외워요."
      },
      {
        "n": 33,
        "en": "due to",
        "ko": "~으로 인해, ~ 때문에",
        "ipa": "/ˈduː tuː/",
        "stress": "DUE to",
        "emoji": "➡️🌧️",
        "ex": "The game was canceled due to rain.",
        "ex_ko": "비 때문에 경기가 취소됐어.",
        "mnemonic": "\"두(due) 탓이야\" — 뒤에 오는 게 원인. 'because of'랑 똑같이 쓰면 돼요."
      },
      {
        "n": 34,
        "en": "pollution",
        "ko": "오염, 공해",
        "ipa": "/pəˈluːʃn/",
        "stress": "pol-LU-tion",
        "emoji": "🏭🌫️🌊",
        "ex": "Air pollution is getting worse in our city.",
        "ex_ko": "우리 도시의 대기 오염이 점점 심해지고 있어.",
        "mnemonic": "\"펄루션\" → 물이 펄펄 끓듯 더러워진 상태. pollute(오염시키다)의 명사형."
      },
      {
        "n": 35,
        "en": "build",
        "ko": "짓다",
        "ipa": "/bɪld/",
        "stress": "BUILD",
        "emoji": "🏗️🧱",
        "ex": "They will build a new library next year.",
        "ex_ko": "그들은 내년에 새 도서관을 지을 거야.",
        "mnemonic": "\"빌드\" — 게임에서 건물 짓는 걸 '빌드한다'고 하죠. 그대로 짓다."
      },
      {
        "n": 36,
        "en": "feature",
        "ko": "특징, 특색",
        "ipa": "/ˈfiːtʃər/",
        "stress": "FEA-ture",
        "emoji": "⭐🔍",
        "ex": "The red roof is the most famous feature of this house.",
        "ex_ko": "빨간 지붕이 이 집의 가장 유명한 특징이야.",
        "mnemonic": "'피처폰'의 그 feature! 그것만의 두드러진 특징·특색을 말해요."
      },
      {
        "n": 37,
        "en": "endangered",
        "ko": "멸종 위기에 처한",
        "ipa": "/ɪnˈdeɪndʒərd/",
        "stress": "en-DAN-gered",
        "emoji": "🐼⚠️",
        "ex": "Pandas are an endangered animal.",
        "ex_ko": "판다는 멸종 위기 동물이야.",
        "mnemonic": "en(안으로) + danger(위험) → 위험 속에 들어간 상태, 즉 멸종 위기."
      },
      {
        "n": 38,
        "en": "check out",
        "ko": "~을 (살펴)보다, ~에 가 보다",
        "ipa": "/tʃek aʊt/",
        "stress": "CHECK out",
        "emoji": "👀🔎",
        "ex": "Check out this video, it's really funny!",
        "ex_ko": "이 영상 한번 봐, 진짜 웃겨!",
        "mnemonic": "\"체크(확인)하러 아웃(나가)\" → 가서 살펴보다, 구경하다."
      },
      {
        "n": 39,
        "en": "chain",
        "ko": "(상점·호텔 등의) 체인(점)",
        "ipa": "/tʃeɪn/",
        "stress": "CHAIN",
        "emoji": "⛓️🏪",
        "ex": "That coffee shop is a famous chain.",
        "ex_ko": "저 커피숍은 유명한 체인점이야.",
        "mnemonic": "쇠사슬(chain)처럼 여러 가게가 줄줄이 연결된 게 체인점."
      },
      {
        "n": 40,
        "en": "order",
        "ko": "주문하다",
        "ipa": "/ˈɔːrdər/",
        "stress": "OR-der",
        "emoji": "🍔📝",
        "ex": "Let's order pizza for dinner tonight.",
        "ex_ko": "오늘 저녁으로 피자 주문하자.",
        "mnemonic": "\"오더 받았습니다!\" 식당에서 쓰는 그 오더. 주문하다."
      },
      {
        "n": 41,
        "en": "touchscreen",
        "ko": "터치스크린",
        "ipa": "/ˈtʌtʃskriːn/",
        "stress": "TOUCH-screen",
        "emoji": "📱👆",
        "ex": "My phone's touchscreen is cracked but still works.",
        "ex_ko": "내 폰 터치스크린은 금이 갔지만 아직 작동해.",
        "mnemonic": "touch(만지다) + screen(화면) = 만지는 화면, 터치스크린."
      },
      {
        "n": 42,
        "en": "device",
        "ko": "장치, 기기",
        "ipa": "/dɪˈvaɪs/",
        "stress": "de-VICE",
        "emoji": "📱💻⌚",
        "ex": "You can connect three devices to this speaker.",
        "ex_ko": "이 스피커에는 기기를 세 개까지 연결할 수 있어.",
        "mnemonic": "\"디바이스\"는 이미 한국어로도 써요. 폰·노트북·워치 다 device예요."
      }
    ]
  },
  {
    "pack_id": "reading-tutor-junior1-section09-2",
    "title": "리딩튜터 주니어 1 섹션 9-2",
    "source": "리딩튜터 주니어 1 · 섹션 9 어휘리스트 프린트 (43~83번)",
    "words": [
      {
        "n": 1,
        "en": "arrive",
        "ko": "도착하다",
        "ipa": "/əˈraɪv/",
        "stress": "a-RRIVE",
        "emoji": "🛬📍",
        "ex": "We will arrive at the airport at six.",
        "ex_ko": "우리는 6시에 공항에 도착할 거야.",
        "mnemonic": "'어라이브(살아서) 도착했다'로 외우세요. 무사히 살아서 도착!"
      },
      {
        "n": 2,
        "en": "track",
        "ko": "선로",
        "ipa": "/træk/",
        "stress": "TRACK",
        "emoji": "🛤️🚂",
        "ex": "The train is waiting on track three.",
        "ex_ko": "기차가 3번 선로에서 기다리고 있어.",
        "mnemonic": "트랙(운동장 트랙)처럼 길게 뻗은 길이 기차 선로예요."
      },
      {
        "n": 3,
        "en": "own",
        "ko": "자기 자신의",
        "ipa": "/oʊn/",
        "stress": "OWN",
        "emoji": "🙋🔑",
        "ex": "I want my own room someday.",
        "ex_ko": "나는 언젠가 내 방을 갖고 싶어.",
        "mnemonic": "'오운(오직 나의 것)'으로 기억하세요. 남 것 아닌 자기 것!"
      },
      {
        "n": 4,
        "en": "up to",
        "ko": "~까지",
        "ipa": "/ˈʌp tu/",
        "stress": "UP to",
        "emoji": "⬆️🔟",
        "ex": "This bus holds up to fifty people.",
        "ex_ko": "이 버스는 50명까지 탈 수 있어.",
        "mnemonic": "위로(up) 어디까지(to) 올라가나 → '~까지'라는 한계선이에요."
      },
      {
        "n": 5,
        "en": "tall",
        "ko": "키가 ~인; 높은",
        "ipa": "/tɔːl/",
        "stress": "TALL",
        "emoji": "📏🦒",
        "ex": "My brother is very tall for his age.",
        "ex_ko": "우리 형은 나이에 비해 키가 아주 커.",
        "mnemonic": "'토(tall)'은 키가 쭉 뻗은 느낌. 기린처럼 키가 ~인, 높은."
      },
      {
        "n": 6,
        "en": "travel",
        "ko": "여행하다; 이동하다",
        "ipa": "/ˈtrævəl/",
        "stress": "TRA-vel",
        "emoji": "✈️🧳",
        "ex": "I want to travel to Japan next year.",
        "ex_ko": "나는 내년에 일본으로 여행 가고 싶어.",
        "mnemonic": "'트래블'—트렁크 끌고 벌벌 떨며 떠나는 여행이라고 상상하세요."
      },
      {
        "n": 7,
        "en": "per",
        "ko": "~당, ~마다",
        "ipa": "/pɜːr/",
        "stress": "PER",
        "emoji": "➗🕐",
        "ex": "The car goes ninety kilometers per hour.",
        "ex_ko": "그 차는 시속 90킬로미터로 달려.",
        "mnemonic": "퍼센트(per cent)는 '100당'이죠. per = '~당, ~마다'예요."
      },
      {
        "n": 8,
        "en": "afraid",
        "ko": "두려워하는",
        "ipa": "/əˈfreɪd/",
        "stress": "a-FRAID",
        "emoji": "😨👻",
        "ex": "My little sister is afraid of dogs.",
        "ex_ko": "내 여동생은 개를 무서워해.",
        "mnemonic": "'어! 프레이드(프라이팬)!' 뜨거운 게 튈까 봐 두려워하는 장면."
      },
      {
        "n": 9,
        "en": "though",
        "ko": "그렇지만, 하지만",
        "ipa": "/ðoʊ/",
        "stress": "THOUGH",
        "emoji": "🤔↔️",
        "ex": "I didn't wear a coat, though it was cold.",
        "ex_ko": "추웠지만 나는 코트를 입지 않았어.",
        "mnemonic": "'도우' 하고 반죽처럼 말이 뒤집히는 느낌. 앞말과 반대로 꺾을 때 쓰는 '하지만'."
      },
      {
        "n": 10,
        "en": "place",
        "ko": "놓다",
        "ipa": "/pleɪs/",
        "stress": "PLACE",
        "emoji": "📦👇",
        "ex": "Please place the box on the table.",
        "ex_ko": "그 상자를 탁자 위에 놓아 주세요.",
        "mnemonic": "'플레이스(장소)'에 물건을 딱 두는 것. 장소에 놓다 → 놓다."
      },
      {
        "n": 11,
        "en": "metal",
        "ko": "금속",
        "ipa": "/ˈmetl/",
        "stress": "ME-tal",
        "emoji": "🔩⚙️",
        "ex": "This spoon is made of metal, not plastic.",
        "ex_ko": "이 숟가락은 플라스틱이 아니라 금속으로 만들어졌어.",
        "mnemonic": "'메탈 음악'의 그 메탈! 쇳소리 나는 금속이야."
      },
      {
        "n": 12,
        "en": "pot",
        "ko": "냄비, 통",
        "ipa": "/pɑːt/",
        "stress": "POT",
        "emoji": "🍲🔥",
        "ex": "Mom is boiling water in a big pot.",
        "ex_ko": "엄마가 큰 냄비에 물을 끓이고 계셔.",
        "mnemonic": "'팟!' 하고 국물이 끓어 넘치는 냄비 소리."
      },
      {
        "n": 13,
        "en": "lid",
        "ko": "뚜껑",
        "ipa": "/lɪd/",
        "stress": "LID",
        "emoji": "🫙🔝",
        "ex": "Don't forget to put the lid on the cup.",
        "ex_ko": "컵에 뚜껑 덮는 거 잊지 마.",
        "mnemonic": "'리드'가 위에서 덮어 준다. 냄비 위에 딱 얹는 뚜껑."
      },
      {
        "n": 14,
        "en": "secure",
        "ko": "고정하다",
        "ipa": "/sɪˈkjʊr/",
        "stress": "se-CURE",
        "emoji": "🔒🪢",
        "ex": "Secure the bike with a strong lock.",
        "ex_ko": "튼튼한 자물쇠로 자전거를 고정해.",
        "mnemonic": "'시큐리티(보안)'의 그 단어. 안 움직이게 꽉 고정하다."
      },
      {
        "n": 15,
        "en": "strap",
        "ko": "끈",
        "ipa": "/stræp/",
        "stress": "STRAP",
        "emoji": "🎒➰",
        "ex": "The strap on my bag is too long.",
        "ex_ko": "내 가방 끈이 너무 길어.",
        "mnemonic": "'스트랩'은 가방·시계 끈. 스트! 하고 조여 매는 끈."
      },
      {
        "n": 16,
        "en": "safety",
        "ko": "안전",
        "ipa": "/ˈseɪfti/",
        "stress": "SAFE-ty",
        "emoji": "🦺⛑️",
        "ex": "Wear a helmet for your own safety.",
        "ex_ko": "네 안전을 위해 헬멧을 써.",
        "mnemonic": "safe(안전한) + ty(성질) = 안전. '세이프!' 외치면 안전한 거야."
      },
      {
        "n": 17,
        "en": "reason",
        "ko": "이유",
        "ipa": "/ˈriːzən/",
        "stress": "REA-son",
        "emoji": "❓🤔💡",
        "ex": "Tell me the reason you were late today.",
        "ex_ko": "오늘 늦은 이유를 말해 봐.",
        "mnemonic": "\"리즌\"—\"이유(理由)를 리(理)로\" 기억! 리즌 하면 이치를 따지는 이유."
      },
      {
        "n": 18,
        "en": "serve",
        "ko": "제공하다, (음식을 상에) 내다",
        "ipa": "/sɜːrv/",
        "stress": "SERVE",
        "emoji": "🍽️🙋‍♂️",
        "ex": "They serve free bread at this restaurant.",
        "ex_ko": "이 식당은 공짜 빵을 제공해요.",
        "mnemonic": "\"서브\"—배구 서브 넣듯 음식을 손님 앞에 척 내놓는다."
      },
      {
        "n": 19,
        "en": "shaped",
        "ko": "~의 모양의",
        "ipa": "/ʃeɪpt/",
        "stress": "SHAPED",
        "emoji": "❤️🍪⭐",
        "ex": "She gave me a heart-shaped cookie.",
        "ex_ko": "걔가 하트 모양의 쿠키를 줬어.",
        "mnemonic": "shape(모양) + -ed(~된) = \"~의 모양의\". 쉐입이 붙은 상태."
      },
      {
        "n": 20,
        "en": "amusement park",
        "ko": "놀이공원",
        "ipa": "/əˈmjuːzmənt pɑːrk/",
        "stress": "a-MUSE-ment PARK",
        "emoji": "🎢🎡🎠",
        "ex": "Let's go to the amusement park this weekend.",
        "ex_ko": "이번 주말에 놀이공원 가자.",
        "mnemonic": "amuse(즐겁게 하다) + park(공원) = 즐겁게 해주는 공원, 놀이공원!"
      },
      {
        "n": 21,
        "en": "Antarctica",
        "ko": "남극 대륙",
        "ipa": "/ænˈtɑːrktɪkə/",
        "stress": "ant-ARC-ti-ca",
        "emoji": "🐧🧊🌎",
        "ex": "Penguins live in Antarctica all year long.",
        "ex_ko": "펭귄은 남극 대륙에서 일 년 내내 살아요.",
        "mnemonic": "anti(반대) + arctic(북극) = 북극의 반대편, 즉 남극 대륙."
      },
      {
        "n": 22,
        "en": "temperature",
        "ko": "기온",
        "ipa": "/ˈtemprətʃər/",
        "stress": "TEM-per-a-ture",
        "emoji": "🌡️🔥❄️",
        "ex": "The temperature will be very high tomorrow.",
        "ex_ko": "내일은 기온이 아주 높을 거예요.",
        "mnemonic": "\"템퍼러쳐\"—템(temp)은 온도 표시! 체온계 볼 때 나오는 그 단어."
      },
      {
        "n": 23,
        "en": "drop",
        "ko": "(잘못해서) 떨어지다; 낮아지다",
        "ipa": "/drɑːp/",
        "stress": "DROP",
        "emoji": "📱⬇️💧",
        "ex": "Be careful! Don't drop your new phone.",
        "ex_ko": "조심해! 새 휴대폰 떨어뜨리지 마.",
        "mnemonic": "\"드롭\"—물방울(드롭)이 뚝 떨어지는 소리. 떨어뜨리다, 낮아지다."
      },
      {
        "n": 24,
        "en": "beneath",
        "ko": "아래에",
        "ipa": "/bɪˈniːθ/",
        "stress": "be-NEATH",
        "emoji": "🐱🛏️⬇️",
        "ex": "The cat is sleeping beneath my bed.",
        "ex_ko": "고양이가 내 침대 아래에서 자고 있어.",
        "mnemonic": "\"비니쓰\"—비니(모자) 쓰면 머리가 그 아래에 있지. 아래에!"
      },
      {
        "n": 25,
        "en": "surprisingly",
        "ko": "놀랍게도",
        "ipa": "/sərˈpraɪzɪŋli/",
        "stress": "sur-PRI-zing-ly",
        "emoji": "😲❗",
        "ex": "The test was surprisingly easy for everyone.",
        "ex_ko": "그 시험은 놀랍게도 모두에게 쉬웠어.",
        "mnemonic": "surprise(놀람)에 -ly가 붙어 '놀랍게도'. '써프라이즈!' 하면 다들 놀라죠."
      },
      {
        "n": 26,
        "en": "huge",
        "ko": "거대한",
        "ipa": "/hjuːdʒ/",
        "stress": "HUGE",
        "emoji": "🐘🏔️",
        "ex": "My brother eats a huge breakfast every day.",
        "ex_ko": "우리 형은 매일 엄청나게 큰 아침을 먹어.",
        "mnemonic": "'휴~지' 하고 한숨 나올 만큼 거대하다고 외우세요."
      },
      {
        "n": 27,
        "en": "lake",
        "ko": "호수",
        "ipa": "/leɪk/",
        "stress": "LAKE",
        "emoji": "🏞️🦆",
        "ex": "We went fishing at the lake last weekend.",
        "ex_ko": "우리는 지난 주말에 호수로 낚시를 갔어.",
        "mnemonic": "'레이크'—물결이 잔잔한 호수. cake(케이크)처럼 -ake 소리, 호수 위에 케이크 띄우기."
      },
      {
        "n": 28,
        "en": "long",
        "ko": "긴; 길이가 ~인",
        "ipa": "/lɔːŋ/",
        "stress": "LONG",
        "emoji": "📏🐍",
        "ex": "Her hair is very long this year.",
        "ex_ko": "올해 그 애 머리가 아주 길어.",
        "mnemonic": "'롱치마'의 롱이 바로 이 long. 길게 늘어진 모습이죠."
      },
      {
        "n": 29,
        "en": "wide",
        "ko": "넓은; 폭이 ~인",
        "ipa": "/waɪd/",
        "stress": "WIDE",
        "emoji": "↔️🛣️",
        "ex": "This road is wide enough for two buses.",
        "ex_ko": "이 도로는 버스 두 대가 다닐 만큼 넓어.",
        "mnemonic": "'와이드 화면'의 와이드—좌우로 폭이 넓은 것."
      },
      {
        "n": 30,
        "en": "deep",
        "ko": "깊은; 깊이가 ~인",
        "ipa": "/diːp/",
        "stress": "DEEP",
        "emoji": "🌊⬇️",
        "ex": "Don't swim there; the water is too deep.",
        "ex_ko": "거기서 수영하지 마, 물이 너무 깊어.",
        "mnemonic": "'딥'하게 담근다—딥소스에 푹 담글 만큼 깊다."
      },
      {
        "n": 31,
        "en": "contain",
        "ko": "포함하다, 함유하다",
        "ipa": "/kənˈteɪn/",
        "stress": "con-TAIN",
        "emoji": "📦🥛",
        "ex": "This drink contains a lot of sugar.",
        "ex_ko": "이 음료는 설탕을 많이 함유하고 있어.",
        "mnemonic": "컨테이너(container)가 물건을 담고 있죠. contain은 '담다, 포함하다'."
      },
      {
        "n": 32,
        "en": "fresh water",
        "ko": "민물",
        "ipa": "/ˌfreʃ ˈwɔːtər/",
        "stress": "fresh WA-ter",
        "emoji": "💧🏞️",
        "ex": "Most fish in this lake need fresh water.",
        "ex_ko": "이 호수의 물고기 대부분은 민물이 필요해.",
        "mnemonic": "fresh(신선한)+water(물)=소금기 없는 민물. 바닷물 반대말이에요."
      },
      {
        "n": 33,
        "en": "million",
        "ko": "100만",
        "ipa": "/ˈmɪljən/",
        "stress": "MIL-lion",
        "emoji": "💰🔢",
        "ex": "One million people live in this city.",
        "ex_ko": "이 도시에는 백만 명이 살아요.",
        "mnemonic": "'밀리언'은 밀이 백만 알! 밀 알갱이 백만 개를 세는 장면을 떠올리세요."
      },
      {
        "n": 34,
        "en": "freeze",
        "ko": "얼다",
        "ipa": "/friːz/",
        "stress": "FREEZE",
        "emoji": "🧊❄️",
        "ex": "The water will freeze in the cold.",
        "ex_ko": "물이 추위에 얼 거예요.",
        "mnemonic": "'프리즈!' 하면 얼음땡처럼 그 자리에 얼어붙어요."
      },
      {
        "n": 35,
        "en": "possible",
        "ko": "가능한",
        "ipa": "/ˈpɑːsəbl/",
        "stress": "POS-si-ble",
        "emoji": "✅🤔",
        "ex": "Is it possible to finish this today?",
        "ex_ko": "오늘 이걸 끝내는 게 가능해요?",
        "mnemonic": "'파서블' → 땅을 파서 뭐든 될 수 있다, 가능하다!"
      },
      {
        "n": 36,
        "en": "thick",
        "ko": "두꺼운",
        "ipa": "/θɪk/",
        "stress": "THICK",
        "emoji": "📚🧱",
        "ex": "This book is really thick and heavy.",
        "ex_ko": "이 책은 정말 두껍고 무거워요.",
        "mnemonic": "'씩' 소리 나게 두꺼운 책을 덮는 모습! 두꺼워야 씩 소리가 나죠."
      },
      {
        "n": 37,
        "en": "prevent",
        "ko": "막다, 예방하다",
        "ipa": "/prɪˈvent/",
        "stress": "pre-VENT",
        "emoji": "🚫🛡️",
        "ex": "Wash your hands to prevent colds.",
        "ex_ko": "감기를 예방하려면 손을 씻으세요.",
        "mnemonic": "pre(미리) + vent(오다) → 미리 와서 막는다, 예방하다."
      },
      {
        "n": 38,
        "en": "heat",
        "ko": "열, 열기",
        "ipa": "/hiːt/",
        "stress": "HEAT",
        "emoji": "🔥🌡️",
        "ex": "The heat from the sun is strong.",
        "ex_ko": "태양에서 나오는 열기가 강해요.",
        "mnemonic": "'히트'치면 뜨겁게 달아오르죠. 히터(heater)가 내뿜는 게 heat!"
      },
      {
        "n": 39,
        "en": "within",
        "ko": "~ 내부에, ~ 안에",
        "ipa": "/wɪˈðɪn/",
        "stress": "with-IN",
        "emoji": "📦⏳",
        "ex": "I will call you within ten minutes.",
        "ex_ko": "10분 안에 전화할게요.",
        "mnemonic": "with(함께) + in(안) → 안에 함께 있다, ~ 안에."
      },
      {
        "n": 40,
        "en": "escape",
        "ko": "달아나다, 빠져나가다",
        "ipa": "/ɪˈskeɪp/",
        "stress": "es-CAPE",
        "emoji": "🏃‍♂️🚪",
        "ex": "The cat tried to escape from the box.",
        "ex_ko": "고양이가 상자에서 빠져나가려고 했어요.",
        "mnemonic": "키보드 Esc 키! 누르면 게임에서 빠져나가죠."
      },
      {
        "n": 41,
        "en": "global warming",
        "ko": "지구 온난화",
        "ipa": "/ˌɡloʊbəl ˈwɔːrmɪŋ/",
        "stress": "GLO-bal WAR-ming",
        "emoji": "🌍🔥🌡️",
        "ex": "Global warming is melting ice in the Arctic.",
        "ex_ko": "지구 온난화가 북극의 얼음을 녹이고 있어.",
        "mnemonic": "global(지구 전체) + warming(따뜻해짐) = 지구가 통째로 데워지는 것, 지구 온난화."
      }
    ]
  }
];
