// 내장 단어팩 (file:// 에서도 동작하도록 JS로 내장) — build_packs.py 가 생성
window.VOCA_BUILD = '0907.2312';
window.VOCA_PACKS = [
  {
    "pack_id": "neungyul-voca-middle-2025-day03",
    "title": "능률VOCA 중등 필수 [2025] DAY 03",
    "source": "프렙업 영어학원 프린트 (PAGE 3/50)",
    "words": [
      {
        "n": 1,
        "en": "pack",
        "ko": "[동] 1. (짐을) 싸다 2. 포장하다 / [명] (한) 갑[통/상자]",
        "ipa": "/pæk/",
        "stress": "PACK",
        "emoji": "🎒📦",
        "ex": "I need to pack my bag tonight.",
        "ex_ko": "나 오늘 밤에 가방 싸야 해.",
        "mnemonic": "'팩'하고 상자에 눌러 담는 소리. 짐을 팩팩 눌러 싸는 장면을 떠올리세요."
      },
      {
        "n": 2,
        "en": "male",
        "ko": "[형] 남성[수컷]의 / [명] 남성, 수컷",
        "ipa": "/meɪl/",
        "stress": "MALE",
        "emoji": "♂️👦",
        "ex": "The male lion has a big mane.",
        "ex_ko": "수컷 사자는 큰 갈기가 있어.",
        "mnemonic": "발음이 '메일(mail)'과 똑같아요. 남자한테 온 메일이라고 묶어서 기억하세요."
      },
      {
        "n": 3,
        "en": "finally",
        "ko": "[부] 1. 마침내, 결국 2. 마지막으로",
        "ipa": "/ˈfaɪnəli/",
        "stress": "FI-nal-ly",
        "emoji": "🏁😮‍💨",
        "ex": "I finally finished my science homework.",
        "ex_ko": "나 드디어 과학 숙제 끝냈어.",
        "mnemonic": "final(마지막) + ly. 마지막에 가서야, 즉 '마침내'예요."
      },
      {
        "n": 4,
        "en": "sometime",
        "ko": "[부] (과거, 미래의) 언제, 언젠가",
        "ipa": "/ˈsʌmtaɪm/",
        "stress": "SOME-time",
        "emoji": "📅❓",
        "ex": "Let's watch a movie sometime next week.",
        "ex_ko": "다음 주 언젠가 영화 보자.",
        "mnemonic": "some(어떤) + time(때) = 어떤 때, 즉 '언젠가'. 정확한 날짜는 몰라요."
      },
      {
        "n": 5,
        "en": "valley",
        "ko": "[명] 계곡, 골짜기",
        "ipa": "/ˈvæli/",
        "stress": "VAL-ley",
        "emoji": "🏞️⛰️",
        "ex": "We hiked down into the green valley.",
        "ex_ko": "우리는 초록 계곡으로 걸어 내려갔어.",
        "mnemonic": "'밸리'는 배구 '발리'처럼 푹 꺼진 곳. 산과 산 사이 푹 팬 골짜기예요."
      },
      {
        "n": 6,
        "en": "bark",
        "ko": "[동] (개가) 짖다",
        "ipa": "/bɑːrk/",
        "stress": "BARK",
        "emoji": "🐕🗯️",
        "ex": "My dog barks at every stranger.",
        "ex_ko": "우리 개는 낯선 사람만 보면 짖어.",
        "mnemonic": "'박!' 하고 개가 짖는 소리예요. 발음 그대로 개 짖는 소리로 외우세요."
      },
      {
        "n": 7,
        "en": "crash",
        "ko": "[동] 충돌[추락]하다 / [명] (자동차의) 충돌, (비행기의) 추락",
        "ipa": "/kræʃ/",
        "stress": "CRASH",
        "emoji": "💥🚗",
        "ex": "Two cars crashed near my school today.",
        "ex_ko": "오늘 학교 근처에서 차 두 대가 충돌했어.",
        "mnemonic": "'크래쉬!' 자체가 쾅 부딪히는 소리. 컴퓨터가 '크래시' 나는 것도 같은 말이에요."
      },
      {
        "n": 8,
        "en": "nature",
        "ko": "[명] 1. 자연 2. 천성, 본성",
        "ipa": "/ˈneɪtʃər/",
        "stress": "NA-ture",
        "emoji": "🌳🦋",
        "ex": "I love walking in nature after school.",
        "ex_ko": "나는 방과 후에 자연 속을 걷는 걸 좋아해.",
        "mnemonic": "'네이처'는 태어난(nat-) 그대로의 모습. 그래서 '자연'이자 타고난 '본성'이에요."
      },
      {
        "n": 9,
        "en": "harmony",
        "ko": "[명] 1. 조화, 화합 2. 화음",
        "ipa": "/ˈhɑːrməni/",
        "stress": "HAR-mo-ny",
        "emoji": "🎶🤝",
        "ex": "The two singers sang in perfect harmony.",
        "ex_ko": "두 가수는 완벽한 화음으로 노래했다.",
        "mnemonic": "\"하모니카\"의 하모니! 여러 소리가 섞여 어울리는 게 조화, 화음이야."
      },
      {
        "n": 10,
        "en": "wonder",
        "ko": "[동] 궁금하다 / [명] 감탄, 놀라움",
        "ipa": "/ˈwʌndər/",
        "stress": "WON-der",
        "emoji": "🤔❓",
        "ex": "I wonder why she didn't come today.",
        "ex_ko": "걔가 오늘 왜 안 왔는지 궁금해.",
        "mnemonic": "\"원더\"풀! 놀라운 걸 보면 \"왜지?\" 하고 궁금해지지."
      },
      {
        "n": 11,
        "en": "able",
        "ko": "[형] 1. …할 수 있는 2. 능력 있는, 유능한",
        "ipa": "/ˈeɪbl/",
        "stress": "A-ble",
        "emoji": "💪✅",
        "ex": "I'm able to finish this homework tonight.",
        "ex_ko": "나 오늘 밤에 이 숙제 끝낼 수 있어.",
        "mnemonic": "\"에이, 불~\" 껐어! 불도 끌 수 있는 능력자. …할 수 있다."
      },
      {
        "n": 12,
        "en": "pain",
        "ko": "[명] (육체적, 정신적) 통증, 고통",
        "ipa": "/peɪn/",
        "stress": "PAIN",
        "emoji": "🤕😣",
        "ex": "I felt a sharp pain in my leg.",
        "ex_ko": "다리에 날카로운 통증이 느껴졌어.",
        "mnemonic": "\"페인\"트 통이 발등에 쿵! 아픈 통증이 확 오지."
      },
      {
        "n": 13,
        "en": "uniform",
        "ko": "[명] 제복, 유니폼 / [형] 균일한, 일정한",
        "ipa": "/ˈjuːnɪfɔːrm/",
        "stress": "U-ni-form",
        "emoji": "👔🎽",
        "ex": "We have to wear a school uniform every day.",
        "ex_ko": "우리는 매일 교복을 입어야 해.",
        "mnemonic": "uni(하나)+form(모양). 다 같은 하나의 모양으로 입는 옷이 제복."
      },
      {
        "n": 14,
        "en": "beauty",
        "ko": "[명] 1. 아름다움, 미 2. 미인",
        "ipa": "/ˈbjuːti/",
        "stress": "BEAU-ty",
        "emoji": "🌸✨",
        "ex": "We stopped to enjoy the beauty of the sunset.",
        "ex_ko": "우리는 노을의 아름다움을 즐기려고 멈췄어.",
        "mnemonic": "\"뷰티\"숍은 아름다움을 만드는 곳! 그대로 아름다움, 미."
      },
      {
        "n": 15,
        "en": "taste",
        "ko": "[명] 맛 / [동] 1. 맛이 나다 2. 맛보다",
        "ipa": "/teɪst/",
        "stress": "TASTE",
        "emoji": "👅🍜",
        "ex": "This soup tastes a little too salty.",
        "ex_ko": "이 국은 좀 너무 짠 맛이 나.",
        "mnemonic": "\"테이스트\"—떼서 입에 스윽! 맛보다, 맛이 나다."
      },
      {
        "n": 16,
        "en": "without",
        "ko": "[전] 1. … 없이 2. …하지 않고",
        "ipa": "/wɪˈðaʊt/",
        "stress": "with-OUT",
        "emoji": "🚫🥤",
        "ex": "I can't study without my phone nearby.",
        "ex_ko": "나는 폰이 옆에 없으면 공부를 못 해.",
        "mnemonic": "with(함께)에서 out(밖으로) 나가버림. 그래서 \"… 없이\"."
      },
      {
        "n": 17,
        "en": "sunlight",
        "ko": "[명] 햇빛, 햇살",
        "ipa": "/ˈsʌnˌlaɪt/",
        "stress": "SUN-light",
        "emoji": "☀️🌤️",
        "ex": "Open the curtains and let the sunlight in.",
        "ex_ko": "커튼 열고 햇빛 좀 들어오게 해.",
        "mnemonic": "sun(태양) + light(빛) = 햇빛. 두 쉬운 단어를 그냥 붙인 말이에요."
      },
      {
        "n": 18,
        "en": "exact",
        "ko": "[형] 정확한",
        "ipa": "/ɪɡˈzækt/",
        "stress": "ex-ACT",
        "emoji": "🎯📏",
        "ex": "Tell me the exact time of the movie.",
        "ex_ko": "영화 시작하는 정확한 시간을 말해 줘.",
        "mnemonic": "\"이그잭!\" 자를 딱 대고 잰 듯 정확한. 뒤에 액트(ACT)에 힘줘서 읽어요."
      },
      {
        "n": 19,
        "en": "popular",
        "ko": "[형] 1. 인기 있는 2. 대중의, 대중적인",
        "ipa": "/ˈpɑːpjələr/",
        "stress": "PO-pu-lar",
        "emoji": "⭐🙌",
        "ex": "That song is really popular at our school.",
        "ex_ko": "그 노래 우리 학교에서 진짜 인기 많아.",
        "mnemonic": "people(사람들)과 뿌리가 같아요. 사람들이 다 좋아하니까 인기 있는."
      },
      {
        "n": 20,
        "en": "noisy",
        "ko": "[형] 떠들썩한, 시끄러운",
        "ipa": "/ˈnɔɪzi/",
        "stress": "NOI-sy",
        "emoji": "📢🔊",
        "ex": "The classroom is too noisy to study.",
        "ex_ko": "교실이 공부하기엔 너무 시끄러워.",
        "mnemonic": "noise(소음)에 -y 붙이면 시끄러운. \"노이지\"하면 귀 아픈 소리 떠올려요."
      },
      {
        "n": 21,
        "en": "pill",
        "ko": "[명] 알약, 정제",
        "ipa": "/pɪl/",
        "stress": "PILL",
        "emoji": "💊",
        "ex": "Take this pill after you eat lunch.",
        "ex_ko": "점심 먹고 나서 이 알약 먹어.",
        "mnemonic": "\"필\"수로 먹어야 하는 알약! 삼킬 때 \"삐~ㄹ\" 넘어가는 느낌."
      },
      {
        "n": 22,
        "en": "be in trouble",
        "ko": "어려움[곤경]에 처하다",
        "ipa": "/bi ɪn ˈtrʌbəl/",
        "stress": "be in TROU-ble",
        "emoji": "😰⚠️",
        "ex": "I'll be in trouble if I'm late again.",
        "ex_ko": "또 늦으면 나 곤란해질 거야.",
        "mnemonic": "trouble(문제) 안에(in) 들어가 있다 = 곤경에 처하다."
      },
      {
        "n": 23,
        "en": "think up",
        "ko": "…을 생각해내다",
        "ipa": "/ˌθɪŋk ˈʌp/",
        "stress": "think UP",
        "emoji": "💡🤔",
        "ex": "Let's think up a good name for our team.",
        "ex_ko": "우리 팀 이름 좋은 걸로 하나 생각해 내자.",
        "mnemonic": "생각(think)을 머리 위로(up) 쑥 끌어올리다 = 생각해내다."
      },
      {
        "n": 24,
        "en": "be famous for",
        "ko": "…로 유명하다",
        "ipa": "/bi ˈfeɪməs fɔːr/",
        "stress": "be FA-mous for",
        "emoji": "🏅🍜",
        "ex": "This town is famous for its fried chicken.",
        "ex_ko": "이 동네는 치킨으로 유명해.",
        "mnemonic": "famous(유명한) 뒤에 for는 \"~때문에\". 무엇 때문에 유명한지 알려줘요."
      }
    ]
  },
  {
    "pack_id": "neungyul-voca-middle-2025-day04",
    "title": "능률VOCA 중등 필수 [2025] DAY 04",
    "source": "프렙업 영어학원 프린트 (PAGE 4/50)",
    "words": [
      {
        "n": 1,
        "en": "female",
        "ko": "[형] 여성[암컷]의 / [명] 여성, 암컷",
        "ipa": "/ˈfiːmeɪl/",
        "stress": "FE-male",
        "emoji": "👩♀️",
        "ex": "The female lion hunts for the whole group.",
        "ex_ko": "암사자가 무리 전체를 위해 사냥해요.",
        "mnemonic": "fe(피메일)는 male(남성) 앞에 fe가 붙은 것. male이 아닌 쪽, 즉 여성이에요."
      },
      {
        "n": 2,
        "en": "regular",
        "ko": "[형] 1. 정기적인, 규칙적인 2. (크기가) 보통의, 표준적인",
        "ipa": "/ˈreɡjələr/",
        "stress": "RE-gu-lar",
        "emoji": "📅⏰",
        "ex": "I have a regular meeting every Monday morning.",
        "ex_ko": "저는 매주 월요일 아침에 정기 회의가 있어요.",
        "mnemonic": "\"레귤러 사이즈\" 하면 보통 크기죠. 늘 똑같은 게 regular예요."
      },
      {
        "n": 3,
        "en": "coin",
        "ko": "[명] 동전",
        "ipa": "/kɔɪn/",
        "stress": "COIN",
        "emoji": "🪙",
        "ex": "I found an old coin under my bed.",
        "ex_ko": "침대 밑에서 오래된 동전을 하나 찾았어요.",
        "mnemonic": "\"코인 노래방\"의 그 코인! 동전 넣고 노래 부르죠."
      },
      {
        "n": 4,
        "en": "prepare",
        "ko": "[동] 1. 준비하다 2. (음식을) 준비[마련]하다",
        "ipa": "/prɪˈper/",
        "stress": "pre-PARE",
        "emoji": "🍳📝",
        "ex": "I need to prepare for tomorrow's math test.",
        "ex_ko": "내일 수학 시험을 준비해야 해요.",
        "mnemonic": "pre(미리) + pare(다듬다). 미리 다듬어 두는 게 준비예요."
      },
      {
        "n": 5,
        "en": "quite",
        "ko": "[부] 꽤, 상당히",
        "ipa": "/kwaɪt/",
        "stress": "QUITE",
        "emoji": "👍📈",
        "ex": "This soup is quite spicy for me.",
        "ex_ko": "이 국은 저한테 꽤 매워요.",
        "mnemonic": "\"콰이트!\" 하고 감탄할 만큼 꽤 대단하다고 외워요."
      },
      {
        "n": 6,
        "en": "alike",
        "ko": "[형] 비슷한 / [부] 비슷하게, 마찬가지로",
        "ipa": "/əˈlaɪk/",
        "stress": "a-LIKE",
        "emoji": "👯👀",
        "ex": "My sister and I look very much alike.",
        "ex_ko": "언니랑 저는 정말 많이 닮았어요.",
        "mnemonic": "a + like(~같은). 서로 '같은' 모습이니까 비슷한 거예요."
      },
      {
        "n": 7,
        "en": "alarm",
        "ko": "[명] 1. 경보(기) 2. 자명종, 알람",
        "ipa": "/əˈlɑːrm/",
        "stress": "a-LARM",
        "emoji": "⏰🚨",
        "ex": "My alarm didn't ring, so I was late.",
        "ex_ko": "알람이 안 울려서 지각했어요.",
        "mnemonic": "\"알람\" 그대로예요. 시끄럽게 울려서 위험도 알리는 경보."
      },
      {
        "n": 8,
        "en": "bored",
        "ko": "[형] 지루해하는",
        "ipa": "/bɔːrd/",
        "stress": "BORED",
        "emoji": "😑🥱",
        "ex": "I'm so bored on rainy weekends at home.",
        "ex_ko": "비 오는 주말에 집에 있으면 너무 지루해요.",
        "mnemonic": "\"보드\"게임도 없이 혼자 있으면 지루하죠. 보얼드=지루한."
      },
      {
        "n": 9,
        "en": "freeze",
        "ko": "[동] 얼다, 얼리다, 냉동하다",
        "ipa": "/friːz/",
        "stress": "FREEZE",
        "emoji": "🧊❄️",
        "ex": "The water in the bottle will freeze tonight.",
        "ex_ko": "병 속의 물이 오늘 밤 얼 거야.",
        "mnemonic": "'프리즈!'하고 외치면 그 자리에서 얼어붙죠. 얼음처럼 굳는 게 freeze예요."
      },
      {
        "n": 10,
        "en": "language",
        "ko": "[명] 언어, 말",
        "ipa": "/ˈlæŋɡwɪdʒ/",
        "stress": "LAN-guage",
        "emoji": "🗣️💬🌍",
        "ex": "How many languages can you speak?",
        "ex_ko": "너는 몇 개 언어를 말할 수 있어?",
        "mnemonic": "'랭귀지'는 혀(라틴어 lingua=혀)에서 왔어요. 혀로 하는 것이 언어죠."
      },
      {
        "n": 11,
        "en": "nobody",
        "ko": "[대] 아무도 … 않다, 아무도 없다",
        "ipa": "/ˈnoʊbɑːdi/",
        "stress": "NO-bod-y",
        "emoji": "🚫👤",
        "ex": "Nobody was home when I got back.",
        "ex_ko": "내가 돌아왔을 때 아무도 집에 없었어.",
        "mnemonic": "no(없다) + body(몸). 몸이 하나도 없으니 '아무도 없다'예요."
      },
      {
        "n": 12,
        "en": "teenager",
        "ko": "[명] 십 대",
        "ipa": "/ˈtiːneɪdʒər/",
        "stress": "TEEN-ag-er",
        "emoji": "🧑‍🎓📱",
        "ex": "Most teenagers love listening to music.",
        "ex_ko": "대부분의 십 대는 음악 듣는 걸 좋아해.",
        "mnemonic": "thirTEEN~nineTEEN, 끝이 teen인 나이(13~19살)가 바로 teenager예요."
      },
      {
        "n": 13,
        "en": "chance",
        "ko": "[명] 1. 가능성 2. 기회 3. 우연",
        "ipa": "/tʃæns/",
        "stress": "CHANCE",
        "emoji": "🎲🍀",
        "ex": "Give me one more chance, please.",
        "ex_ko": "나에게 한 번만 더 기회를 줘.",
        "mnemonic": "'찬스!'라고 외칠 때를 떠올려요. 딱 찾아온 기회, 가능성이 chance."
      },
      {
        "n": 14,
        "en": "curl",
        "ko": "[동] 곱슬곱슬하다, 곱슬곱슬하게 하다 / [명] 곱슬머리",
        "ipa": "/kɜːrl/",
        "stress": "CURL",
        "emoji": "🌀💇",
        "ex": "She curls her hair before every party.",
        "ex_ko": "그녀는 파티마다 머리를 곱슬곱슬하게 말아.",
        "mnemonic": "'컬 파마'할 때 그 컬! 머리카락이 동그랗게 말리는 게 curl이에요."
      },
      {
        "n": 15,
        "en": "planet",
        "ko": "[명] 행성",
        "ipa": "/ˈplænɪt/",
        "stress": "PLAN-et",
        "emoji": "🪐🌍",
        "ex": "Mars is the fourth planet from the sun.",
        "ex_ko": "화성은 태양에서 네 번째 행성이야.",
        "mnemonic": "'플라넷'—우주에 넷(net)처럼 퍼진 별들. 태양 둘레를 도는 행성이에요."
      },
      {
        "n": 16,
        "en": "deaf",
        "ko": "[형] 귀가 먹은, 청각 장애가 있는",
        "ipa": "/def/",
        "stress": "DEAF",
        "emoji": "🦻🚫👂",
        "ex": "My grandfather is deaf in one ear.",
        "ex_ko": "우리 할아버지는 한쪽 귀가 안 들리셔.",
        "mnemonic": "'데프'—소리가 덮여서 안 들려요. 귀가 막힌 상태가 deaf예요."
      },
      {
        "n": 17,
        "en": "invent",
        "ko": "[동] 발명하다",
        "ipa": "/ɪnˈvent/",
        "stress": "in-VENT",
        "emoji": "💡🔧",
        "ex": "He wants to invent a robot that cleans rooms.",
        "ex_ko": "그는 방을 청소하는 로봇을 발명하고 싶어 해.",
        "mnemonic": "'인(in) 벤트(vent, 통풍구)'를 처음 뚫은 사람이 발명가! 안쪽에 새 길을 내는 게 발명이야."
      },
      {
        "n": 18,
        "en": "soil",
        "ko": "[명] 흙, 토양",
        "ipa": "/sɔɪl/",
        "stress": "SOIL",
        "emoji": "🌱🟤",
        "ex": "This soil is good for growing tomatoes.",
        "ex_ko": "이 흙은 토마토 키우기에 좋아.",
        "mnemonic": "'쏘일까?' 하고 흙에 씨앗을 쏘아 심는 장면. 씨를 쏘는 곳이 흙이야."
      },
      {
        "n": 19,
        "en": "noodle",
        "ko": "[명] 국수",
        "ipa": "/ˈnuːdl/",
        "stress": "NOO-dle",
        "emoji": "🍜🥢",
        "ex": "I ate a big bowl of noodles for lunch.",
        "ex_ko": "나 점심으로 국수 한 그릇 크게 먹었어.",
        "mnemonic": "'누들누들' 늘어지는 면발. 소리가 그대로 국수의 흐물흐물한 모습이야."
      },
      {
        "n": 20,
        "en": "stair",
        "ko": "[명] 계단",
        "ipa": "/ster/",
        "stress": "STAIR",
        "emoji": "🪜🚶",
        "ex": "She ran up the stairs to her room.",
        "ex_ko": "그 애는 자기 방으로 계단을 뛰어 올라갔어.",
        "mnemonic": "'스테어'는 '스타(star)처럼 위로' 올라가는 계단. 한 칸씩 별을 향해 올라가."
      },
      {
        "n": 21,
        "en": "comedy",
        "ko": "[명] 코미디, 희극",
        "ipa": "/ˈkɑːmədi/",
        "stress": "CO-me-dy",
        "emoji": "😂🎭",
        "ex": "We watched a funny comedy movie last night.",
        "ex_ko": "우리 어젯밤에 웃긴 코미디 영화 봤어.",
        "mnemonic": "'코미디'는 그대로 코미디! 코가 미친 듯이 웃겨 벌렁거리는 장면을 떠올려."
      },
      {
        "n": 22,
        "en": "calm down",
        "ko": "진정하다, …을 진정시키다",
        "ipa": "/kɑːm daʊn/",
        "stress": "CALM down",
        "emoji": "😮‍💨🧘",
        "ex": "Calm down and tell me what happened.",
        "ex_ko": "진정하고 무슨 일이 있었는지 말해 봐.",
        "mnemonic": "'캄(calm) 다운' — 화가 위로 솟았다가 아래(down)로 내려앉는 그림. 열이 내려가면 진정."
      },
      {
        "n": 23,
        "en": "take care",
        "ko": "조심하다",
        "ipa": "/teɪk ker/",
        "stress": "take CARE",
        "emoji": "🤗⚠️",
        "ex": "Take care when you cross the street.",
        "ex_ko": "길 건널 때 조심해.",
        "mnemonic": "'케어(care, 돌봄)를 챙겨(take) 간다' — 자기를 돌볼 마음을 챙기니 조심하게 돼."
      },
      {
        "n": 24,
        "en": "because of",
        "ko": "… 때문에",
        "ipa": "/bɪˈkɔːz əv/",
        "stress": "be CAUSE of",
        "emoji": "➡️🌧️",
        "ex": "We stayed home because of the rain.",
        "ex_ko": "우리는 비 때문에 집에 있었어.",
        "mnemonic": "because 안에 'cause(원인)'가 들어 있어. '원인이 되는 것' 때문에! 뒤엔 명사가 와."
      }
    ]
  },
  {
    "pack_id": "neungyul-voca-middle-2025-day05",
    "title": "능률VOCA 중등 필수 [2025] DAY 05",
    "source": "프렙업 영어학원 프린트 (PAGE 5/50)",
    "words": [
      {
        "n": 1,
        "en": "repair",
        "ko": "[동] 고치다, 수리하다 / [명] 수리, 보수",
        "ipa": "/rɪˈper/",
        "stress": "re-PAIR",
        "emoji": "🔧🛠️",
        "ex": "My dad will repair my broken bike today.",
        "ex_ko": "아빠가 오늘 내 고장 난 자전거를 고쳐 주실 거야.",
        "mnemonic": "'리페어' — 페어(pair, 짝)를 다시(re) 맞춘다. 망가진 걸 원래 짝처럼 되돌리는 게 수리."
      },
      {
        "n": 2,
        "en": "instant",
        "ko": "[형] 1. 즉각적인, 당장의 2. 즉석의, 인스턴트의 / [명] 순간",
        "ipa": "/ˈɪnstənt/",
        "stress": "IN-stant",
        "emoji": "⚡🍜",
        "ex": "I made instant noodles for a quick snack.",
        "ex_ko": "간단히 먹으려고 인스턴트 라면을 끓였어.",
        "mnemonic": "인스턴트 라면! 3분이면 바로 나오는 즉석. 그래서 '즉각적인, 순간'."
      },
      {
        "n": 3,
        "en": "advise",
        "ko": "[동] 충고하다, 조언하다",
        "ipa": "/ədˈvaɪz/",
        "stress": "ad-VISE",
        "emoji": "💬🧑‍🏫",
        "ex": "My teacher advised me to study every day.",
        "ex_ko": "선생님이 나에게 매일 공부하라고 조언하셨어.",
        "mnemonic": "ad(~에게) + vise(wise, 지혜). 지혜를 건네주는 게 충고·조언이에요."
      },
      {
        "n": 4,
        "en": "totally",
        "ko": "[부] 완전히, 전적으로",
        "ipa": "/ˈtoʊtəli/",
        "stress": "TO-tal-ly",
        "emoji": "💯🙌",
        "ex": "I totally forgot about the math test.",
        "ex_ko": "나 수학 시험을 완전히 까먹었어.",
        "mnemonic": "토탈(total, 전체)에 -ly가 붙어 '전체적으로 = 완전히'. 토탈 합계니까 하나도 안 빼고."
      },
      {
        "n": 5,
        "en": "freezing",
        "ko": "[형] 몹시 추운[차가운]",
        "ipa": "/ˈfriːzɪŋ/",
        "stress": "FREE-zing",
        "emoji": "🥶❄️",
        "ex": "It's freezing outside, so wear your coat.",
        "ex_ko": "밖이 엄청 추우니까 코트 입어.",
        "mnemonic": "'프리징' — 프리저(냉동실) 안처럼 꽁꽁 어는 추위. freeze(얼다)+ing."
      },
      {
        "n": 6,
        "en": "blank",
        "ko": "[형] 공백의, 빈 / [명] 빈칸, 공란",
        "ipa": "/blæŋk/",
        "stress": "BLANK",
        "emoji": "📄⬜",
        "ex": "Please fill in the blank with a word.",
        "ex_ko": "빈칸에 단어를 채워 넣으세요.",
        "mnemonic": "'블랭크' — 시험지 빈칸 보면 머리가 '블랭!' 하고 하얘진다. 그게 공백."
      },
      {
        "n": 7,
        "en": "important",
        "ko": "[형] 중요한",
        "ipa": "/ɪmˈpɔːrtnt/",
        "stress": "im-POR-tant",
        "emoji": "⭐❗",
        "ex": "This test is very important for my grade.",
        "ex_ko": "이 시험은 내 성적에 아주 중요해.",
        "mnemonic": "항구(port)로 안으로(im) 들여오는 물건은 귀한 것. 수입할 만큼 값진 = 중요한."
      },
      {
        "n": 8,
        "en": "teen",
        "ko": "[명] 십 대 / [형] 십 대의",
        "ipa": "/tiːn/",
        "stress": "TEEN",
        "emoji": "🧑‍🎤🎒",
        "ex": "Many teens love listening to K-pop music.",
        "ex_ko": "많은 십 대들이 케이팝 음악 듣는 걸 좋아해.",
        "mnemonic": "thirTEEN(13)부터 nineTEEN(19)까지 뒤에 붙는 -teen. 그 나이대가 바로 십 대."
      },
      {
        "n": 9,
        "en": "weigh",
        "ko": "[동] 1. 무게가 …이다 2. 무게를 재다[달다]",
        "ipa": "/weɪ/",
        "stress": "WEIGH",
        "emoji": "⚖️",
        "ex": "How much does your backpack weigh?",
        "ex_ko": "네 가방 무게가 얼마나 나가?",
        "mnemonic": "\"웨이\" 하고 저울 위에 올리면 무게가 나온다. 헬스장 웨이트(weight)도 같은 뿌리."
      },
      {
        "n": 10,
        "en": "regularly",
        "ko": "[부] 정기적으로, 규칙적으로",
        "ipa": "/ˈreɡjələrli/",
        "stress": "RE-gu-lar-ly",
        "emoji": "📅⏰",
        "ex": "I exercise regularly after school.",
        "ex_ko": "나는 방과 후에 규칙적으로 운동해.",
        "mnemonic": "규칙(rule)을 뜻하는 regular에 -ly가 붙어 '규칙적으로'. 달력에 동그라미 치듯 정기적으로."
      },
      {
        "n": 11,
        "en": "law",
        "ko": "[명] 법, 법률",
        "ipa": "/lɔː/",
        "stress": "LAW",
        "emoji": "⚖️📜",
        "ex": "Everyone must follow the law.",
        "ex_ko": "모두가 법을 지켜야 해.",
        "mnemonic": "\"로\"—법대를 '로스쿨(law school)'이라고 하지. 로스쿨 = 법 배우는 학교."
      },
      {
        "n": 12,
        "en": "rub",
        "ko": "[동] 비비다, 문지르다",
        "ipa": "/rʌb/",
        "stress": "RUB",
        "emoji": "🤲✨",
        "ex": "She rubbed her eyes and yawned.",
        "ex_ko": "그녀는 눈을 비비며 하품했어.",
        "mnemonic": "\"럽\" 하고 손을 문지르면 러브(love) 하트가 나올 것 같다. 램프를 rub하면 지니 등장."
      },
      {
        "n": 13,
        "en": "pour",
        "ko": "[동] 1. 붓다, 따르다 2. (비가) 쏟아지다, 퍼붓다",
        "ipa": "/pɔːr/",
        "stress": "POUR",
        "emoji": "🫗🌧️",
        "ex": "Can you pour me some water?",
        "ex_ko": "물 좀 따라 줄래?",
        "mnemonic": "\"포~\" 하고 물줄기가 쏟아진다. 비가 퍼부을 때도 pour."
      },
      {
        "n": 14,
        "en": "yet",
        "ko": "[부] 1. [부정문] 아직 2. [의문문] 벌써",
        "ipa": "/jet/",
        "stress": "YET",
        "emoji": "⏳❓",
        "ex": "I haven't finished my homework yet.",
        "ex_ko": "나 아직 숙제 다 못 끝냈어.",
        "mnemonic": "\"옛?\"—아직 안 했냐고 물을 때 쓰는 말. 부정문엔 '아직', 의문문엔 '벌써'."
      },
      {
        "n": 15,
        "en": "skill",
        "ko": "[명] 1. 기량, 솜씨 2. 기술",
        "ipa": "/skɪl/",
        "stress": "SKILL",
        "emoji": "🎯🛠️",
        "ex": "Cooking is a useful skill to have.",
        "ex_ko": "요리는 갖고 있으면 유용한 기술이야.",
        "mnemonic": "게임에서 '스킬 쓴다'고 하지. 스킬 = 갈고닦은 솜씨·기술."
      },
      {
        "n": 16,
        "en": "neat",
        "ko": "[형] 정돈된, 단정한",
        "ipa": "/niːt/",
        "stress": "NEAT",
        "emoji": "🧹📚",
        "ex": "Your room looks really neat today.",
        "ex_ko": "네 방 오늘 정말 깔끔해 보인다.",
        "mnemonic": "\"니트\" 스웨터를 곱게 개어 놓은 모습. 반듯하고 단정한 상태가 neat."
      },
      {
        "n": 17,
        "en": "ache",
        "ko": "[동] 아프다, 쑤시다 / [명] 아픔, 통증",
        "ipa": "/eɪk/",
        "stress": "ACHE",
        "emoji": "🤕😣",
        "ex": "My legs ache after playing soccer all day.",
        "ex_ko": "하루 종일 축구하고 나니 다리가 쑤셔요.",
        "mnemonic": "'에이크(에이 크다!)' 하고 아파서 소리치는 모습. 몸이 쑤실 때 나는 신음이에요."
      },
      {
        "n": 18,
        "en": "patient",
        "ko": "[명] 환자 / [형] 인내심[참을성] 있는",
        "ipa": "/ˈpeɪʃənt/",
        "stress": "PA-tient",
        "emoji": "🏥🧑‍⚕️😌",
        "ex": "The doctor is very patient with young patients.",
        "ex_ko": "그 의사 선생님은 어린 환자들에게 아주 인내심이 많아요.",
        "mnemonic": "'페이션트'는 아파도 참는 사람. 참는 사람이 곧 '환자'이자 '참을성 있는' 이에요."
      },
      {
        "n": 19,
        "en": "elderly",
        "ko": "[형] 나이가 지긋한, 연세가 드신",
        "ipa": "/ˈeldərli/",
        "stress": "EL-der-ly",
        "emoji": "👴👵",
        "ex": "An elderly man sat next to me on the bus.",
        "ex_ko": "버스에서 나이 지긋한 할아버지가 제 옆에 앉으셨어요.",
        "mnemonic": "elder(연장자) + ly. '엘더'는 나보다 오래 산 어른, 그래서 연세 드신."
      },
      {
        "n": 20,
        "en": "wipe",
        "ko": "[동] 닦다, 훔치다",
        "ipa": "/waɪp/",
        "stress": "WIPE",
        "emoji": "🧽🧻",
        "ex": "Please wipe the table before we eat.",
        "ex_ko": "밥 먹기 전에 식탁 좀 닦아 줘.",
        "mnemonic": "'와입~' 하고 물티슈로 쓱 닦는 소리. 와이퍼가 유리창 닦는 거 생각하면 돼요."
      },
      {
        "n": 21,
        "en": "punch",
        "ko": "[동] 1. 주먹으로 치다[때리다] 2. 구멍을 뚫다",
        "ipa": "/pʌntʃ/",
        "stress": "PUNCH",
        "emoji": "👊🥊",
        "ex": "He tried to punch the wall in anger.",
        "ex_ko": "그는 화가 나서 벽을 주먹으로 치려고 했어요.",
        "mnemonic": "'펀치!' 주먹으로 퍽 때리기. 펀치로 종이에 구멍 뚫는 것도 같은 단어예요."
      },
      {
        "n": 22,
        "en": "take out",
        "ko": "1. …을 꺼내다 2. …을 데리고 나가다",
        "ipa": "/teɪk aʊt/",
        "stress": "TAKE out",
        "emoji": "🎒📤🐕",
        "ex": "Take out your notebook and write your name.",
        "ex_ko": "공책을 꺼내서 이름을 쓰세요.",
        "mnemonic": "take(가지다) + out(밖으로) = 밖으로 가지고 나오다, 즉 꺼내다."
      },
      {
        "n": 23,
        "en": "get out of",
        "ko": "1. (장소)에서 나가다 2. (차)에서 내리다",
        "ipa": "/ɡet aʊt əv/",
        "stress": "GET out of",
        "emoji": "🚗🚪🚶",
        "ex": "Get out of the car and close the door.",
        "ex_ko": "차에서 내려서 문을 닫아.",
        "mnemonic": "get(움직이다) + out of(~밖으로) = ~에서 빠져나오다, 차에서 내리다."
      },
      {
        "n": 24,
        "en": "plenty of",
        "ko": "많은, 충분한",
        "ipa": "/ˈplenti əv/",
        "stress": "PLEN-ty of",
        "emoji": "🍎🍎🍎",
        "ex": "We have plenty of time before the movie starts.",
        "ex_ko": "영화 시작 전까지 시간이 충분히 많아요.",
        "mnemonic": "'플렌티'는 full(가득)과 뿌리가 같아요. 넘칠 만큼 많고 충분한 것."
      }
    ]
  },
  {
    "pack_id": "neungyul-voca-middle-2025-day06",
    "title": "능률VOCA 중등 필수 [2025] DAY 06",
    "source": "프렙업 영어학원 프린트 (PAGE 6/50)",
    "words": [
      {
        "n": 1,
        "en": "mistake",
        "ko": "[명] 실수, 잘못",
        "ipa": "/mɪˈsteɪk/",
        "stress": "mis-TAKE",
        "emoji": "❌📝",
        "ex": "Sorry, I made a mistake on question five.",
        "ex_ko": "미안해, 나 5번 문제에서 실수했어.",
        "mnemonic": "mis(잘못)+take(잡다) — 잘못 집어 들면 실수! '미스테이크'는 미스(miss)한 것."
      },
      {
        "n": 2,
        "en": "flour",
        "ko": "[명] 밀가루",
        "ipa": "/ˈflaʊər/",
        "stress": "FLOUR",
        "emoji": "🌾🥣",
        "ex": "We need more flour to make the cookies.",
        "ex_ko": "쿠키를 만들려면 밀가루가 더 필요해.",
        "mnemonic": "발음이 flower(꽃)와 똑같아요. '밀가루를 뿌리니 하얀 꽃가루 같다'로 기억!"
      },
      {
        "n": 3,
        "en": "lawyer",
        "ko": "[명] 변호사",
        "ipa": "/ˈlɔɪər/",
        "stress": "LAW-yer",
        "emoji": "⚖️👨‍💼",
        "ex": "My uncle is a lawyer at a big company.",
        "ex_ko": "우리 삼촌은 큰 회사의 변호사야.",
        "mnemonic": "law(법)+er(사람) — 법을 다루는 사람이 변호사예요."
      },
      {
        "n": 4,
        "en": "tire",
        "ko": "[동] 지치다, 지치게 하다 / [명] (자동차 등의) 타이어",
        "ipa": "/ˈtaɪər/",
        "stress": "TIRE",
        "emoji": "🛞😩",
        "ex": "Long walks always tire my little brother.",
        "ex_ko": "오래 걸으면 항상 내 남동생은 지쳐.",
        "mnemonic": "'타이어'가 닳아서 힘 빠지듯, 사람도 tire하면 지쳐요."
      },
      {
        "n": 5,
        "en": "channel",
        "ko": "[명] (TV 등의) 채널",
        "ipa": "/ˈtʃænəl/",
        "stress": "CHAN-nel",
        "emoji": "📺🔢",
        "ex": "Can you change the channel to the news?",
        "ex_ko": "채널을 뉴스로 바꿔 줄래?",
        "mnemonic": "'채널'이라고 그대로 읽어요. TV 채널은 물길처럼 방송이 흘러오는 통로!"
      },
      {
        "n": 6,
        "en": "soldier",
        "ko": "[명] 군인, 병사",
        "ipa": "/ˈsoʊldʒər/",
        "stress": "SOL-dier",
        "emoji": "🪖🎖️",
        "ex": "My grandfather was a soldier for ten years.",
        "ex_ko": "우리 할아버지는 10년 동안 군인이셨어.",
        "mnemonic": "'솔저' — 솔(sol) 하고 총 쏘는 사람. 군인은 나라를 지켜요."
      },
      {
        "n": 7,
        "en": "recipe",
        "ko": "[명] 요리법, 레시피",
        "ipa": "/ˈresəpi/",
        "stress": "RE-ci-pe",
        "emoji": "📖🍳",
        "ex": "This recipe for pancakes is really easy.",
        "ex_ko": "이 팬케이크 요리법은 정말 쉬워.",
        "mnemonic": "'레시피'라고 읽어요. '레서피 → 레시피' 끝을 '파이'로 읽지 않게 조심!"
      },
      {
        "n": 8,
        "en": "wallet",
        "ko": "[명] 지갑",
        "ipa": "/ˈwɑlət/",
        "stress": "WAL-let",
        "emoji": "👛💳",
        "ex": "I left my wallet at home this morning.",
        "ex_ko": "나 오늘 아침에 지갑을 집에 두고 왔어.",
        "mnemonic": "'왈렛' — '왈! 돈이 다 나갔네' 하고 놀라는 지갑으로 기억!"
      },
      {
        "n": 9,
        "en": "silent",
        "ko": "[형] 1. 말이 없는, 침묵하는 2. 조용한, 고요한",
        "ipa": "/ˈsaɪlənt/",
        "stress": "SI-lent",
        "emoji": "🤫🔇",
        "ex": "Everyone was silent during the test.",
        "ex_ko": "시험 보는 동안 모두가 조용했어.",
        "mnemonic": "\"사일런트 모드\" 하면 폰이 소리 안 나죠. 말없이 조용한 상태예요."
      },
      {
        "n": 10,
        "en": "rail",
        "ko": "[명] 1. (철도의) 레일 2. 철도, 기차",
        "ipa": "/reɪl/",
        "stress": "RAIL",
        "emoji": "🛤️🚆",
        "ex": "Don't stand too close to the rail.",
        "ex_ko": "레일에 너무 가까이 서 있지 마.",
        "mnemonic": "\"레일\"은 우리도 그대로 써요. 기차가 달리는 두 줄 철길!"
      },
      {
        "n": 11,
        "en": "adult",
        "ko": "[명] 성인, 어른 / [형] 성인의, 다 자란",
        "ipa": "/əˈdʌlt/",
        "stress": "a-DULT",
        "emoji": "🧑👔",
        "ex": "You can drive when you become an adult.",
        "ex_ko": "어른이 되면 운전할 수 있어.",
        "mnemonic": "\"어덜트\" → \"어른\"! 소리가 비슷해서 바로 외워져요."
      },
      {
        "n": 12,
        "en": "tasty",
        "ko": "[형] 맛있는",
        "ipa": "/ˈteɪsti/",
        "stress": "TAS-ty",
        "emoji": "😋🍕",
        "ex": "This pizza is really tasty!",
        "ex_ko": "이 피자 진짜 맛있다!",
        "mnemonic": "taste(맛) + y = 맛이 있는, 맛있는."
      },
      {
        "n": 13,
        "en": "couple",
        "ko": "[명] 1. 한 쌍, 두 개 2. 부부, 커플",
        "ipa": "/ˈkʌpəl/",
        "stress": "COU-ple",
        "emoji": "👫2️⃣",
        "ex": "I need a couple of minutes to finish.",
        "ex_ko": "끝내려면 몇 분만 더 필요해.",
        "mnemonic": "\"커플\"은 둘이 한 쌍! 그래서 \"두 개, 한 쌍\"이란 뜻이에요."
      },
      {
        "n": 14,
        "en": "especially",
        "ko": "[부] 1. 특히 2. 특별히, 각별히",
        "ipa": "/ɪˈspeʃəli/",
        "stress": "es-PE-cial-ly",
        "emoji": "⭐👉",
        "ex": "I love fruit, especially strawberries.",
        "ex_ko": "난 과일 좋아해, 특히 딸기.",
        "mnemonic": "special(특별한) + ly = 특별하게, 특히."
      },
      {
        "n": 15,
        "en": "soap",
        "ko": "[명] 비누",
        "ipa": "/soʊp/",
        "stress": "SOAP",
        "emoji": "🧼🫧",
        "ex": "Wash your hands with soap and water.",
        "ex_ko": "비누랑 물로 손 씻어.",
        "mnemonic": "\"솝\" 하고 손을 문지르면 거품이 뽀글! 비누예요."
      },
      {
        "n": 16,
        "en": "lonely",
        "ko": "[형] 외로운, 쓸쓸한",
        "ipa": "/ˈloʊnli/",
        "stress": "LONE-ly",
        "emoji": "😢🧍",
        "ex": "I feel lonely when my friends are busy.",
        "ex_ko": "친구들이 바쁘면 난 외로워.",
        "mnemonic": "alone(혼자)에서 온 말. 혼자라서 외로운 거예요."
      },
      {
        "n": 17,
        "en": "mind",
        "ko": "[명] 마음, 정신 / [동] 꺼리다, 싫어하다",
        "ipa": "/maɪnd/",
        "stress": "MIND",
        "emoji": "🧠",
        "ex": "Do you mind if I open the window?",
        "ex_ko": "제가 창문 좀 열어도 될까요?",
        "mnemonic": "'마인드'는 마음·정신. 'Do you mind?'는 '마음에 걸려?' 즉 꺼리냐는 뜻이에요."
      },
      {
        "n": 18,
        "en": "curly",
        "ko": "[형] 곱슬곱슬한",
        "ipa": "/ˈkɜːrli/",
        "stress": "CUR-ly",
        "emoji": "🌀💇",
        "ex": "My sister has long curly brown hair.",
        "ex_ko": "우리 언니는 길고 곱슬곱슬한 갈색 머리야.",
        "mnemonic": "'컬리'—머리 '컬(curl)' 넣는다는 말 그대로! 컬이 들어간 머리가 curly."
      },
      {
        "n": 19,
        "en": "opinion",
        "ko": "[명] 의견, 견해",
        "ipa": "/əˈpɪnjən/",
        "stress": "o-PIN-ion",
        "emoji": "💭🗣️",
        "ex": "In my opinion, the movie was too long.",
        "ex_ko": "내 생각엔 그 영화 너무 길었어.",
        "mnemonic": "'어핀연'—핀(pin)을 콕 꽂듯 자기 생각을 딱 찍어 말하는 게 opinion, 의견."
      },
      {
        "n": 20,
        "en": "blend",
        "ko": "[동] 섞이다, 섞다, 혼합하다",
        "ipa": "/blend/",
        "stress": "BLEND",
        "emoji": "🥤🌀",
        "ex": "Blend the milk and bananas for two minutes.",
        "ex_ko": "우유랑 바나나를 2분 동안 섞어.",
        "mnemonic": "'블렌더(blender)'가 뭐 하는 기계? 섞는 기계! blend가 바로 '섞다'."
      },
      {
        "n": 21,
        "en": "mixture",
        "ko": "[명] 혼합(물)",
        "ipa": "/ˈmɪkstʃər/",
        "stress": "MIX-ture",
        "emoji": "🥣🎨",
        "ex": "This drink is a mixture of juice and soda.",
        "ex_ko": "이 음료는 주스와 탄산음료를 섞은 거야.",
        "mnemonic": "mix(섞다) + -ture(명사 꼬리) = 섞은 것, 혼합물. '믹스처'라고 읽어."
      },
      {
        "n": 22,
        "en": "fill in",
        "ko": "1. (빈칸 등)에 기입하다, 써넣다 2. (구멍 등)을 메우다",
        "ipa": "/ˌfɪl ˈɪn/",
        "stress": "fill IN",
        "emoji": "📝✍️",
        "ex": "Please fill in your name and phone number.",
        "ex_ko": "이름이랑 전화번호를 적어 주세요.",
        "mnemonic": "fill(채우다) + in(안에) = 빈칸 '안을 채우다', 즉 써넣다."
      },
      {
        "n": 23,
        "en": "be different from",
        "ko": "…와 다르다",
        "ipa": "/bi ˈdɪfrənt frəm/",
        "stress": "be DIF-fer-ent from",
        "emoji": "🍎🍊↔️",
        "ex": "My school is different from yours.",
        "ex_ko": "우리 학교는 너희 학교랑 달라.",
        "mnemonic": "different(다른) 뒤엔 무조건 from! '~로부터 떨어져 다르다'로 외우면 to랑 안 헷갈려."
      },
      {
        "n": 24,
        "en": "go away",
        "ko": "1. (사람, 장소를) (떠나)가다 2. 집을 떠나다, 어디를 가다 3. 없어지다",
        "ipa": "/ˌɡoʊ əˈweɪ/",
        "stress": "go a-WAY",
        "emoji": "🚶‍♂️💨",
        "ex": "My headache finally went away last night.",
        "ex_ko": "어젯밤에 두통이 드디어 사라졌어.",
        "mnemonic": "go(가다) + away(멀리) = 멀리 가버리다. 사람이면 '떠나다', 아픔이면 '없어지다'."
      }
    ]
  },
  {
    "pack_id": "neungyul-voca-middle-2025-day07",
    "title": "능률VOCA 중등 필수 [2025] DAY 07",
    "source": "프렙업 영어학원 프린트 (PAGE 7/50)",
    "words": [
      {
        "n": 1,
        "en": "share",
        "ko": "[동] 1. 함께 쓰다, 공유하다 2. 나누다",
        "ipa": "/ʃer/",
        "stress": "SHARE",
        "emoji": "🤝🍕",
        "ex": "Can I share your umbrella on the way home?",
        "ex_ko": "집에 가는 길에 네 우산 같이 써도 될까?",
        "mnemonic": "'셰어하우스'는 여러 명이 집을 함께 쓰는 곳. share = 함께 쓰다."
      },
      {
        "n": 2,
        "en": "form",
        "ko": "[명] 1. 종류, 유형, 형태 2. (문서) 서식 / [동] 형성하다, 이루다",
        "ipa": "/fɔrm/",
        "stress": "FORM",
        "emoji": "📝🧱",
        "ex": "Please fill out this form before the class starts.",
        "ex_ko": "수업 시작 전에 이 서식을 작성해 주세요.",
        "mnemonic": "'폼이 좋다'의 폼! 겉모양·형태를 뜻하고, 종이 서식도 정해진 형태라서 form."
      },
      {
        "n": 3,
        "en": "invention",
        "ko": "[명] 발명(품)",
        "ipa": "/ɪnˈvenʃən/",
        "stress": "in-VEN-tion",
        "emoji": "💡🔧",
        "ex": "The phone is one of the greatest inventions ever.",
        "ex_ko": "전화기는 역사상 가장 위대한 발명품 중 하나야.",
        "mnemonic": "invent(발명하다) + -tion(명사) = 발명품. '인벤토리'에 새로 만든 물건이 쌓인다고 생각해요."
      },
      {
        "n": 4,
        "en": "blind",
        "ko": "[형] 1. 눈 먼, 맹인의 2. 깨닫지[알아차리지] 못하는",
        "ipa": "/blaɪnd/",
        "stress": "BLIND",
        "emoji": "🙈🕶️",
        "ex": "My grandfather went blind in his left eye.",
        "ex_ko": "우리 할아버지는 왼쪽 눈이 안 보이게 되셨어.",
        "mnemonic": "창문 '블라인드'를 내리면 아무것도 안 보이죠. blind = 눈 먼."
      },
      {
        "n": 5,
        "en": "actual",
        "ko": "[형] 실제의, 사실의",
        "ipa": "/ˈæktʃuəl/",
        "stress": "AC-tu-al",
        "emoji": "✅🔍",
        "ex": "The actual price was higher than I expected.",
        "ex_ko": "실제 가격은 내가 생각한 것보다 비쌌어.",
        "mnemonic": "'액션(act)'은 진짜로 일어난 행동. 그래서 actual은 '실제의'."
      },
      {
        "n": 6,
        "en": "culture",
        "ko": "[명] 문화",
        "ipa": "/ˈkʌltʃər/",
        "stress": "CUL-ture",
        "emoji": "🌏🎎",
        "ex": "Korean culture is popular around the world now.",
        "ex_ko": "요즘 한국 문화는 전 세계에서 인기가 많아.",
        "mnemonic": "'컬처 쇼크'라는 말 그대로 문화. 밭을 갈아 키우듯 사람들이 가꿔온 것이 문화예요."
      },
      {
        "n": 7,
        "en": "lost",
        "ko": "[형] 1. 길을 잃은 2. 잃어버린, 분실된",
        "ipa": "/lɔst/",
        "stress": "LOST",
        "emoji": "🧭😵",
        "ex": "We got lost on the way to the museum.",
        "ex_ko": "우리는 박물관 가는 길에 길을 잃었어.",
        "mnemonic": "lose(잃다)의 과거분사가 lost. 게임에서 지면 뜨는 'LOST' 화면을 떠올려요."
      },
      {
        "n": 8,
        "en": "natural",
        "ko": "[형] 1. 자연의 2. 당연한, 자연스러운 3. 타고난, 선천적인",
        "ipa": "/ˈnætʃərəl/",
        "stress": "NA-tu-ral",
        "emoji": "🌿☀️",
        "ex": "This juice has no sugar, only natural flavor.",
        "ex_ko": "이 주스는 설탕 없이 자연 그대로의 맛만 나.",
        "mnemonic": "nature(자연) + -al(형용사) = 자연의. '내추럴한 화장'은 꾸미지 않은 자연스러운 것."
      },
      {
        "n": 9,
        "en": "breath",
        "ko": "[명] 숨, 호흡",
        "ipa": "/brɛθ/",
        "stress": "BREATH",
        "emoji": "😮‍💨🫁",
        "ex": "Take a deep breath before you start.",
        "ex_ko": "시작하기 전에 숨을 깊게 들이쉬어.",
        "mnemonic": "'브레스'—숨을 '후' 불면 브레스가 나와요. breathe(숨쉬다)의 명사형이 breath(숨)."
      },
      {
        "n": 10,
        "en": "excite",
        "ko": "[동] 흥분시키다, 들뜨게 하다",
        "ipa": "/ɪkˈsaɪt/",
        "stress": "ex-CITE",
        "emoji": "🤩🎉",
        "ex": "The new game really excites my little brother.",
        "ex_ko": "그 새 게임은 내 남동생을 정말 들뜨게 해.",
        "mnemonic": "'익사이트'—너무 신나서 '익! 사이다!' 하고 소리치는 장면을 떠올려요."
      },
      {
        "n": 11,
        "en": "garbage",
        "ko": "[명] 쓰레기",
        "ipa": "/ˈɡɑːrbɪdʒ/",
        "stress": "GAR-bage",
        "emoji": "🗑️🍌",
        "ex": "Please take the garbage out tonight.",
        "ex_ko": "오늘 밤에 쓰레기 좀 내다 버려 줘.",
        "mnemonic": "'가비지'—쓰레기 봉투를 '가방'에 담아 버린다고 기억해요."
      },
      {
        "n": 12,
        "en": "suck",
        "ko": "[동] 1. 빨아 마시다[먹다] 2. 빨다",
        "ipa": "/sʌk/",
        "stress": "SUCK",
        "emoji": "🥤😮",
        "ex": "The baby sucks milk from the bottle.",
        "ex_ko": "아기가 젖병에서 우유를 빨아 마셔.",
        "mnemonic": "'석'—빨대로 '쓱' 빨아 마시는 소리. 쓱쓱 빨아들이면 suck."
      },
      {
        "n": 13,
        "en": "prison",
        "ko": "[명] 교도소, 감옥",
        "ipa": "/ˈprɪzən/",
        "stress": "PRI-son",
        "emoji": "🏢⛓️",
        "ex": "The thief spent five years in prison.",
        "ex_ko": "그 도둑은 감옥에서 5년을 보냈어.",
        "mnemonic": "'프리즌'—free(자유)가 없는 zone(구역)! 자유 없는 곳이 감옥이에요."
      },
      {
        "n": 14,
        "en": "flow",
        "ko": "[동] 흐르다 / [명] 흐름",
        "ipa": "/floʊ/",
        "stress": "FLOW",
        "emoji": "🌊➡️",
        "ex": "The river flows into the sea.",
        "ex_ko": "그 강은 바다로 흘러 들어가.",
        "mnemonic": "'플로우'—물이 '플~' 하고 부드럽게 흘러가는 소리로 기억해요."
      },
      {
        "n": 15,
        "en": "solar",
        "ko": "[형] 1. 태양의, 태양에 관한 2. 태양열의",
        "ipa": "/ˈsoʊlər/",
        "stress": "SO-lar",
        "emoji": "☀️🔋",
        "ex": "Our school uses solar power for electricity.",
        "ex_ko": "우리 학교는 전기를 태양열로 만들어 써.",
        "mnemonic": "'솔라'—라틴어 sol이 '태양'. 솔라시도의 '솔'을 태양이라고 외워요."
      },
      {
        "n": 16,
        "en": "captain",
        "ko": "[명] 1. 선장, 기장 2. (팀의) 주장",
        "ipa": "/ˈkæptən/",
        "stress": "CAP-tain",
        "emoji": "🧢⚓",
        "ex": "Our team captain gave us a short speech.",
        "ex_ko": "우리 팀 주장이 우리에게 짧게 연설했어.",
        "mnemonic": "'캡틴'—모자(cap) 쓴 사람이 배의 선장이자 팀 주장이에요."
      },
      {
        "n": 17,
        "en": "dialogue",
        "ko": "[명] (소설, 영화 등의) 대화, 회화",
        "ipa": "/ˈdaɪəlɔːɡ/",
        "stress": "DI-a-logue",
        "emoji": "💬🗣️",
        "ex": "The movie had funny dialogue between two friends.",
        "ex_ko": "그 영화는 두 친구 사이의 웃긴 대화가 있었어.",
        "mnemonic": "'다이얼로그' — 전화 다이얼(dial) 돌려서 주고받는 말이 대화예요."
      },
      {
        "n": 18,
        "en": "fail",
        "ko": "[동] 1. 실패하다 2. (시험에) 떨어지다",
        "ipa": "/feɪl/",
        "stress": "FAIL",
        "emoji": "❌📉",
        "ex": "I studied hard so I didn't fail the test.",
        "ex_ko": "열심히 공부해서 시험에 떨어지지 않았어.",
        "mnemonic": "'페일' — 페인트가 벽에서 다 벗겨지듯 실패했다고 외워요."
      },
      {
        "n": 19,
        "en": "purse",
        "ko": "[명] (여성용) 지갑, 핸드백",
        "ipa": "/pɜːrs/",
        "stress": "PURSE",
        "emoji": "👛💰",
        "ex": "My mom keeps her cards in her purse.",
        "ex_ko": "엄마는 카드를 지갑에 넣어 두셔.",
        "mnemonic": "'퍼스' — 지갑을 확 퍼서 돈을 꺼낸다고 기억해요."
      },
      {
        "n": 20,
        "en": "mate",
        "ko": "[명] 1. 친구, 동료 2. (한 쌍을 이루는 동물의) 짝",
        "ipa": "/meɪt/",
        "stress": "MATE",
        "emoji": "🤝👬",
        "ex": "He is my best mate at school.",
        "ex_ko": "걔는 학교에서 내 제일 친한 친구야.",
        "mnemonic": "'메이트' — 룸메이트, 팀메이트처럼 짝이 되는 친구예요."
      },
      {
        "n": 21,
        "en": "villa",
        "ko": "[명] (휴가용) 주택, 별장, 저택",
        "ipa": "/ˈvɪlə/",
        "stress": "VIL-la",
        "emoji": "🏡🌴",
        "ex": "We stayed in a villa near the beach.",
        "ex_ko": "우리는 해변 근처 별장에서 머물렀어.",
        "mnemonic": "'빌라' — 우리가 아는 빌라보다 훨씬 좋은 휴가용 별장이에요."
      },
      {
        "n": 22,
        "en": "pick up",
        "ko": "1. …을 집어 들다 2. …을 (차에) 태우러 가다[오다]",
        "ipa": "/ˈpɪk ʌp/",
        "stress": "PICK up",
        "emoji": "🤏🚗",
        "ex": "My dad will pick me up after school.",
        "ex_ko": "아빠가 학교 끝나고 나를 데리러 오실 거야.",
        "mnemonic": "pick(집다) + up(위로) — 위로 집어 올리다, 사람도 차에 태워 올려요."
      },
      {
        "n": 23,
        "en": "help out",
        "ko": "도와주다",
        "ipa": "/ˈhelp aʊt/",
        "stress": "HELP out",
        "emoji": "🙌🤲",
        "ex": "I help out my mom in the kitchen.",
        "ex_ko": "나는 부엌에서 엄마를 도와드려.",
        "mnemonic": "help(돕다) + out(밖으로) — 힘든 상황 밖으로 꺼내 주는 게 도와주는 거예요."
      },
      {
        "n": 24,
        "en": "thanks to",
        "ko": "…의 덕분에, … 때문에",
        "ipa": "/ˈθæŋks tuː/",
        "stress": "THANKS to",
        "emoji": "🙏✨",
        "ex": "Thanks to my friend, I passed the exam.",
        "ex_ko": "친구 덕분에 나는 시험에 합격했어.",
        "mnemonic": "'~에게 감사(thanks)를 준다' — 그 사람 덕분이라는 뜻이에요."
      }
    ]
  },
  {
    "pack_id": "neungyul-voca-middle-2025-day08",
    "title": "능률VOCA 중등 필수 [2025] DAY 08",
    "source": "프렙업 영어학원 프린트 (PAGE 8/50)",
    "words": [
      {
        "n": 1,
        "en": "tear",
        "ko": "[명] 눈물 / [동] 찢다, 찢어지다",
        "ipa": "/tɪr/",
        "stress": "TEAR",
        "emoji": "😢💧",
        "ex": "A tear rolled down her cheek slowly.",
        "ex_ko": "눈물 한 방울이 그녀의 뺨을 타고 천천히 흘렀다.",
        "mnemonic": "티어 나게 울면 눈물! 찢을 때는 '테어' 하고 종이가 찢어지는 소리."
      },
      {
        "n": 2,
        "en": "gallery",
        "ko": "[명] 미술관",
        "ipa": "/ˈɡæləri/",
        "stress": "GAL-ler-y",
        "emoji": "🖼️🏛️",
        "ex": "We visited an art gallery on Sunday.",
        "ex_ko": "우리는 일요일에 미술관에 갔다.",
        "mnemonic": "'갤러리'는 우리도 그대로 쓰죠. 그림 걸어놓고 구경하는 곳!"
      },
      {
        "n": 3,
        "en": "result",
        "ko": "[명] 결과 / [동] (…의 결과로) 발생하다, 생기다",
        "ipa": "/rɪˈzʌlt/",
        "stress": "re-SULT",
        "emoji": "📊✅",
        "ex": "I'm nervous about my test results today.",
        "ex_ko": "오늘 시험 결과 때문에 긴장돼.",
        "mnemonic": "'리설트' — 게임 끝나면 뜨는 RESULT 화면. 다 끝난 뒤 나오는 게 결과."
      },
      {
        "n": 4,
        "en": "upstairs",
        "ko": "[부] 위층에[으로] / [명] 위층",
        "ipa": "/ˌʌpˈsterz/",
        "stress": "up-STAIRS",
        "emoji": "🪜⬆️🏠",
        "ex": "My room is upstairs next to the bathroom.",
        "ex_ko": "내 방은 위층 화장실 옆에 있어.",
        "mnemonic": "up(위로) + stairs(계단) = 계단 위로, 즉 위층!"
      },
      {
        "n": 5,
        "en": "living",
        "ko": "[형] 살아 있는 / [명] 생활비, 생계 수단",
        "ipa": "/ˈlɪvɪŋ/",
        "stress": "LIV-ing",
        "emoji": "🌱💰",
        "ex": "My uncle makes a living by fixing cars.",
        "ex_ko": "우리 삼촌은 자동차를 고쳐서 생계를 유지하신다.",
        "mnemonic": "live(살다)+ing → 살아 있는. 살려면 돈이 필요하니 '생계'도 됨."
      },
      {
        "n": 6,
        "en": "report",
        "ko": "[명] 보고(서) / [동] 1. 보고하다, 발표하다 2. 보도하다",
        "ipa": "/rɪˈpɔrt/",
        "stress": "re-PORT",
        "emoji": "📝📢",
        "ex": "I have to write a book report tonight.",
        "ex_ko": "나 오늘 밤에 독후감 써야 해.",
        "mnemonic": "'리포트' 그대로 쓰죠! 조사한 걸 다시(re) 날라다(port) 알리는 것."
      },
      {
        "n": 7,
        "en": "produce",
        "ko": "[동] 1. (곡물 등을) 생산하다 2. (상품 등을) 제조[생산]하다",
        "ipa": "/prəˈdus/",
        "stress": "pro-DUCE",
        "emoji": "🏭🌾",
        "ex": "This factory produces about a thousand phones daily.",
        "ex_ko": "이 공장은 하루에 약 천 대의 휴대폰을 생산한다.",
        "mnemonic": "'프로듀서'가 뭘 하죠? 노래·방송을 만들어내는 사람. produce는 만들어내다!"
      },
      {
        "n": 8,
        "en": "excited",
        "ko": "[형] 신이 난, 흥분한",
        "ipa": "/ɪkˈsaɪtɪd/",
        "stress": "ex-CI-ted",
        "emoji": "🤩🎉",
        "ex": "I'm so excited about the school trip tomorrow.",
        "ex_ko": "나 내일 수학여행 때문에 너무 신나.",
        "mnemonic": "'익사이팅'한 순간! 심장이 '싸이(cite)~' 하고 뛰며 신나는 상태."
      },
      {
        "n": 9,
        "en": "gather",
        "ko": "[동] 1. (사람들이) 모이다, (물건 등을) 모으다 2. (정보 등을) 수집하다",
        "ipa": "/ˈɡæðər/",
        "stress": "GA-ther",
        "emoji": "👥🧺",
        "ex": "Let's gather in the gym after lunch.",
        "ex_ko": "점심 먹고 체육관에 모이자.",
        "mnemonic": "\"개더\" 개들이 더 모인다! 사람도 물건도 한곳에 모으는 거예요."
      },
      {
        "n": 10,
        "en": "cause",
        "ko": "[명] 원인 / [동] 일으키다, …의 원인이 되다",
        "ipa": "/kɔːz/",
        "stress": "CAUSE",
        "emoji": "🔥➡️💨",
        "ex": "The heavy rain caused a big accident.",
        "ex_ko": "폭우가 큰 사고를 일으켰어.",
        "mnemonic": "'코즈'는 because 안에 들어 있는 cause! 결과를 일으키는 원인이에요."
      },
      {
        "n": 11,
        "en": "interested",
        "ko": "[형] 흥미 있는, 관심 있는",
        "ipa": "/ˈɪntrəstɪd/",
        "stress": "IN-ter-est-ed",
        "emoji": "🤩👀",
        "ex": "I'm really interested in K-pop dance.",
        "ex_ko": "난 케이팝 댄스에 정말 관심이 많아.",
        "mnemonic": "interest(관심)에 -ed가 붙어 \"관심이 생긴 상태\". 사람이 흥미를 느낄 땐 -ed예요."
      },
      {
        "n": 12,
        "en": "actually",
        "ko": "[부] 실제로, 정말로",
        "ipa": "/ˈæktʃuəli/",
        "stress": "AC-tu-al-ly",
        "emoji": "💡✅",
        "ex": "Actually, I already finished my homework.",
        "ex_ko": "사실 나 숙제 벌써 다 했어.",
        "mnemonic": "act(행동)+ually — 말이 아니라 실제 행동으로 그렇다는 뜻, \"사실은\"."
      },
      {
        "n": 13,
        "en": "talent",
        "ko": "[명] (타고난) 재능, 재주",
        "ipa": "/ˈtælənt/",
        "stress": "TA-lent",
        "emoji": "🎤🌟",
        "ex": "She has a real talent for singing.",
        "ex_ko": "걔는 노래에 진짜 재능이 있어.",
        "mnemonic": "\"탤런트\"는 연기 재능을 타고난 사람이죠. 타고난 재능이 talent예요."
      },
      {
        "n": 14,
        "en": "greet",
        "ko": "[동] 맞이하다, 환영하다",
        "ipa": "/ɡriːt/",
        "stress": "GREET",
        "emoji": "🙋👋",
        "ex": "My dog greets me at the door.",
        "ex_ko": "우리 개가 문 앞에서 날 반겨줘.",
        "mnemonic": "\"그리트\" 그리웠던 사람을 만나 반갑게 맞이한다!"
      },
      {
        "n": 15,
        "en": "lane",
        "ko": "[명] 1. 좁은 길, 도로 2. 차선 3. (육상, 수영 대회 등의) 레인",
        "ipa": "/leɪn/",
        "stress": "LANE",
        "emoji": "🛣️🏊",
        "ex": "The car moved into the fast lane.",
        "ex_ko": "그 차가 추월 차선으로 옮겨 갔어.",
        "mnemonic": "\"레인\" 수영장 레인처럼 길게 나뉜 좁은 길·차선이에요."
      },
      {
        "n": 16,
        "en": "stress",
        "ko": "[명] 1. 스트레스, 압박 2. 강조 / [동] 강조하다",
        "ipa": "/stres/",
        "stress": "STRESS",
        "emoji": "😩📌",
        "ex": "Exams give me a lot of stress.",
        "ex_ko": "시험은 나에게 스트레스를 많이 줘.",
        "mnemonic": "\"스트레스\" 그대로! 꾹 누르는 압박, 말할 때 꾹 눌러 강조하기도 해요."
      },
      {
        "n": 17,
        "en": "later",
        "ko": "[부] 후에, 나중에 / [형] 더 늦은, 더 나중의",
        "ipa": "/ˈleɪtər/",
        "stress": "LA-ter",
        "emoji": "⏰➡️",
        "ex": "I'll call you later tonight, okay?",
        "ex_ko": "오늘 밤 이따가 전화할게, 알았지?",
        "mnemonic": "late(늦은)에 -er이 붙어 '더 늦게', 즉 '나중에'가 돼요."
      },
      {
        "n": 18,
        "en": "create",
        "ko": "[동] 창조하다, 만들다",
        "ipa": "/kriˈeɪt/",
        "stress": "cre-ATE",
        "emoji": "🎨✨",
        "ex": "Let's create a new game together this weekend.",
        "ex_ko": "이번 주말에 같이 새 게임을 만들어 보자.",
        "mnemonic": "'크리에이터'는 영상을 만드는 사람이죠. create = 만들다, 창조하다."
      },
      {
        "n": 19,
        "en": "flat",
        "ko": "[형] 1. 평평한 2. (타이어 등이) 바람이 빠진, 펑크가 난",
        "ipa": "/flæt/",
        "stress": "FLAT",
        "emoji": "🛣️🛞",
        "ex": "My bike tire is flat again today.",
        "ex_ko": "내 자전거 타이어가 오늘 또 펑크 났어.",
        "mnemonic": "'플랫 슈즈'는 굽 없이 평평한 신발! 바람 빠져 납작해진 타이어도 flat."
      },
      {
        "n": 20,
        "en": "beat",
        "ko": "[동] 1. 때리다, 두드리다 2. 이기다",
        "ipa": "/biːt/",
        "stress": "BEAT",
        "emoji": "🥁🏆",
        "ex": "We beat their team by three points.",
        "ex_ko": "우리가 그 팀을 3점 차로 이겼어.",
        "mnemonic": "노래 '비트'는 북을 두드리는 소리! 두드리다 → 상대를 눌러 이기다."
      },
      {
        "n": 21,
        "en": "plus",
        "ko": "[전] 1. 더하기 2. 게다가, … 뿐만 아니라",
        "ipa": "/plʌs/",
        "stress": "PLUS",
        "emoji": "➕😀",
        "ex": "Two plus three is five, plus it's easy.",
        "ex_ko": "2 더하기 3은 5고, 게다가 쉬워.",
        "mnemonic": "'플러스' 기호 그대로 더하기. 문장 앞에 쓰면 '게다가'라는 뜻이에요."
      },
      {
        "n": 22,
        "en": "make noise",
        "ko": "소란을 피우다, 떠들다",
        "ipa": "/meɪk nɔɪz/",
        "stress": "make NOISE",
        "emoji": "📢🙉",
        "ex": "Please don't make noise during the movie.",
        "ex_ko": "영화 보는 동안 떠들지 말아 줘.",
        "mnemonic": "noise(소음)를 make(만들다) → 소음을 만들다 = 떠들다."
      },
      {
        "n": 23,
        "en": "hand in hand",
        "ko": "서로 손을 잡고",
        "ipa": "/hænd ɪn hænd/",
        "stress": "HAND in hand",
        "emoji": "🤝👫",
        "ex": "They walked hand in hand along the beach.",
        "ex_ko": "그들은 해변을 따라 손을 잡고 걸었다.",
        "mnemonic": "손(hand) 안에(in) 손(hand) — 서로 손을 맞잡은 그림 그대로예요."
      },
      {
        "n": 24,
        "en": "take care of",
        "ko": "…을 돌보다",
        "ipa": "/teɪk kɛr ʌv/",
        "stress": "take CARE of",
        "emoji": "🧸👶",
        "ex": "Can you take care of my dog tomorrow?",
        "ex_ko": "내일 우리 강아지 좀 돌봐 줄 수 있어?",
        "mnemonic": "care(돌봄)를 take(맡다) → 누군가를 맡아 돌보다."
      }
    ]
  },
  {
    "pack_id": "neungyul-voca-middle-2025-day09",
    "title": "능률VOCA 중등 필수 [2025] DAY 09",
    "source": "프렙업 영어학원 프린트 (PAGE 9/50)",
    "words": [
      {
        "n": 1,
        "en": "member",
        "ko": "[명] 회원, 일원",
        "ipa": "/ˈmembər/",
        "stress": "MEM-ber",
        "emoji": "👥🎫",
        "ex": "She is a member of our school band.",
        "ex_ko": "그녀는 우리 학교 밴드의 회원이야.",
        "mnemonic": "'멤버'는 이미 우리말로 쓰죠. 동아리 멤버 = 그 모임의 회원, 일원."
      },
      {
        "n": 2,
        "en": "serious",
        "ko": "[형] 1. (상태, 정도가) 심각한 2. 진지한",
        "ipa": "/ˈsɪriəs/",
        "stress": "SE-ri-ous",
        "emoji": "😐🚨",
        "ex": "Don't laugh, this is a serious problem.",
        "ex_ko": "웃지 마, 이건 심각한 문제야.",
        "mnemonic": "'시리어스'한 얼굴 = 웃음기 없이 굳은 표정. 심각하고 진지한 상태예요."
      },
      {
        "n": 3,
        "en": "afraid",
        "ko": "[형] 1. 두려워하는 2. 걱정하는",
        "ipa": "/əˈfreɪd/",
        "stress": "a-FRAID",
        "emoji": "😨🕷️",
        "ex": "I'm afraid of spiders in the bathroom.",
        "ex_ko": "난 욕실에 있는 거미가 무서워.",
        "mnemonic": "a + fraid(fright, 공포). 공포에 빠진 상태라서 두려워하는 거예요."
      },
      {
        "n": 4,
        "en": "dessert",
        "ko": "[명] 디저트, 후식",
        "ipa": "/dɪˈzɜːrt/",
        "stress": "de-SSERT",
        "emoji": "🍰🍨",
        "ex": "What's for dessert after dinner tonight?",
        "ex_ko": "오늘 저녁 먹고 디저트는 뭐야?",
        "mnemonic": "s가 두 개인 건 디저트는 한 번 더(second) 먹고 싶으니까! 사막(desert)은 s 하나."
      },
      {
        "n": 5,
        "en": "toothache",
        "ko": "[명] 치통",
        "ipa": "/ˈtuːθeɪk/",
        "stress": "TOOTH-ache",
        "emoji": "🦷😖",
        "ex": "I have a toothache, so I can't eat.",
        "ex_ko": "나 이가 아파서 못 먹겠어.",
        "mnemonic": "tooth(이) + ache(아픔) = 치통. ache는 '에이크', 아파서 '에잇!' 소리."
      },
      {
        "n": 6,
        "en": "effect",
        "ko": "[명] 1. 영향 2. 결과",
        "ipa": "/ɪˈfekt/",
        "stress": "e-FFECT",
        "emoji": "🎬✨",
        "ex": "The movie's special effects were really cool.",
        "ex_ko": "그 영화의 특수 효과 정말 멋있었어.",
        "mnemonic": "게임·영화의 '이펙트(효과)' 그대로예요. 원인 뒤에 따라오는 결과·영향."
      },
      {
        "n": 7,
        "en": "skillful",
        "ko": "[형] 숙련된, 능숙한",
        "ipa": "/ˈskɪlfl/",
        "stress": "SKILL-ful",
        "emoji": "🎯🛠️",
        "ex": "He is a skillful player on our team.",
        "ex_ko": "그는 우리 팀에서 능숙한 선수야.",
        "mnemonic": "skill(기술) + full(가득) = 기술이 가득한, 즉 능숙한."
      },
      {
        "n": 8,
        "en": "silence",
        "ko": "[명] 1. 고요, 정적 2. 침묵",
        "ipa": "/ˈsaɪləns/",
        "stress": "SI-lence",
        "emoji": "🤫🔇",
        "ex": "There was a long silence in the classroom.",
        "ex_ko": "교실에 긴 침묵이 흘렀어.",
        "mnemonic": "'사일런스'—폰의 사일런트 모드처럼 소리가 꺼진 상태, 고요·침묵."
      },
      {
        "n": 9,
        "en": "stomach",
        "ko": "[명] [소화기관] 위, 배",
        "ipa": "/ˈstʌmək/",
        "stress": "STOM-ach",
        "emoji": "🫃🍽️",
        "ex": "My stomach hurts after eating too much pizza.",
        "ex_ko": "피자를 너무 많이 먹었더니 배가 아파.",
        "mnemonic": "\"스터먹\" — 스트레스 받으면 먹고, 그게 다 위로 간다고 기억하세요."
      },
      {
        "n": 10,
        "en": "print",
        "ko": "[동] 1. 인쇄[출력]하다 2. 출판[발행]하다",
        "ipa": "/prɪnt/",
        "stress": "PRINT",
        "emoji": "🖨️📄",
        "ex": "Can you print this page for me, please?",
        "ex_ko": "이 페이지 좀 출력해 줄래?",
        "mnemonic": "프린터가 종이를 뽑아내는 그 동작이 바로 print입니다."
      },
      {
        "n": 11,
        "en": "safely",
        "ko": "[부] 안전하게, 무사히",
        "ipa": "/ˈseɪfli/",
        "stress": "SAFE-ly",
        "emoji": "🦺✅",
        "ex": "We arrived home safely before the storm started.",
        "ex_ko": "우리는 폭풍이 오기 전에 무사히 집에 도착했어.",
        "mnemonic": "safe(안전한) + ly(하게) = 안전하게. 금고(safe)처럼 무사히요."
      },
      {
        "n": 12,
        "en": "importance",
        "ko": "[명] 중요성",
        "ipa": "/ɪmˈpɔːrtəns/",
        "stress": "im-POR-tance",
        "emoji": "⭐❗",
        "ex": "My teacher talked about the importance of sleep.",
        "ex_ko": "선생님이 잠의 중요성에 대해 말씀하셨어.",
        "mnemonic": "important(중요한)에 -ance 붙여 명사로. \"임포턴스\" = 중요함."
      },
      {
        "n": 13,
        "en": "review",
        "ko": "[동] 1. 검토하다 2. 평론[비평]하다 3. 복습하다 / [명] 1. 검토 2. 평론[비평] 3. 복습",
        "ipa": "/rɪˈvjuː/",
        "stress": "re-VIEW",
        "emoji": "🔁👀📝",
        "ex": "I need to review my notes before the test.",
        "ex_ko": "시험 전에 필기를 복습해야 해.",
        "mnemonic": "re(다시) + view(보다) = 다시 보다 → 복습, 검토."
      },
      {
        "n": 14,
        "en": "strange",
        "ko": "[형] 1. 이상한 2. 낯선",
        "ipa": "/streɪndʒ/",
        "stress": "STRANGE",
        "emoji": "🤨👽",
        "ex": "That's a strange noise coming from upstairs.",
        "ex_ko": "위층에서 이상한 소리가 나는데.",
        "mnemonic": "\"스트레인지\" — 스트레스 받게 낯설고 이상한 느낌으로 외우세요."
      },
      {
        "n": 15,
        "en": "burn",
        "ko": "[동] (불에) 타다, 태우다",
        "ipa": "/bɜːrn/",
        "stress": "BURN",
        "emoji": "🔥",
        "ex": "Be careful, don't burn your hand on the pan!",
        "ex_ko": "조심해, 팬에 손 데지 마!",
        "mnemonic": "\"번!\" 하고 불이 번지는 소리 — 타다, 태우다."
      },
      {
        "n": 16,
        "en": "talented",
        "ko": "[형] 재능 있는, 유능한",
        "ipa": "/ˈtæləntɪd/",
        "stress": "TAL-ent-ed",
        "emoji": "🎤🌟",
        "ex": "She is a talented singer in our school band.",
        "ex_ko": "그 애는 우리 학교 밴드의 재능 있는 가수야.",
        "mnemonic": "탤런트(talent)는 재능 있는 사람. 거기에 -ed 붙여 \"재능 있는\"."
      },
      {
        "n": 17,
        "en": "bare",
        "ko": "[형] 벌거벗은, 살을 드러낸",
        "ipa": "/ber/",
        "stress": "BARE",
        "emoji": "🦶🌳",
        "ex": "Don't walk on the hot sand with bare feet.",
        "ex_ko": "뜨거운 모래 위를 맨발로 걷지 마.",
        "mnemonic": "곰(bear)이 털 없이 '베어'진 모습 — 벌거벗은 상태. 소리는 곰과 똑같아요."
      },
      {
        "n": 18,
        "en": "housework",
        "ko": "[명] 집안일, 가사",
        "ipa": "/ˈhaʊsˌwɜːrk/",
        "stress": "HOUSE-work",
        "emoji": "🧹🧺🏠",
        "ex": "I have to do the housework before dinner.",
        "ex_ko": "나 저녁 먹기 전에 집안일 해야 해.",
        "mnemonic": "house(집) + work(일) = 집안일. 숙제는 homework, 집안일은 housework!"
      },
      {
        "n": 19,
        "en": "however",
        "ko": "[부] 그러나, 그렇지만",
        "ipa": "/haʊˈevər/",
        "stress": "how-EV-er",
        "emoji": "🔄🤔",
        "ex": "I studied hard. However, I failed the test.",
        "ex_ko": "나 열심히 공부했어. 그러나 시험을 망쳤어.",
        "mnemonic": "how(어떻게) + ever(도대체) — '아무리 그래도'가 '그러나'로. 앞말을 뒤집는 신호."
      },
      {
        "n": 20,
        "en": "accept",
        "ko": "[동] 받아들이다, 수락하다",
        "ipa": "/əkˈsept/",
        "stress": "ac-CEPT",
        "emoji": "🤝🎁✅",
        "ex": "She decided to accept his apology.",
        "ex_ko": "그녀는 그의 사과를 받아들이기로 했어.",
        "mnemonic": "ac(~에게) + cept(잡다). 내미는 걸 손으로 잡아 받아들이는 장면이에요."
      },
      {
        "n": 21,
        "en": "mark",
        "ko": "[명] 1. 자국, 얼룩 2. 표시 / [동] 표시하다",
        "ipa": "/mɑːrk/",
        "stress": "MARK",
        "emoji": "🖊️🔵",
        "ex": "There's a dirty mark on your white shirt.",
        "ex_ko": "네 흰 셔츠에 더러운 얼룩이 있어.",
        "mnemonic": "매직으로 '마크' 찍기 — 찍으면 표시, 남으면 자국. 마크 표시가 곧 얼룩."
      },
      {
        "n": 22,
        "en": "not ... anymore",
        "ko": "더 이상 … 않다",
        "ipa": "/nɑːt ˌeniˈmɔːr/",
        "stress": "NOT ... an-y-MORE",
        "emoji": "🚫⏹️",
        "ex": "I don't play that game anymore.",
        "ex_ko": "나 그 게임 더 이상 안 해.",
        "mnemonic": "not(안) + any more(더) = '더는 안'. 문장 맨 끝에 붙여서 '이제 끝!'을 표시해요."
      },
      {
        "n": 23,
        "en": "pass through",
        "ko": "지나가다, 통과하다",
        "ipa": "/pæs θruː/",
        "stress": "PASS through",
        "emoji": "🚶🚪➡️",
        "ex": "The train passes through our town every hour.",
        "ex_ko": "그 기차는 한 시간마다 우리 마을을 지나가.",
        "mnemonic": "pass(지나가다) + through(관통) = 뚫고 지나가다. 터널을 통과하는 기차를 떠올려요."
      },
      {
        "n": 24,
        "en": "in fact",
        "ko": "사실은",
        "ipa": "/ɪn fækt/",
        "stress": "in FACT",
        "emoji": "💡🗣️",
        "ex": "He looks young. In fact, he's forty.",
        "ex_ko": "그는 어려 보여. 사실은 마흔이야.",
        "mnemonic": "fact(사실) 안으로 들어가면 '사실은'. 겉모습 말한 뒤 진짜를 밝힐 때 써요."
      }
    ]
  },
  {
    "pack_id": "neungyul-voca-middle-2025-day10",
    "title": "능률VOCA 중등 필수 [2025] DAY 10",
    "source": "프렙업 영어학원 프린트 (PAGE 10/50)",
    "words": [
      {
        "n": 1,
        "en": "return",
        "ko": "[동] 1. 돌아가다[오다] 2. 돌려주다, 반납하다 / [명] 돌아감, 귀환",
        "ipa": "/rɪˈtɜːrn/",
        "stress": "re-TURN",
        "emoji": "🔙📚",
        "ex": "I have to return this book today.",
        "ex_ko": "나 오늘 이 책 반납해야 해.",
        "mnemonic": "re(다시) + turn(돌다) = 다시 돌아가다, 돌려주다."
      },
      {
        "n": 2,
        "en": "press",
        "ko": "[동] 누르다 / [명] 언론, 신문",
        "ipa": "/pres/",
        "stress": "PRESS",
        "emoji": "👆🔘",
        "ex": "Press this button to start the game.",
        "ex_ko": "게임을 시작하려면 이 버튼을 눌러.",
        "mnemonic": "'프레스'로 꾹 누르는 기계 생각! 신문도 종이를 눌러 찍어서 press."
      },
      {
        "n": 3,
        "en": "focus",
        "ko": "[동] 집중하다, 집중시키다 / [명] 초점, 중점",
        "ipa": "/ˈfoʊkəs/",
        "stress": "FO-cus",
        "emoji": "🎯🔍",
        "ex": "I can't focus with all this noise.",
        "ex_ko": "이렇게 시끄러우면 집중이 안 돼.",
        "mnemonic": "'포커스'는 카메라 초점! 한 곳에 초점을 맞추는 게 집중하다."
      },
      {
        "n": 4,
        "en": "dictionary",
        "ko": "[명] 사전",
        "ipa": "/ˈdɪkʃəneri/",
        "stress": "DIC-tion-ar-y",
        "emoji": "📖🔤",
        "ex": "Look up the word in your dictionary.",
        "ex_ko": "그 단어를 사전에서 찾아봐.",
        "mnemonic": "'딕션(diction, 말)'을 모아둔 책 = 사전. 말이 다 들어있는 책이야."
      },
      {
        "n": 5,
        "en": "allow",
        "ko": "[동] 허락하다, 허용하다",
        "ipa": "/əˈlaʊ/",
        "stress": "al-LOW",
        "emoji": "✅🙆",
        "ex": "My mom doesn't allow me to stay out late.",
        "ex_ko": "엄마는 내가 늦게까지 밖에 있는 걸 허락 안 하셔.",
        "mnemonic": "'얼라우' → '얼른 하우(해)!' 하고 허락해 주는 느낌."
      },
      {
        "n": 6,
        "en": "breathe",
        "ko": "[동] 숨 쉬다, 호흡하다",
        "ipa": "/briːð/",
        "stress": "BREATHE",
        "emoji": "😮‍💨🫁",
        "ex": "Just breathe slowly and calm down.",
        "ex_ko": "천천히 숨 쉬면서 진정해.",
        "mnemonic": "'브리~드' 하고 길게 소리 내보면 그게 바로 숨 쉬는 거야."
      },
      {
        "n": 7,
        "en": "trash",
        "ko": "[명] 쓰레기",
        "ipa": "/træʃ/",
        "stress": "TRASH",
        "emoji": "🗑️🍌",
        "ex": "Please take out the trash tonight.",
        "ex_ko": "오늘 밤에 쓰레기 좀 내다 버려.",
        "mnemonic": "'트래쉬' → '트럭에 쓸어(래쉬) 담는 쓰레기'로 기억!"
      },
      {
        "n": 8,
        "en": "success",
        "ko": "[명] 성공, 성과",
        "ipa": "/səkˈses/",
        "stress": "suc-CESS",
        "emoji": "🏆🎉",
        "ex": "Hard work is the key to success.",
        "ex_ko": "노력이 성공의 열쇠야.",
        "mnemonic": "'석세스' → '(어깨) 석! 세워' 성공하면 어깨가 으쓱 올라가지."
      },
      {
        "n": 9,
        "en": "rise",
        "ko": "[동] 1. 오르다, 상승하다 2. 일어나다 3. (해, 달이) 뜨다",
        "ipa": "/raɪz/",
        "stress": "RISE",
        "emoji": "📈🌅",
        "ex": "The sun will rise at six tomorrow.",
        "ex_ko": "내일 해는 6시에 뜰 거야.",
        "mnemonic": "라이즈! 하고 몸을 일으키며 해가 떠오르는 장면을 떠올려요."
      },
      {
        "n": 10,
        "en": "topic",
        "ko": "[명] 주제, 화제",
        "ipa": "/ˈtɑːpɪk/",
        "stress": "TO-pic",
        "emoji": "💬📋",
        "ex": "Let's change the topic to something fun.",
        "ex_ko": "더 재미있는 주제로 바꾸자.",
        "mnemonic": "'톱(top)'에 적힌 제목이 곧 주제예요. 맨 위에 오는 게 화제죠."
      },
      {
        "n": 11,
        "en": "scare",
        "ko": "[동] 겁주다, 겁나게 하다",
        "ipa": "/sker/",
        "stress": "SCARE",
        "emoji": "😱👻",
        "ex": "Don't scare me like that again!",
        "ex_ko": "다시는 그렇게 나 겁주지 마!",
        "mnemonic": "'스케어'가 '스산해'처럼 들려요. 스산하면 겁이 나죠."
      },
      {
        "n": 12,
        "en": "step",
        "ko": "[명] 1. (발)걸음 2. 조치 3. 단계",
        "ipa": "/step/",
        "stress": "STEP",
        "emoji": "👣🪜",
        "ex": "Take one more step and stop.",
        "ex_ko": "한 걸음 더 가고 멈춰.",
        "mnemonic": "스텝 밟는다는 말 그대로 발걸음, 계단 한 칸씩 오르는 단계예요."
      },
      {
        "n": 13,
        "en": "cooking",
        "ko": "[명] 요리(하기) / [형] 요리(용)의",
        "ipa": "/ˈkʊkɪŋ/",
        "stress": "COOK-ing",
        "emoji": "🍳👨‍🍳",
        "ex": "My mom is cooking dinner right now.",
        "ex_ko": "우리 엄마는 지금 저녁을 요리하고 계셔.",
        "mnemonic": "cook(요리하다) + ing = 요리하기. '쿡쿡' 찔러가며 음식을 익히는 모습이에요."
      },
      {
        "n": 14,
        "en": "anger",
        "ko": "[명] 화, 분노",
        "ipa": "/ˈæŋɡər/",
        "stress": "AN-ger",
        "emoji": "😡🔥",
        "ex": "He couldn't hide his anger at school.",
        "ex_ko": "그는 학교에서 화를 감출 수 없었어.",
        "mnemonic": "'앵거'가 '앵!' 하고 성내는 소리 같아요. 앵! 하면 화가 난 거죠."
      },
      {
        "n": 15,
        "en": "own",
        "ko": "[형] 자기 자신의 / [동] 소유하다",
        "ipa": "/oʊn/",
        "stress": "OWN",
        "emoji": "🙋🔑",
        "ex": "I want my own room someday.",
        "ex_ko": "언젠가 내 방을 갖고 싶어.",
        "mnemonic": "'오운'을 '오! 내 것'으로 기억해요. 내 자신의 것, 소유하다."
      },
      {
        "n": 16,
        "en": "praise",
        "ko": "[동] 칭찬하다 / [명] 칭찬, 찬양",
        "ipa": "/preɪz/",
        "stress": "PRAISE",
        "emoji": "👏🌟",
        "ex": "My teacher gave me praise for my work.",
        "ex_ko": "선생님이 내 과제를 칭찬해 주셨어.",
        "mnemonic": "'프레이즈' — 잘했다고 박수 치며 칭찬하는 소리로 기억해요."
      },
      {
        "n": 17,
        "en": "continue",
        "ko": "[동] 계속되다, 계속하다",
        "ipa": "/kənˈtɪnjuː/",
        "stress": "con-TIN-ue",
        "emoji": "▶️➡️",
        "ex": "The rain will continue until tomorrow morning.",
        "ex_ko": "비는 내일 아침까지 계속 올 거야.",
        "mnemonic": "con(함께) + tinue(잡다). 손을 놓지 않고 계속 이어가는 거예요."
      },
      {
        "n": 18,
        "en": "wooden",
        "ko": "[형] 나무로 된, 목재의",
        "ipa": "/ˈwʊdən/",
        "stress": "WOOD-en",
        "emoji": "🪵🪑",
        "ex": "We sat on an old wooden bench.",
        "ex_ko": "우리는 오래된 나무 벤치에 앉았어.",
        "mnemonic": "wood(나무) + -en(~로 된) = 나무로 된."
      },
      {
        "n": 19,
        "en": "certain",
        "ko": "[형] 1. 확실한, 확신하는 2. 어떤, 특정한",
        "ipa": "/ˈsɜːrtən/",
        "stress": "CER-tain",
        "emoji": "✅🤔",
        "ex": "I'm certain I locked the front door.",
        "ex_ko": "나 현관문 잠근 거 확실해.",
        "mnemonic": "'써튼(서든)' 확신에 차서 서 있는 모습. 확실한!"
      },
      {
        "n": 20,
        "en": "less",
        "ko": "[형] 더 적은, 덜한 / [부] 더 적게, 덜하게",
        "ipa": "/les/",
        "stress": "LESS",
        "emoji": "📉🤏",
        "ex": "I want less sugar in my coffee.",
        "ex_ko": "커피에 설탕 좀 덜 넣어줘.",
        "mnemonic": "little(적은)의 비교급이 less. 더 적은, 덜한."
      },
      {
        "n": 21,
        "en": "entire",
        "ko": "[형] 전체의",
        "ipa": "/ɪnˈtaɪər/",
        "stress": "en-TIRE",
        "emoji": "🌐🍰",
        "ex": "He ate the entire pizza by himself.",
        "ex_ko": "걔는 피자 한 판을 통째로 혼자 먹었어.",
        "mnemonic": "'인타이어' — 타이어 전체가 하나로 이어진 원. 전체의."
      },
      {
        "n": 22,
        "en": "at least",
        "ko": "적어도, 최소한",
        "ipa": "/æt ˈliːst/",
        "stress": "at LEAST",
        "emoji": "☝️📏",
        "ex": "You should sleep at least seven hours.",
        "ex_ko": "적어도 일곱 시간은 자야 해.",
        "mnemonic": "least(가장 적은)에 at을 붙이면 '가장 적어도' = 최소한."
      },
      {
        "n": 23,
        "en": "no longer",
        "ko": "더 이상 … 않다",
        "ipa": "/noʊ ˈlɔːŋɡər/",
        "stress": "no LON-ger",
        "emoji": "🚫⏳",
        "ex": "She no longer lives in this town.",
        "ex_ko": "그 애는 더 이상 이 동네에 안 살아.",
        "mnemonic": "no(아니) + longer(더 오래) = 더 이상 오래 안 함."
      },
      {
        "n": 24,
        "en": "look up",
        "ko": "1. (정보 등을) 찾아보다 2. 올려다보다",
        "ipa": "/lʊk ʌp/",
        "stress": "LOOK up",
        "emoji": "🔎📖⬆️",
        "ex": "Let's look up the answer online.",
        "ex_ko": "온라인으로 답을 찾아보자.",
        "mnemonic": "사전 위쪽(up)을 훑어보며(look) 찾는다. 올려다보기도 그대로."
      }
    ]
  }
];
